'use strict';
const {query,transaction}=require('../db');
const emailSettings=require('../integrations/email-settings');
const emailOutbox=require('../integrations/email-outbox');
const runtimeSettings=require('../platform/runtime-settings');
const operations=require('../platform/operations-settings');
const KEY='activation_cleanup_v1';
async function settings(){const r=await query('SELECT setting_value FROM platform_settings WHERE setting_key=$1',[KEY]),v=r.rows[0]?.setting_value||{};return{enabled:v.enabled===true,retentionDays:Math.max(7,Math.min(365,Number(v.retentionDays)||30)),warningDays:Math.max(1,Math.min(30,Number(v.warningDays)||7))}}
async function candidates(cfg){const r=await query(`SELECT u.id user_id,u.email,u.username,c.id customer_id,t.id token_id,t.created_at,t.expires_at,EXTRACT(DAY FROM(NOW()-t.created_at))::int age_days FROM account_activation_tokens t JOIN app_users u ON u.id=t.user_id JOIN customers c ON c.user_id=u.id WHERE t.purpose='customer_activation' AND t.used_at IS NULL AND t.revoked_at IS NULL AND u.role='customer' AND NOT EXISTS(SELECT 1 FROM subscriptions s WHERE s.customer_id=c.id) AND NOT EXISTS(SELECT 1 FROM jellyfin_accounts ja WHERE ja.customer_id=c.id) AND NOT EXISTS(SELECT 1 FROM reseller_sales rs WHERE rs.customer_id=c.id) AND NOT EXISTS(SELECT 1 FROM content_requests cr WHERE cr.customer_id=c.id) AND t.created_at<=NOW()-($1::int||' days')::interval ORDER BY t.created_at`,[Math.max(0,cfg.retentionDays-cfg.warningDays)]);return r.rows}
async function warn(row,cfg){if(!row.email)return false;const mail=await emailSettings.status();if(!mail.configured)return false;await runtimeSettings.ensureLoaded();const deadline=new Date(new Date(row.created_at).getTime()+cfg.retentionDays*86400000),base=(await operations.get()).publicBaseUrl||'',url=base?`${base.replace(/\/$/,'')}/account/login`:'';return emailOutbox.enqueue({type:'activation_cleanup_warning',to:row.email,subject:`Complete your ${runtimeSettings.siteName()} account setup`,text:`Your unused account setup will be removed after ${deadline.toLocaleDateString('en-GB')} if activation is not completed.${url?`\n\nSign in / activate: ${url}`:''}`,dedupeKey:`activation-cleanup-warning:${row.user_id}:${deadline.toISOString().slice(0,10)}`})}
async function remove(row,cfg){if(Number(row.age_days)<cfg.retentionDays)return false;return transaction(async client=>{const safe=await client.query(`SELECT c.id FROM customers c JOIN app_users u ON u.id=c.user_id WHERE c.id=$1 AND u.id=$2 AND NOT EXISTS(SELECT 1 FROM subscriptions s WHERE s.customer_id=c.id) AND NOT EXISTS(SELECT 1 FROM jellyfin_accounts ja WHERE ja.customer_id=c.id) AND NOT EXISTS(SELECT 1 FROM reseller_sales rs WHERE rs.customer_id=c.id) FOR UPDATE OF c,u`,[row.customer_id,row.user_id]);if(!safe.rowCount)return false;await client.query(`UPDATE account_activation_tokens SET revoked_at=NOW() WHERE user_id=$1 AND used_at IS NULL AND revoked_at IS NULL`,[row.user_id]);await client.query(`INSERT INTO audit_log(action,entity_type,entity_id,metadata) VALUES('customer.activation.abandoned_cleanup','customer',$1,$2::jsonb)`,[row.customer_id,JSON.stringify({userId:row.user_id,retentionDays:cfg.retentionDays})]);await client.query('DELETE FROM customers WHERE id=$1',[row.customer_id]);await client.query('DELETE FROM app_users WHERE id=$1',[row.user_id]);return true})}
async function process(){const cfg=await settings();if(!cfg.enabled)return{processed:0,skipped:'disabled'};const rows=await candidates(cfg);let warned=0,removed=0;for(const row of rows){try{if(Number(row.age_days)>=cfg.retentionDays){if(await remove(row,cfg))removed++}else if(await warn(row,cfg))warned++}catch(error){console.error(`Activation cleanup failed for ${row.user_id}:`,error.message)}}return{processed:rows.length,warned,removed}}
module.exports={settings,candidates,process,remove};
