'use strict';

const {query,transaction}=require('../db');
const outbox=require('../integrations/email-outbox');

const SEGMENTS=new Set(['no_active_subscription','expired_subscription','all_opted_in']);
function clean(value,min,max,label){const text=String(value||'').trim();if(text.length<min||text.length>max)throw new Error(`${label} must be between ${min} and ${max} characters.`);return text;}
function segment(value){const key=String(value||'no_active_subscription').trim();if(!SEGMENTS.has(key))throw new Error('Invalid marketing segment.');return key;}
function scheduleTime(value){const parsed=new Date(String(value||''));if(Number.isNaN(parsed.getTime()))throw new Error('Choose a valid campaign schedule time.');const minimum=Date.now()+30_000,maximum=Date.now()+366*24*60*60*1000;if(parsed.getTime()<minimum)throw new Error('Schedule the campaign at least 30 seconds in the future.');if(parsed.getTime()>maximum)throw new Error('Campaigns can be scheduled up to one year ahead.');return parsed;}
async function validateDiscount(code){const value=String(code||'').trim();if(!value)return null;const row=(await query(`SELECT code FROM discount_codes WHERE UPPER(code)=UPPER($1) AND active=TRUE AND (expires_at IS NULL OR expires_at>NOW())`,[value])).rows[0];if(!row)throw new Error('Choose an active, unexpired discount code.');return row.code;}
function eligibleWhere(key){const active=`EXISTS (SELECT 1 FROM subscriptions s WHERE s.customer_id=c.id AND s.status IN ('active','trialing','past_due','paused'))`;if(key==='no_active_subscription')return `NOT ${active}`;if(key==='expired_subscription')return `NOT ${active} AND EXISTS (SELECT 1 FROM subscriptions old WHERE old.customer_id=c.id)`;return 'TRUE';}
async function eligible(segmentKey){const key=segment(segmentKey),where=eligibleWhere(key);return(await query(`SELECT c.id customer_id,c.login_email email,COALESCE(NULLIF(c.display_name,''),NULLIF(c.login_username,''),c.login_email) display_name FROM customers c JOIN customer_communication_preferences cp ON cp.customer_id=c.id WHERE cp.marketing_email_opt_in=TRUE AND NULLIF(TRIM(c.login_email),'') IS NOT NULL AND ${where} ORDER BY c.created_at DESC`)).rows;}
async function preview(segmentKey){const rows=await eligible(segmentKey);return{count:rows.length,sample:rows.slice(0,25)};}
async function create({name,subject,bodyText,discountCode,segmentKey,adminUserId}){const campaignName=clean(name,3,160,'Campaign name'),mailSubject=clean(subject,3,300,'Subject'),body=clean(bodyText,1,100000,'Message'),key=segment(segmentKey),discount=await validateDiscount(discountCode);const row=(await query(`INSERT INTO marketing_campaigns(name,subject,body_text,discount_code,segment_key,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[campaignName,mailSubject,body,discount,key,adminUserId])).rows[0];await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'marketing.campaign.create','marketing_campaign',$2,$3::jsonb)`,[adminUserId,row.id,JSON.stringify({segment:key,discountCode:discount})]);return row;}
async function list(){return(await query(`SELECT c.*,COUNT(r.id)::int snapshotted,COUNT(r.id) FILTER(WHERE r.status='queued')::int recipients_queued FROM marketing_campaigns c LEFT JOIN marketing_campaign_recipients r ON r.campaign_id=c.id GROUP BY c.id ORDER BY c.created_at DESC LIMIT 250`)).rows;}
async function get(id){const campaign=(await query(`SELECT * FROM marketing_campaigns WHERE id=$1`,[id])).rows[0];if(!campaign)return null;const recipients=(await query(`SELECT * FROM marketing_campaign_recipients WHERE campaign_id=$1 ORDER BY created_at,email_snapshot LIMIT 500`,[id])).rows;return{campaign,recipients};}
async function snapshotRecipients(campaign){const candidates=await eligible(campaign.segment_key);await transaction(async client=>{for(const person of candidates){await client.query(`INSERT INTO marketing_campaign_recipients(campaign_id,customer_id,email_snapshot,display_name_snapshot) VALUES($1,$2,$3,$4) ON CONFLICT(campaign_id,customer_id) DO NOTHING`,[campaign.id,person.customer_id,person.email,person.display_name]);}await client.query(`UPDATE marketing_campaigns SET recipient_count=(SELECT COUNT(*) FROM marketing_campaign_recipients WHERE campaign_id=$1),updated_at=NOW() WHERE id=$1`,[campaign.id]);});return candidates.length;}
function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[ch]));}
function renderMessage(campaign,recipient,storefrontUrl){const name=recipient.display_name_snapshot||'there',discount=campaign.discount_code?`\n\nDiscount code: ${campaign.discount_code}`:'',link=storefrontUrl?`\n\nView plans: ${storefrontUrl}`:'';const text=`Hi ${name},\n\n${campaign.body_text}${discount}${link}\n\nYou are receiving this because you opted in to marketing email in your CAPTAiNFiN account. You can switch marketing email off from your notification preferences.`;const html=`<p>Hi ${escapeHtml(name)},</p>${campaign.body_text.split(/\n{2,}/).map(p=>`<p>${escapeHtml(p).replace(/\n/g,'<br>')}</p>`).join('')}${campaign.discount_code?`<p><strong>Discount code: ${escapeHtml(campaign.discount_code)}</strong></p>`:''}${storefrontUrl?`<p><a href="${escapeHtml(storefrontUrl)}">View available plans</a></p>`:''}<p><small>You are receiving this because you opted in to marketing email in your CAPTAiNFiN account. You can switch marketing email off from your notification preferences.</small></p>`;return{text,html};}
async function schedule({campaignId,scheduledFor,adminUserId}){const when=scheduleTime(scheduledFor);const result=await query(`UPDATE marketing_campaigns SET status='scheduled',scheduled_for=$2,schedule_attempts=0,schedule_last_error=NULL,updated_at=NOW() WHERE id=$1 AND status IN ('draft','scheduled') RETURNING *`,[campaignId,when]);if(!result.rowCount)throw new Error('Only draft or already scheduled campaigns can be scheduled.');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'marketing.campaign.schedule','marketing_campaign',$2,$3::jsonb)`,[adminUserId,campaignId,JSON.stringify({scheduledFor:when.toISOString()})]);return result.rows[0];}
async function unschedule({campaignId,adminUserId}){const result=await query(`UPDATE marketing_campaigns SET status='draft',scheduled_for=NULL,schedule_attempts=0,schedule_last_error=NULL,updated_at=NOW() WHERE id=$1 AND status='scheduled' RETURNING *`,[campaignId]);if(!result.rowCount)throw new Error('Only scheduled campaigns can be returned to draft.');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'marketing.campaign.unschedule','marketing_campaign',$2,'{}'::jsonb)`,[adminUserId,campaignId]);return result.rows[0];}
async function queue({campaignId,adminUserId=null,storefrontUrl=''}){let data=await get(campaignId);if(!data)throw new Error('Campaign not found.');if(!['draft','scheduled','queued'].includes(data.campaign.status))throw new Error('Only draft, scheduled or partially queued campaigns can be queued.');await snapshotRecipients(data.campaign);data=await get(campaignId);if(!data.recipients.length)throw new Error('No eligible opted-in recipients are available for this campaign.');let queued=0;for(const recipient of data.recipients){if(recipient.status==='queued')continue;const message=renderMessage(data.campaign,recipient,storefrontUrl);const item=await outbox.enqueue({type:'marketing_campaign',to:recipient.email_snapshot,subject:data.campaign.subject,text:message.text,html:message.html,dedupeKey:`marketing:${data.campaign.id}:${recipient.customer_id}`});await query(`UPDATE marketing_campaign_recipients SET status='queued',outbox_id=$2,updated_at=NOW() WHERE id=$1`,[recipient.id,item.id]);queued+=1;}await query(`UPDATE marketing_campaigns SET status='queued',queued_count=(SELECT COUNT(*) FROM marketing_campaign_recipients WHERE campaign_id=$1 AND status='queued'),queued_at=COALESCE(queued_at,NOW()),schedule_last_error=NULL,updated_at=NOW() WHERE id=$1`,[campaignId]);await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'marketing.campaign.queue','marketing_campaign',$2,$3::jsonb)`,[adminUserId,campaignId,JSON.stringify({queuedNow:queued,scheduled:Boolean(data.campaign.scheduled_for)})]);return{queued};}
async function due(limit=20){return(await query(`SELECT id FROM marketing_campaigns WHERE status='scheduled' AND scheduled_for<=NOW() ORDER BY scheduled_for,id LIMIT $1`,[Math.max(1,Math.min(100,Number(limit)||20))])).rows;}
async function runDue({limit=20,storefrontUrl='' }={}){const rows=await due(limit),result={total:rows.length,processed:0,failed:0};for(const row of rows){try{await queue({campaignId:row.id,adminUserId:null,storefrontUrl});result.processed+=1;}catch(error){result.failed+=1;await query(`UPDATE marketing_campaigns SET schedule_attempts=schedule_attempts+1,schedule_last_error=$2,updated_at=NOW() WHERE id=$1 AND status='scheduled'`,[row.id,String(error?.message||error).slice(0,1500)]);}}return result;}
module.exports={SEGMENTS,segment,eligible,preview,create,list,get,queue,schedule,unschedule,due,runDue,validateDiscount,renderMessage,scheduleTime};
