'use strict';

const crypto=require('crypto');
const {query,transaction}=require('../db');
const outbound=require('../security/outbound-url-policy');
const {encryptWithEnv,decryptWithEnv}=require('../security/purpose-crypto');
const foundation=require('./foundation');

const TOKEN_ENV='STREMIO_JELLYFIN_TOKEN_KEY';
const TOKEN_PREFIX='stremio-source-token';
const SETTINGS_KEY='stremio_source_pool_v1';
function cleanText(v,n=200){return String(v||'').trim().slice(0,n);}
function int(v,min,max,fallback){const n=Number.parseInt(v,10);return Number.isInteger(n)&&n>=min&&n<=max?n:fallback;}
function httpUrl(v,label){let u;try{u=new URL(String(v||'').trim());}catch{throw new Error(`${label} is invalid.`)}if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.hash)throw new Error(`${label} must be an http(s) URL without embedded credentials or a fragment.`);return u.toString().replace(/\/$/,'');}
function authHeader(token,deviceId='captainfin-stremio-bridge'){if(/[\r\n]/.test(String(token||'')))throw new Error('Invalid Jellyfin source token');return `MediaBrowser Client="CAPTaINFiN Stremio", Device="CAPTaINFiN Bridge", DeviceId="${deviceId}", Version="1.0", Token="${token}"`;}
function tokenFor(account){return decryptWithEnv(account.access_token_encrypted,TOKEN_ENV,TOKEN_PREFIX);}
function parseVideoId(type,videoId){if(type==='movie'){const imdb=String(videoId||'').toLowerCase();return /^tt\d{5,12}$/.test(imdb)?{type:'movie',imdb}:null;}if(type!=='series')return null;const m=String(videoId||'').match(/^(tt\d{5,12}):(\d{1,3}):(\d{1,4})$/i);return m?{type:'series',imdb:m[1].toLowerCase(),season:Number(m[2]),episode:Number(m[3])}:null;}
function valueItems(payload){return Array.isArray(payload?.Items)?payload.Items:[];}

async function settings(){const r=await query('SELECT setting_value FROM platform_settings WHERE setting_key=$1',[SETTINGS_KEY]);const strategy=String(r.rows[0]?.setting_value?.strategy||'weighted_random');return{strategy:['priority','random','weighted_random'].includes(strategy)?strategy:'weighted_random'};}
async function saveSettings(input,actorUserId=null){const strategy=['priority','random','weighted_random'].includes(String(input?.strategy))?String(input.strategy):'weighted_random';await transaction(async client=>{await client.query(`INSERT INTO platform_settings(setting_key,setting_value,updated_by) VALUES($1,$2::jsonb,$3) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[SETTINGS_KEY,JSON.stringify({strategy}),actorUserId]);await client.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio_source_pool.settings','platform_setting',$2,$3::jsonb)`,[actorUserId,SETTINGS_KEY,JSON.stringify({strategy})]);});return{strategy};}
async function listSources(){const r=await query(`SELECT s.*,js.name managed_server_name,COALESCE(i.status,'never') index_status,COALESCE(i.item_count,0)::int item_count,i.last_completed_at,i.last_error,(SELECT COUNT(*)::int FROM stremio_source_accounts a WHERE a.source_id=s.id AND a.enabled=TRUE) account_count FROM stremio_sources s LEFT JOIN jellyfin_servers js ON js.id=s.managed_server_id LEFT JOIN stremio_source_index_state i ON i.source_id=s.id ORDER BY s.enabled DESC,s.priority,s.name`);return r.rows;}
async function source(id){const r=await query('SELECT * FROM stremio_sources WHERE id=$1',[id]);return r.rows[0]||null;}
async function accounts(sourceId){const r=await query(`SELECT id,source_id,label,jellyfin_user_id,jellyfin_username,enabled,weight,created_at,updated_at FROM stremio_source_accounts WHERE source_id=$1 ORDER BY enabled DESC,label`,[sourceId]);return r.rows;}
async function accountSecrets(sourceId){const r=await query('SELECT * FROM stremio_source_accounts WHERE source_id=$1 AND enabled=TRUE ORDER BY id',[sourceId]);return r.rows;}

async function saveSource(input,actorUserId=null,id=null){
  const type=String(input.sourceType||input.source_type||'managed')==='external'?'external':'managed',name=cleanText(input.name,120);if(!name)throw new Error('Source name is required.');let managedServerId=input.managedServerId||input.managed_server_id||null,baseUrl,publicUrl;
  if(type==='managed'){if(!managedServerId)throw new Error('Choose the managed Jellyfin server.');const r=await query('SELECT id,base_url,public_url,name FROM jellyfin_servers WHERE id=$1',[managedServerId]);if(!r.rowCount)throw new Error('Managed Jellyfin server not found.');baseUrl=httpUrl(r.rows[0].base_url,'Managed Jellyfin base URL');publicUrl=httpUrl(r.rows[0].public_url||r.rows[0].base_url,'Managed Jellyfin public URL');}
  else{managedServerId=null;baseUrl=httpUrl(input.baseUrl||input.base_url,'External Jellyfin base URL');publicUrl=httpUrl(input.publicUrl||input.public_url,'External Jellyfin public URL');await outbound.assertSafeIntegrationUrl(baseUrl,{purpose:'Stremio external Jellyfin source'});}
  const enabled=input.enabled===undefined?true:['1','true','on','yes'].includes(String(input.enabled).toLowerCase()),priority=int(input.priority,0,100000,100),weight=int(input.weight,1,10000,100);
  return transaction(async client=>{let row;if(id){const r=await client.query(`UPDATE stremio_sources SET name=$2,source_type=$3,managed_server_id=$4,base_url=$5,public_url=$6,enabled=$7,priority=$8,weight=$9,updated_at=NOW() WHERE id=$1 RETURNING *`,[id,name,type,managedServerId,baseUrl,publicUrl,enabled,priority,weight]);if(!r.rowCount)throw new Error('Stremio source not found.');row=r.rows[0];}else row=(await client.query(`INSERT INTO stremio_sources(name,source_type,managed_server_id,base_url,public_url,enabled,priority,weight) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[name,type,managedServerId,baseUrl,publicUrl,enabled,priority,weight])).rows[0];await client.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'stremio_source',$3,$4::jsonb)`,[actorUserId,id?'admin.stremio_source.update':'admin.stremio_source.create',row.id,JSON.stringify({name,type,managedServerId,enabled,priority,weight})]);return row;});
}
async function saveAccount(sourceId,input,actorUserId=null,id=null){const s=await source(sourceId);if(!s)throw new Error('Stremio source not found.');const label=cleanText(input.label,120),userId=cleanText(input.jellyfinUserId||input.jellyfin_user_id,100),username=cleanText(input.jellyfinUsername||input.jellyfin_username,120)||null,rawToken=String(input.accessToken||'').trim(),weight=int(input.weight,1,10000,100),enabled=input.enabled===undefined?true:['1','true','on','yes'].includes(String(input.enabled).toLowerCase());if(!label||!userId)throw new Error('Account label and Jellyfin user ID are required.');let encrypted=null;if(rawToken)encrypted=encryptWithEnv(rawToken,TOKEN_ENV,TOKEN_PREFIX);if(!id&&!encrypted)throw new Error('Access token is required for a new source account.');const row=await transaction(async client=>{let result;if(id)result=await client.query(`UPDATE stremio_source_accounts SET label=$3,jellyfin_user_id=$4,jellyfin_username=$5,access_token_encrypted=COALESCE($6,access_token_encrypted),enabled=$7,weight=$8,updated_at=NOW() WHERE id=$1 AND source_id=$2 RETURNING *`,[id,sourceId,label,userId,username,encrypted,enabled,weight]);else result=await client.query(`INSERT INTO stremio_source_accounts(source_id,label,jellyfin_user_id,jellyfin_username,access_token_encrypted,enabled,weight) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[sourceId,label,userId,username,encrypted,enabled,weight]);if(!result.rowCount)throw new Error('Source account not found.');await client.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,$2,'stremio_source_account',$3,$4::jsonb)`,[actorUserId,id?'admin.stremio_source_account.update':'admin.stremio_source_account.create',result.rows[0].id,JSON.stringify({sourceId,label,userId,enabled,weight,tokenRotated:Boolean(encrypted)})]);return result.rows[0];});await testAccount(row.id);return row;}
async function deleteSource(id,actorUserId=null){await transaction(async client=>{await client.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) SELECT $1,'admin.stremio_source.delete','stremio_source',id,jsonb_build_object('name',name) FROM stremio_sources WHERE id=$2`,[actorUserId,id]);await client.query('DELETE FROM stremio_sources WHERE id=$1',[id]);});}
async function deleteAccount(id,actorUserId=null){await transaction(async client=>{await client.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) SELECT $1,'admin.stremio_source_account.delete','stremio_source_account',id,jsonb_build_object('sourceId',source_id,'label',label) FROM stremio_source_accounts WHERE id=$2`,[actorUserId,id]);await client.query('DELETE FROM stremio_source_accounts WHERE id=$1',[id]);});}

async function request(s,a,endpoint,{method='GET',body=null,timeoutMs=15000,deviceId='captainfin-stremio-index'}={}){if(!String(endpoint).startsWith('/')||String(endpoint).startsWith('//'))throw new Error('Invalid Jellyfin source endpoint.');const base=new URL(s.base_url),url=new URL(endpoint,`${String(s.base_url).replace(/\/$/,'')}/`);if(url.origin!==base.origin)throw new Error('Jellyfin source request escaped configured origin.');const token=tokenFor(a),response=await outbound.safeFetch(url,{purpose:`Stremio source ${s.name}`,method,timeoutMs,headers:{Authorization:authHeader(token,deviceId),Accept:'application/json',...(body!==null?{'Content-Type':'application/json'}:{})},...(body!==null?{body:JSON.stringify(body)}:{})});const text=await response.text();let parsed={};if(text){try{parsed=JSON.parse(text);}catch{parsed=text;}}if(!response.ok){const e=new Error(`Stremio source returned HTTP ${response.status}`);e.status=response.status;throw e;}return parsed;}
async function testAccount(accountId){const r=await query(`SELECT a.*,s.name source_name,s.base_url,s.public_url FROM stremio_source_accounts a JOIN stremio_sources s ON s.id=a.source_id WHERE a.id=$1`,[accountId]);if(!r.rowCount)throw new Error('Source account not found.');const a=r.rows[0],s={id:a.source_id,name:a.source_name,base_url:a.base_url,public_url:a.public_url};const me=await request(s,a,`/Users/${encodeURIComponent(a.jellyfin_user_id)}`);if(!me||String(me.Id)!==String(a.jellyfin_user_id))throw new Error('The configured source token/user ID did not resolve to the expected Jellyfin user.');return{name:me.Name||a.jellyfin_username||a.label,userId:String(me.Id)};}

async function indexSource(sourceId,{pageSize=500}={}){const s=await source(sourceId);if(!s||!s.enabled)return{sourceId,processed:0,skipped:'source_disabled'};const accountPool=await accountSecrets(sourceId);if(!accountPool.length)throw new Error('No enabled source account configured.');const a=pickWeighted(accountPool),generation=crypto.randomUUID();await query(`INSERT INTO stremio_source_index_state(source_id,status,last_started_at,last_error,updated_at) VALUES($1,'running',NOW(),NULL,NOW()) ON CONFLICT(source_id) DO UPDATE SET status='running',last_started_at=NOW(),last_error=NULL,updated_at=NOW()`,[sourceId]);let start=0,total=0;try{while(true){const qs=new URLSearchParams({Recursive:'true',IncludeItemTypes:'Movie,Series',Fields:'ProviderIds,Path',HasImdbId:'true',UserId:String(a.jellyfin_user_id),StartIndex:String(start),Limit:String(pageSize)});const payload=await request(s,a,`/Items?${qs.toString()}`,{timeoutMs:30000});const items=valueItems(payload);if(!items.length)break;await transaction(async client=>{for(const item of items){const imdb=String(item.ProviderIds?.Imdb||item.ProviderIds?.IMDB||'').toLowerCase(),type=String(item.Type||'');if(!/^tt\d{5,12}$/.test(imdb)||!['Movie','Series'].includes(type)||!item.Id)continue;await client.query(`INSERT INTO stremio_source_media_index(source_id,imdb_id,item_id,item_type,name,production_year,path,scan_generation,updated_at,seen_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,NOW(),NOW()) ON CONFLICT(source_id,item_id) DO UPDATE SET imdb_id=EXCLUDED.imdb_id,item_type=EXCLUDED.item_type,name=EXCLUDED.name,production_year=EXCLUDED.production_year,path=EXCLUDED.path,scan_generation=EXCLUDED.scan_generation,updated_at=NOW(),seen_at=NOW()`,[sourceId,imdb,String(item.Id),type,item.Name||null,Number.isInteger(item.ProductionYear)?item.ProductionYear:null,item.Path||null,generation]);total++;}});start+=items.length;const declared=Number(payload.TotalRecordCount||0);if(items.length<pageSize||(declared&&start>=declared))break;}await transaction(async client=>{await client.query('DELETE FROM stremio_source_media_index WHERE source_id=$1 AND scan_generation<>$2',[sourceId,generation]);const c=await client.query('SELECT COUNT(*)::int n FROM stremio_source_media_index WHERE source_id=$1',[sourceId]);await client.query(`UPDATE stremio_source_index_state SET status='ready',last_completed_at=NOW(),item_count=$2,last_error=NULL,updated_at=NOW() WHERE source_id=$1`,[sourceId,Number(c.rows[0]?.n||0)]);});return{sourceId,processed:total,ok:true};}catch(error){await query(`UPDATE stremio_source_index_state SET status='failed',last_error=$2,updated_at=NOW() WHERE source_id=$1`,[sourceId,String(error.message||error).slice(0,2000)]).catch(()=>{});throw error;}}
async function indexAll(){const sources=await listSources();let processed=0,failed=0,total=0;for(const s of sources.filter(x=>x.enabled)){total++;try{const r=await indexSource(s.id);processed+=Number(r.processed||0);}catch(e){failed++;console.error(`Stremio source index failed for ${s.name}:`,e.message);}}return{total,processed,failed};}

function pickWeighted(rows){if(!rows.length)return null;const total=rows.reduce((n,r)=>n+Math.max(1,Number(r.weight||1)),0);let point=Math.random()*total;for(const row of rows){point-=Math.max(1,Number(row.weight||1));if(point<=0)return row;}return rows[rows.length-1];}
function orderedCandidates(rows,strategy){const unique=[];const seen=new Set();for(const row of rows){if(!seen.has(row.source_id)){seen.add(row.source_id);unique.push(row);}}if(strategy==='priority')return unique.sort((a,b)=>Number(a.priority)-Number(b.priority));if(strategy==='random')return unique.sort(()=>Math.random()-.5);const pending=[...unique],ordered=[];while(pending.length){const pick=pickWeighted(pending),i=pending.indexOf(pick);ordered.push(pick);pending.splice(i,1);}return ordered;}
async function lookup(imdb,type){const itemType=type==='series'?'Series':'Movie';const r=await query(`SELECT i.*,s.name source_name,s.base_url,s.public_url,s.priority,s.weight FROM stremio_source_media_index i JOIN stremio_sources s ON s.id=i.source_id LEFT JOIN stremio_source_index_state st ON st.source_id=s.id WHERE i.imdb_id=$1 AND i.item_type=$2 AND s.enabled=TRUE AND COALESCE(st.status,'never')='ready' ORDER BY s.priority,i.updated_at DESC`,[imdb,itemType]);return r.rows;}
async function resolveItem(s,a,indexed,args,deviceId){if(args.type==='movie')return{id:indexed.item_id,name:indexed.name,path:indexed.path,type:'Movie'};const qs=new URLSearchParams({UserId:String(a.jellyfin_user_id),Season:String(args.season),Fields:'Path,MediaSources,MediaStreams',StartIndex:'0',Limit:'500',EnableImages:'false'}),payload=await request(s,a,`/Shows/${encodeURIComponent(indexed.item_id)}/Episodes?${qs.toString()}`,{deviceId});const item=valueItems(payload).find(x=>Number(x.IndexNumber)===args.episode&&Number(x.ParentIndexNumber??args.season)===args.season);return item?{...item,id:String(item.Id),name:item.Name||indexed.name,path:item.Path||null,type:'Episode'}:null;}
function basename(v){const raw=String(v||'');if(!raw)return'';try{return decodeURIComponent(new URL(raw).pathname.split('/').filter(Boolean).pop()||'');}catch{return raw.split(/[\\/]/).pop()||'';}}
function filename(item,source){return basename(/\.strm(?:$|[?#])/i.test(String(item.path||''))?item.path:(source.Path||item.path||''))||`${item.name||'video'}.mkv`;}
async function admission(entitlement,videoId=null){const limit=Math.max(1,Number(entitlement.stream_limit||entitlement.streams||1));const r=await query(`SELECT COUNT(DISTINCT video_id)::int n,COALESCE(BOOL_OR(video_id=$2),FALSE) same_video FROM stremio_stream_requests WHERE customer_id=$1 AND requested_at>NOW()-INTERVAL '150 seconds'`,[entitlement.customer_id,String(videoId||'')]);const active=Number(r.rows[0]?.n||0),same=Boolean(r.rows[0]?.same_video);return{allowed:same||active<limit,active,limit,sameVideo:same};}
async function streamsFor(entitlement,type,videoId){const args=parseVideoId(type,videoId);if(!args)return[];const candidates=await lookup(args.imdb,args.type);if(!candidates.length)return null;const gate=await admission(entitlement,videoId);if(!gate.allowed)return[];const cfg=await settings(),ordered=orderedCandidates(candidates,cfg.strategy),deviceId=`cfst-${crypto.createHash('sha256').update(String(entitlement.id||entitlement.customer_id)).digest('hex').slice(0,20)}`;for(const indexed of ordered){const s={id:indexed.source_id,name:indexed.source_name,base_url:indexed.base_url,public_url:indexed.public_url};const accountPool=await accountSecrets(s.id);if(!accountPool.length)continue;const a=pickWeighted(accountPool);try{const item=await resolveItem(s,a,indexed,args,deviceId);if(!item)continue;const qs=new URLSearchParams({UserId:String(a.jellyfin_user_id)}),playback=await request(s,a,`/Items/${encodeURIComponent(item.id)}/PlaybackInfo?${qs.toString()}`,{deviceId}),sources=valueItems({Items:playback?.MediaSources}).filter(x=>x&&x.Id&&x.SupportsDirectPlay!==false);if(!sources.length)continue;const token=tokenFor(a),publicBase=String(s.public_url).replace(/\/$/,'');const streams=sources.map(src=>{const file=filename(item,src),display=foundation.streamDisplayFromFilename(file),url=new URL(`/Videos/${encodeURIComponent(item.id)}/stream`,`${publicBase}/`);url.searchParams.set('Static','true');url.searchParams.set('MediaSourceId',String(src.Id));const quality=display.metadata?.resolution||src.MediaStreams?.find(x=>x.Type==='Video')?.DisplayTitle||'Direct';return{name:`[CF ⚡ ${s.name}] ${quality}`,description:`${display.description||'Direct Jellyfin stream'}\nSource: ${s.name}`,url:url.toString(),behaviorHints:{notWebReady:true,proxyHeaders:{request:{Authorization:authHeader(token,deviceId)}},filename:file}};});await query(`INSERT INTO stremio_stream_requests(entitlement_id,customer_id,source_id,source_account_id,video_id,imdb_id,item_type,item_id,media_source_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)`,[entitlement.id,entitlement.customer_id,s.id,a.id,String(videoId),args.imdb,args.type,item.id,String(sources[0].Id),JSON.stringify({sourceName:s.name,bridgeAccount:a.label,deviceId,strategy:cfg.strategy,portalCustomerAttributed:true,upstreamVisibility:'bridge_account'})]);return streams;}catch(error){console.warn(`Stremio source ${s.name} failed for ${videoId}:`,error.message);}}
return null;}
async function recentRequests(limit=100){const r=await query(`SELECT sr.*,s.name source_name,a.label source_account_label,COALESCE(c.display_name,u.username,c.email,'Customer') customer_name FROM stremio_stream_requests sr JOIN stremio_sources s ON s.id=sr.source_id LEFT JOIN stremio_source_accounts a ON a.id=sr.source_account_id JOIN customers c ON c.id=sr.customer_id LEFT JOIN app_users u ON u.id=c.user_id ORDER BY sr.requested_at DESC LIMIT $1`,[Math.max(1,Math.min(500,Number(limit)||100))]);return r.rows;}

module.exports={TOKEN_ENV,TOKEN_PREFIX,SETTINGS_KEY,settings,saveSettings,listSources,source,accounts,saveSource,saveAccount,deleteSource,deleteAccount,testAccount,indexSource,indexAll,lookup,admission,streamsFor,recentRequests,request,authHeader};
