'use strict';

const http=require('http');
const https=require('https');
const net=require('net');
const {query,transaction}=require('../db');
const outbound=require('../security/outbound-url-policy');
const client=require('./source-client');
const sourceIndex=require('./source-index');

const KEY='stremio_source_pool_v1';
const DEFAULTS=Object.freeze({enabled:true,selectionMode:'priority'});
const MODES=new Set(['priority']);
function cleanText(v,max=200){return String(v||'').trim().slice(0,max);}
function bool(v){return v===true||['true','1','on','yes'].includes(String(v||'').toLowerCase());}
function normalizeSettings(){return{enabled:true,selectionMode:'priority'};}
async function settings(){return normalizeSettings();}
async function saveSettings(_input,actorUserId=null){const value=normalizeSettings();await query(`INSERT INTO platform_settings(setting_key,setting_value,updated_by) VALUES($1,$2::jsonb,$3) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[KEY,JSON.stringify(value),actorUserId]);return value;}
async function get(id){const r=await query('SELECT * FROM stremio_sources WHERE id=$1',[id]);return r.rows[0]||null;}
async function list(){return sourceIndex.states();}
async function refreshLibraries(sourceId){
  const source=await get(sourceId);if(!source)throw new Error('Stremio source not found.');const discovered=await client.discoverLibraries(source);
  await transaction(async db=>{await db.query('UPDATE stremio_source_libraries SET available=FALSE,updated_at=NOW() WHERE source_id=$1',[sourceId]);for(const library of discovered)await db.query(`INSERT INTO stremio_source_libraries(source_id,library_id,name,collection_type,selected,available) VALUES($1,$2,$3,$4,FALSE,TRUE) ON CONFLICT(source_id,library_id) DO UPDATE SET name=EXCLUDED.name,collection_type=EXCLUDED.collection_type,available=TRUE,updated_at=NOW()`,[sourceId,library.libraryId,library.name,library.collectionType]);await db.query(`UPDATE stremio_sources SET auth_state='connected',last_auth_check_at=NOW(),last_success_at=NOW(),last_error=NULL,updated_at=NOW() WHERE id=$1`,[sourceId]);});return discovered;
}
async function libraries(sourceId){const r=await query(`SELECT library_id,name,collection_type,selected,available FROM stremio_source_libraries WHERE source_id=$1 ORDER BY available DESC,name`,[sourceId]);return r.rows;}
async function connect(input,actorUserId=null){
  const name=cleanText(input.name,120);if(!name)throw new Error('Enter a source name.');if(!bool(input.authorizationConfirmed))throw new Error('Confirm that you are authorized to use this Jellyfin account for Stremio delivery.');
  const auth=await client.authenticate(input.baseUrl,input.username,input.password),encrypted=client.encryptToken(auth.accessToken);
  const created=await transaction(async db=>{const result=await db.query(`INSERT INTO stremio_sources(name,enabled,source_kind,base_url,public_url,jellyfin_user_id,jellyfin_username,access_token_encrypted,weight,priority,authorization_confirmed,auth_state,last_connected_at,last_auth_check_at) VALUES($1,TRUE,'external',$2,$3,$4,$5,$6,100,$7,TRUE,'connected',NOW(),NOW()) RETURNING id`,[name,auth.baseUrl,auth.publicUrl,auth.jellyfinUserId,auth.jellyfinUsername,encrypted,Math.max(1,Math.min(10000,Number.parseInt(input.priority,10)||100))]);await db.query(`INSERT INTO stremio_source_index_state(source_id,status,next_incremental_at,force_full) VALUES($1,'never',NOW(),TRUE) ON CONFLICT(source_id) DO NOTHING`,[result.rows[0].id]);await db.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.connect','stremio_source',$2,$3::jsonb)`,[actorUserId,result.rows[0].id,JSON.stringify({name,baseUrl:auth.baseUrl,jellyfinUsername:auth.jellyfinUsername,passwordStored:false,tokenStoredEncrypted:true})]);return result.rows[0];});
  try{await refreshLibraries(created.id);}catch(error){await query(`UPDATE stremio_sources SET auth_state=$2,last_error=$3,updated_at=NOW() WHERE id=$1`,[created.id,error?.code==='STREMIO_SOURCE_AUTH'?'reconnect_required':'error',String(error.message||error).slice(0,1000)]);throw error;}return created;
}
async function reconnect(sourceId,input,actorUserId=null){const source=await get(sourceId);if(!source)throw new Error('Stremio source not found.');const auth=await client.authenticate(source.base_url,input.username||source.jellyfin_username,input.password),encrypted=client.encryptToken(auth.accessToken);await transaction(async db=>{await db.query(`UPDATE stremio_sources SET base_url=$2,public_url=$3,jellyfin_user_id=$4,jellyfin_username=$5,access_token_encrypted=$6,auth_state='connected',last_connected_at=NOW(),last_auth_check_at=NOW(),last_error=NULL,updated_at=NOW() WHERE id=$1`,[sourceId,auth.baseUrl,auth.publicUrl,auth.jellyfinUserId,auth.jellyfinUsername,encrypted]);await db.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.reconnect','stremio_source',$2,$3::jsonb)`,[actorUserId,sourceId,JSON.stringify({jellyfinUsername:auth.jellyfinUsername,passwordStored:false,tokenRotated:true})]);});await refreshLibraries(sourceId);await sourceIndex.queue(sourceId,{full:true});return get(sourceId);}
async function setLibraries(sourceId,libraryIds,actorUserId=null){const requested=[...new Set((Array.isArray(libraryIds)?libraryIds:[libraryIds]).map(String).filter(Boolean))];if(!requested.length)throw new Error('Select at least one Jellyfin library to index.');await transaction(async db=>{const available=await db.query(`SELECT library_id FROM stremio_source_libraries WHERE source_id=$1 AND available=TRUE`,[sourceId]),allowed=new Set(available.rows.map(r=>String(r.library_id)));if(requested.some(id=>!allowed.has(id)))throw new Error('One or more selected Jellyfin libraries are no longer available.');await db.query('UPDATE stremio_source_libraries SET selected=FALSE,updated_at=NOW() WHERE source_id=$1',[sourceId]);await db.query('UPDATE stremio_source_libraries SET selected=TRUE,updated_at=NOW() WHERE source_id=$1 AND library_id=ANY($2::text[])',[sourceId,requested]);await db.query(`DELETE FROM stremio_source_media_index i WHERE i.source_id=$1 AND NOT EXISTS(SELECT 1 FROM stremio_source_libraries l WHERE l.source_id=i.source_id AND l.library_id=i.library_id AND l.selected=TRUE AND l.available=TRUE)`,[sourceId]);await db.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.libraries','stremio_source',$2,$3::jsonb)`,[actorUserId,sourceId,JSON.stringify({libraryIds:requested})]);});await sourceIndex.queue(sourceId,{full:true});return requested;}
async function setEnabled(id,enabled,actorUserId=null){const r=await query(`UPDATE stremio_sources SET enabled=$2,updated_at=NOW() WHERE id=$1 RETURNING name`,[id,Boolean(enabled)]);if(!r.rowCount)throw new Error('Stremio source not found.');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.toggle','stremio_source',$2,$3::jsonb)`,[actorUserId,id,JSON.stringify({enabled:Boolean(enabled)})]);}
async function remove(id,actorUserId=null){const mapped=await query('SELECT COUNT(*)::int n FROM plan_stremio_sources WHERE source_id=$1',[id]);if(Number(mapped.rows[0]?.n||0)>0)throw new Error('Remove this Stremio source from every plan before deleting it.');const r=await query('DELETE FROM stremio_sources WHERE id=$1 RETURNING name',[id]);if(!r.rowCount)throw new Error('Stremio source not found.');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.delete','stremio_source',$2,$3::jsonb)`,[actorUserId,id,JSON.stringify({name:r.rows[0].name})]);}
async function planSources(planId){const r=await query(`SELECT s.id,s.name,s.enabled,s.auth_state,s.jellyfin_username,COALESCE(i.status,'never') index_status,COALESCE(i.item_count,0)::int item_count,COUNT(l.library_id) FILTER(WHERE l.selected AND l.available)::int selected_libraries,COALESCE(ps.enabled,FALSE) selected,COALESCE(ps.priority,s.priority) plan_priority FROM stremio_sources s LEFT JOIN stremio_source_index_state i ON i.source_id=s.id LEFT JOIN stremio_source_libraries l ON l.source_id=s.id LEFT JOIN plan_stremio_sources ps ON ps.source_id=s.id AND ps.plan_id=$1 GROUP BY s.id,i.source_id,ps.plan_id,ps.source_id ORDER BY COALESCE(ps.priority,s.priority),s.name`,[planId]);return r.rows;}
async function savePlanSources(planId,selections,actorUserId=null){const rows=Array.isArray(selections)?selections:[];await transaction(async db=>{await db.query('DELETE FROM plan_stremio_sources WHERE plan_id=$1',[planId]);for(const row of rows){if(!row?.sourceId)continue;const priority=Math.max(1,Math.min(10000,Number(row.priority)||100));await db.query(`INSERT INTO plan_stremio_sources(plan_id,source_id,enabled,priority) VALUES($1,$2,TRUE,$3)`,[planId,row.sourceId,priority]);}await db.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.stremio_sources.update','plan',$2,$3::jsonb)`,[actorUserId,planId,JSON.stringify({sources:rows.map(r=>({sourceId:r.sourceId,priority:Number(r.priority)||100}))})]);});}
async function hasPlanMappings(entitlement){const r=await query(`SELECT EXISTS(SELECT 1 FROM subscriptions sub JOIN plan_stremio_sources ps ON ps.plan_id=sub.plan_id AND ps.enabled=TRUE WHERE sub.id=$1) yes`,[entitlement.subscription_id]);return r.rows[0]?.yes===true;}
async function enabledSourcesForEntitlement(entitlement){
  const explicit=await hasPlanMappings(entitlement),mapped=await query(`SELECT s.*,ps.priority plan_priority FROM subscriptions sub JOIN plan_stremio_sources ps ON ps.plan_id=sub.plan_id AND ps.enabled=TRUE JOIN stremio_sources s ON s.id=ps.source_id JOIN stremio_source_index_state i ON i.source_id=s.id WHERE sub.id=$1 AND s.enabled=TRUE AND s.auth_state='connected' AND i.status='ready' AND i.item_count>0 ORDER BY ps.priority,s.priority,s.name`,[entitlement.subscription_id]);
  if(explicit)return mapped.rows;
  const all=await query(`SELECT s.*,s.priority plan_priority FROM stremio_sources s JOIN stremio_source_index_state i ON i.source_id=s.id WHERE s.enabled=TRUE AND s.auth_state='connected' AND i.status='ready' AND i.item_count>0 ORDER BY s.priority,s.name`);return all.rows;
}
async function authorizedSourceForEntitlement(entitlement,sourceId){return (await enabledSourcesForEntitlement(entitlement)).find(s=>String(s.id)===String(sourceId))||null;}
async function resolve(source,type,videoId){let imdb;if(type==='movie')imdb=String(videoId||'').toLowerCase();else{const match=String(videoId||'').match(/^(tt\d{5,12}):(\d{1,3}):(\d{1,4})$/i);if(!match)return null;imdb=match[1].toLowerCase();}const root=await sourceIndex.lookup(source.id,imdb,type);if(!root)return null;if(type==='movie')return{Id:root.item_id,Name:root.name};const match=String(videoId).match(/^(tt\d{5,12}):(\d{1,3}):(\d{1,4})$/i),qs=new URLSearchParams({UserId:String(source.jellyfin_user_id),Season:match[2],Fields:'Path,MediaSources,MediaStreams',StartIndex:'0',Limit:'500',EnableImages:'false'}),payload=await client.request(source,`/Shows/${encodeURIComponent(root.item_id)}/Episodes?${qs}`),episode=(payload.Items||[]).find(x=>Number(x.ParentIndexNumber)===Number(match[2])&&Number(x.IndexNumber)===Number(match[3]));return episode||null;}
async function streamsFrom(source,type,videoId,{proxyBase,installToken}={}){const item=await resolve(source,type,videoId);if(!item)return[];const qs=new URLSearchParams({UserId:String(source.jellyfin_user_id)}),playback=await client.request(source,`/Items/${encodeURIComponent(item.Id)}/PlaybackInfo?${qs}`),mediaSources=(playback.MediaSources||[]).filter(x=>x?.Id&&x.SupportsDirectPlay!==false);return mediaSources.map(media=>{const height=Number(media.Height||media.MediaStreams?.find(s=>s.Type==='Video')?.Height||0),quality=height>=2000?'4K':height>=1000?'1080p':height>=700?'720p':'Direct',url=`${String(proxyBase||'').replace(/\/$/,'')}/stremio/${encodeURIComponent(installToken)}/source/${encodeURIComponent(source.id)}/${encodeURIComponent(item.Id)}/${encodeURIComponent(media.Id)}`;return{name:`[CAPTAiNFiN] ${quality}`,description:`${source.name} · Jellyfin source`,url,behaviorHints:{notWebReady:true,bingeGroup:`captainfin-source-${source.id}-${quality.toLowerCase()}`},_source:{id:source.id,name:source.name,itemId:String(item.Id)}};});}
async function streamsFor(entitlement,type,videoId,options={}){const rows=await enabledSourcesForEntitlement(entitlement);for(const source of rows){try{const streams=await streamsFrom(source,type,videoId,options);if(!streams.length)continue;const first=streams[0]._source;await query(`UPDATE stremio_sources SET last_success_at=NOW(),last_error=NULL,updated_at=NOW() WHERE id=$1`,[source.id]);await query(`INSERT INTO stremio_stream_attribution(entitlement_id,customer_id,source_id,source_name,video_type,video_id,item_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[entitlement.id,entitlement.customer_id,source.id,source.name,type,videoId,first.itemId,JSON.stringify({selectionMode:'plan_priority',upstreamIdentity:source.jellyfin_username||source.jellyfin_user_id})]);return streams.map(s=>{delete s._source;return s;});}catch(error){await query(`UPDATE stremio_sources SET auth_state=CASE WHEN $2 THEN 'reconnect_required' ELSE auth_state END,last_error=$3,updated_at=NOW() WHERE id=$1`,[source.id,error?.code==='STREMIO_SOURCE_AUTH',String(error.message||error).slice(0,1000)]).catch(()=>{});}}return[];}
async function openPlayback(source,itemId,mediaSourceId,rangeHeader=''){const base=new URL(client.cleanUrl(source.base_url)),url=new URL(`/Videos/${encodeURIComponent(itemId)}/stream`,`${base}/`);url.searchParams.set('Static','true');url.searchParams.set('MediaSourceId',String(mediaSourceId));const checked=await outbound.assertSafeIntegrationUrl(url,{purpose:`Stremio playback source ${source.name}`}),address=checked.addresses.find(v=>net.isIP(v)===4)||checked.addresses[0],family=net.isIP(address),transport=url.protocol==='https:'?https:http,headers={Authorization:client.jellyfinAuthHeader(client.sourceToken(source)),Accept:'*/*'};if(rangeHeader)headers.Range=String(rangeHeader).slice(0,200);return new Promise((resolve,reject)=>{const lookup=(_hostname,options,callback)=>{if(typeof options==='function'){callback=options;options={};}if(options?.all)return callback(null,[{address,family}]);return callback(null,address,family);};const request=transport.request(url,{method:'GET',headers,lookup},response=>resolve({request,response}));request.setTimeout(15000,()=>request.destroy(new Error('Jellyfin playback connection timed out.')));request.on('error',reject);request.end();});}
async function recentAttribution(limit=100){const r=await query(`SELECT a.*,COALESCE(c.display_name,u.username,c.email,'Customer') customer_name FROM stremio_stream_attribution a JOIN customers c ON c.id=a.customer_id LEFT JOIN app_users u ON u.id=c.user_id ORDER BY a.requested_at DESC LIMIT $1`,[Math.max(1,Math.min(500,Number(limit)||100))]);return r.rows;}

module.exports={KEY,DEFAULTS,MODES,normalizeSettings,settings,saveSettings,get,list,connect,reconnect,refreshLibraries,libraries,setLibraries,setEnabled,remove,planSources,savePlanSources,hasPlanMappings,enabledSourcesForEntitlement,authorizedSourceForEntitlement,streamsFor,openPlayback,recentAttribution};
