'use strict';

const {query,transaction}=require('../db');
const {encryptWithEnv,decryptWithEnv}=require('../security/purpose-crypto');
const outbound=require('../security/outbound-url-policy');
const entitlements=require('./entitlements');

const KEY='stremio_source_pool_v1';
const TOKEN_ENV='STREMIO_JELLYFIN_TOKEN_KEY';
const TOKEN_PREFIX='stremio-source-token';
const DEFAULTS=Object.freeze({enabled:false,selectionMode:'weighted_random'});
const MODES=new Set(['weighted_random','random','priority']);

function normalizeSettings(v={}){const mode=MODES.has(String(v.selectionMode))?String(v.selectionMode):DEFAULTS.selectionMode;return{enabled:v.enabled===true||['true','1','on','yes'].includes(String(v.enabled||'').toLowerCase()),selectionMode:mode};}
async function settings(){const r=await query('SELECT setting_value FROM platform_settings WHERE setting_key=$1',[KEY]);return normalizeSettings({...DEFAULTS,...(r.rows[0]?.setting_value||{})});}
async function saveSettings(input,actorUserId=null){const value=normalizeSettings(input);await transaction(async client=>{await client.query(`INSERT INTO platform_settings(setting_key,setting_value,updated_by) VALUES($1,$2::jsonb,$3) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[KEY,JSON.stringify(value),actorUserId]);await client.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source_pool.settings','platform_setting',$2,$3::jsonb)`,[actorUserId,KEY,JSON.stringify(value)]);});return value;}
function cleanUrl(v,label){let u;try{u=new URL(String(v||''));}catch{throw new Error(`${label} must be a valid URL.`);}if(!['http:','https:'].includes(u.protocol))throw new Error(`${label} must use HTTP or HTTPS.`);u.pathname=u.pathname.replace(/\/$/,'');u.search='';u.hash='';return u.toString().replace(/\/$/,'');}
function cleanText(v,max=200){return String(v||'').trim().slice(0,max);}
async function list(){const r=await query(`SELECT id,name,enabled,source_kind,server_id,base_url,public_url,jellyfin_user_id,jellyfin_username,weight,priority,authorization_confirmed,last_success_at,last_error,created_at,updated_at FROM stremio_sources ORDER BY enabled DESC,priority,name`);return r.rows;}
async function create(input,actorUserId=null){
  const name=cleanText(input.name,120),kind=String(input.sourceKind||'external')==='owned'?'owned':'external',baseUrl=cleanUrl(input.baseUrl,'Base URL'),publicUrl=cleanUrl(input.publicUrl||input.baseUrl,'Public URL'),userId=cleanText(input.jellyfinUserId,200),username=cleanText(input.jellyfinUsername,120),token=String(input.accessToken||'').trim();
  const authorizationConfirmed=kind==='owned'||input.authorizationConfirmed===true||['true','1','on','yes'].includes(String(input.authorizationConfirmed||'').toLowerCase());
  if(!name||!userId||token.length<8)throw new Error('Name, Jellyfin user ID and access token are required.');if(kind==='external'&&!authorizationConfirmed)throw new Error('Confirm that you are authorized to use this external Jellyfin server/account.');
  const weight=Math.max(1,Math.min(10000,Number.parseInt(input.weight,10)||100)),priority=Math.max(1,Math.min(10000,Number.parseInt(input.priority,10)||100)),encrypted=encryptWithEnv(token,TOKEN_ENV,TOKEN_PREFIX);
  const r=await query(`INSERT INTO stremio_sources(name,enabled,source_kind,server_id,base_url,public_url,jellyfin_user_id,jellyfin_username,access_token_encrypted,weight,priority,authorization_confirmed) VALUES($1,TRUE,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id`,[name,kind,input.serverId||null,baseUrl,publicUrl,userId,username||null,encrypted,weight,priority,authorizationConfirmed]);
  await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.create','stremio_source',$2,$3::jsonb)`,[actorUserId,r.rows[0].id,JSON.stringify({name,kind,baseUrl,publicUrl,userId,username:username||null,weight,priority,authorizationConfirmed,secretStoredEncrypted:true})]);return r.rows[0];
}
async function setEnabled(id,enabled,actorUserId=null){const r=await query(`UPDATE stremio_sources SET enabled=$2,updated_at=NOW() WHERE id=$1 RETURNING name`,[id,Boolean(enabled)]);if(!r.rowCount)throw new Error('Stremio source not found.');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.toggle','stremio_source',$2,$3::jsonb)`,[actorUserId,id,JSON.stringify({enabled:Boolean(enabled)})]);}
async function remove(id,actorUserId=null){const r=await query('DELETE FROM stremio_sources WHERE id=$1 RETURNING name',[id]);if(!r.rowCount)throw new Error('Stremio source not found.');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.delete','stremio_source',$2,$3::jsonb)`,[actorUserId,id,JSON.stringify({name:r.rows[0].name})]);}
function token(source){return decryptWithEnv(source.access_token_encrypted,TOKEN_ENV,TOKEN_PREFIX);}
async function request(source,endpoint){if(typeof endpoint!=='string'||!endpoint.startsWith('/')||endpoint.startsWith('//'))throw new Error('Invalid Jellyfin source endpoint.');const base=new URL(source.base_url),url=new URL(endpoint,`${base.toString().replace(/\/$/,'')}/`);if(url.origin!==base.origin)throw new Error('Jellyfin source endpoint escaped configured origin.');const response=await outbound.safeFetch(url,{purpose:`Stremio source pool request on ${source.name}`,timeoutMs:12000,headers:{Authorization:entitlements.jellyfinAuthHeader(token(source)),Accept:'application/json'}});const text=await response.text();let body={};try{body=text?JSON.parse(text):{};}catch{body={};}if(!response.ok)throw new Error(`Jellyfin source ${source.name} returned HTTP ${response.status}`);return body;}
function order(rows,mode){const copy=[...rows];if(mode==='priority')return copy.sort((a,b)=>Number(a.priority)-Number(b.priority));if(mode==='random')return copy.sort(()=>Math.random()-.5);const pool=[];for(const row of copy){const weight=Math.max(1,Number(row.weight||1));pool.push({row,key:-Math.log(Math.max(Number.MIN_VALUE,Math.random()))/weight});}return pool.sort((a,b)=>a.key-b.key).map(x=>x.row);}
async function enabledSources(){const r=await query(`SELECT * FROM stremio_sources WHERE enabled=TRUE ORDER BY priority,name`);return r.rows;}
async function resolve(source,type,videoId){
  let imdb;if(type==='movie')imdb=String(videoId||'').toLowerCase();else{const m=String(videoId||'').match(/^(tt\d{5,12}):(\d{1,3}):(\d{1,4})$/i);if(!m)return null;imdb=m[1].toLowerCase();}
  if(!/^tt\d{5,12}$/.test(imdb))return null;
  const qs=new URLSearchParams({UserId:String(source.jellyfin_user_id),Recursive:'true',AnyProviderIdEquals:`imdb.${imdb}`,Fields:'Path,MediaSources,MediaStreams,ProviderIds',Limit:'25'});qs.set('IncludeItemTypes',type==='movie'?'Movie':'Series');
  const found=await request(source,`/Items?${qs}`),items=Array.isArray(found.Items)?found.Items:[],root=items.find(x=>String(x.ProviderIds?.Imdb||'').toLowerCase()===imdb)||items[0];if(!root)return null;
  if(type==='movie')return root;
  const m=String(videoId).match(/^(tt\d{5,12}):(\d{1,3}):(\d{1,4})$/i),eps=new URLSearchParams({UserId:String(source.jellyfin_user_id),Season:m[2],Fields:'Path,MediaSources,MediaStreams',StartIndex:'0',Limit:'500',EnableImages:'false'}),payload=await request(source,`/Shows/${encodeURIComponent(root.Id)}/Episodes?${eps}`),episode=(payload.Items||[]).find(x=>Number(x.ParentIndexNumber)===Number(m[2])&&Number(x.IndexNumber)===Number(m[3]));return episode||null;
}
async function streamsFrom(source,type,videoId){const item=await resolve(source,type,videoId);if(!item)return[];const qs=new URLSearchParams({UserId:String(source.jellyfin_user_id)}),playback=await request(source,`/Items/${encodeURIComponent(item.Id)}/PlaybackInfo?${qs}`),sources=(playback.MediaSources||[]).filter(x=>x?.Id&&x.SupportsDirectPlay!==false);const publicBase=source.public_url.replace(/\/$/,'');return sources.map(media=>{const url=new URL(`/Videos/${encodeURIComponent(item.Id)}/stream`,`${publicBase}/`);url.searchParams.set('Static','true');url.searchParams.set('MediaSourceId',String(media.Id));const height=Number(media.Height||media.MediaStreams?.find(s=>s.Type==='Video')?.Height||0),quality=height>=2000?'4K':height>=1000?'1080p':height>=700?'720p':'Direct';return{name:`[CF Pool] ${quality}`,description:`${source.name} · authorized Jellyfin bridge`,url:url.toString(),behaviorHints:{notWebReady:true,bingeGroup:`captainfin-pool-${quality.toLowerCase()}`,proxyHeaders:{request:{Authorization:entitlements.jellyfinAuthHeader(token(source))}}},_source:{id:source.id,name:source.name,itemId:String(item.Id)}};});}
async function streamsFor(entitlement,type,videoId){const cfg=await settings();if(!cfg.enabled)return[];const rows=order(await enabledSources(),cfg.selectionMode);for(const source of rows){try{const streams=await streamsFrom(source,type,videoId);if(!streams.length)continue;const first=streams[0]._source;await query(`UPDATE stremio_sources SET last_success_at=NOW(),last_error=NULL,updated_at=NOW() WHERE id=$1`,[source.id]);await query(`INSERT INTO stremio_stream_attribution(entitlement_id,customer_id,source_id,source_name,video_type,video_id,item_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[entitlement.id,entitlement.customer_id,source.id,source.name,type,videoId,first.itemId,JSON.stringify({selectionMode:cfg.selectionMode,upstreamIdentity:source.jellyfin_username||source.jellyfin_user_id})]);return streams.map(s=>{delete s._source;return s;});}catch(error){await query(`UPDATE stremio_sources SET last_error=$2,updated_at=NOW() WHERE id=$1`,[source.id,String(error.message||error).slice(0,1000)]).catch(()=>{});}}
  return[];}
async function recentAttribution(limit=100){const r=await query(`SELECT a.*,COALESCE(c.display_name,u.username,c.email,'Customer') customer_name FROM stremio_stream_attribution a JOIN customers c ON c.id=a.customer_id LEFT JOIN app_users u ON u.id=c.user_id ORDER BY a.requested_at DESC LIMIT $1`,[Math.max(1,Math.min(500,Number(limit)||100))]);return r.rows;}

module.exports={KEY,DEFAULTS,MODES,normalizeSettings,settings,saveSettings,list,create,setEnabled,remove,enabledSources,streamsFor,recentAttribution};
