from pathlib import Path

# Fix settings terminology safely and add a clear settings directory.
p=Path('src/platform/admin-original-settings.js'); s=p.read_text()
s=s.replace('allowPrivateConnected services','allowPrivateIntegrations')
s=s.replace("function generalSection(req,data){const pf=data.platform,o=data.operations;return `", "function generalSection(req,data){const pf=data.platform,o=data.operations;return `<section class=\"settings-card settings-directory\"><div class=\"card-header\"><div><h3>Where settings live</h3><div class=\"settings-hint\">Start here when you are unsure. Each card opens the one canonical place that owns that behaviour.</div></div></div><div class=\"card-body\"><div class=\"quick-actions settingsDirectoryGrid\"><a class=\"quick-action\" href=\"/admin/settings?section=general\"><strong>General & branding</strong><span>Site name, storefront, public URL, locale and support links</span></a><a class=\"quick-action\" href=\"/admin/plans\"><strong>Plans & customer access</strong><span>Prices, homepage features, Jellyfin policy, libraries, capacity and storefront order</span></a><a class=\"quick-action\" href=\"/admin/servers\"><strong>Jellyfin servers</strong><span>Servers, health, capacity, placement and controlled customer moves</span></a><a class=\"quick-action\" href=\"/admin/servers/stremio\"><strong>Stremio</strong><span>Jellyfin sources, libraries, indexing and runtime readiness</span></a><a class=\"quick-action\" href=\"/admin/notifications/preferences\"><strong>Communications</strong><span>Email, Telegram, Discord, WhatsApp and event permissions</span></a><a class=\"quick-action\" href=\"/admin/settings?section=security\"><strong>Customer onboarding & security</strong><span>Registration, email verification, sessions, Turnstile and network trust</span></a><a class=\"quick-action\" href=\"/admin/activity/inactivity-policy\"><strong>Automation & retention</strong><span>Free-plan usage rules and dormant Jellyfin cleanup</span></a><a class=\"quick-action\" href=\"/admin/commerce\"><strong>Commerce</strong><span>Billing activity, incidents and affiliate service credits</span></a></div></div></section>")
p.write_text(s)

# Fully retire reseller ordering; make the behaviour self-explanatory.
p=Path('src/platform/admin-plan-order.js'); s=p.read_text()
start=s.index('async function orderData()')
end=s.index('\nfunction status(', start)
s=s[:start]+"async function orderData(){const plans=await query(`SELECT id,code,name,service_type,is_addon,is_free_tier,active,visible,sort_order,price_minor,currency FROM plans WHERE archived_at IS NULL AND audience IN('direct','both') ORDER BY sort_order,name,id`),free=plans.rows.find(p=>p.is_free_tier)||null,standard=plans.rows.filter(p=>!p.is_free_tier&&groupFor(p)==='standard'),stremio=plans.rows.filter(p=>!p.is_free_tier&&groupFor(p)==='stremio');return{free,standard,stremio}}"+s[end:]
s=s.replace("function item(row,{reseller=false}={}){return `<li class=\"orderItem\" draggable=\"true\" data-order-item data-id=\"${esc(row.id)}\"><span class=\"dragHandle\" aria-hidden=\"true\">⋮⋮</span><div class=\"orderMain\"><strong>${esc(row.name)}</strong><div class=\"subText\">${esc(row.code)} · ${reseller?`${esc(row.seat_limit)} managed users · ${esc(price(row.monthly_price_minor,row.currency))}/mo`:`${esc(String(row.service_type||'jellyfin'))} · ${esc(price(row.price_minor,row.currency))}`}</div></div>${status(row)}<div class=\"orderButtons\"><button class=\"button secondary btn-sm\" type=\"button\" data-move=\"up\" aria-label=\"Move ${esc(row.name)} up\">↑</button><button class=\"button secondary btn-sm\" type=\"button\" data-move=\"down\" aria-label=\"Move ${esc(row.name)} down\">↓</button></div></li>`}", "function item(row){return `<li class=\"orderItem\" draggable=\"true\" data-order-item data-id=\"${esc(row.id)}\"><span class=\"dragHandle\" aria-hidden=\"true\">⋮⋮</span><div class=\"orderMain\"><strong>${esc(row.name)}</strong><div class=\"subText\">${esc(row.code)} · ${esc(String(row.service_type||'jellyfin'))} · ${esc(price(row.price_minor,row.currency))}</div></div>${status(row)}<div class=\"orderButtons\"><button class=\"button secondary btn-sm\" type=\"button\" data-move=\"up\" aria-label=\"Move ${esc(row.name)} up\">↑</button><button class=\"button secondary btn-sm\" type=\"button\" data-move=\"down\" aria-label=\"Move ${esc(row.name)} down\">↓</button></div></li>`}")
s=s.replace("function list(name,title,description,rows,{reseller=false}={}){return `<section class=\"section\"><div class=\"sectionHead\"><div><h2>${esc(title)}</h2><div class=\"muted\">${esc(description)}</div></div></div>${rows.length?`<ol class=\"orderList\" data-order-list=\"${esc(name)}\">${rows.map(row=>item(row,{reseller})).join('')}</ol>`:'<div class=\"empty\">No products in this storefront section.</div>'}<input type=\"hidden\" name=\"${esc(name)}Order\" data-order-output=\"${esc(name)}\"></section>`}", "function list(name,title,description,rows){return `<section class=\"section\"><div class=\"sectionHead\"><div><h2>${esc(title)}</h2><div class=\"muted\">${esc(description)}</div></div></div>${rows.length?`<ol class=\"orderList\" data-order-list=\"${esc(name)}\">${rows.map(item).join('')}</ol>`:'<div class=\"empty\">No products in this storefront section.</div>'}<input type=\"hidden\" name=\"${esc(name)}Order\" data-order-output=\"${esc(name)}\"></section>`}")
s=s.replace('Free Access is permanently pinned above the plan cards. Drag the other products into the order customers should see inside each homepage section.','Free Access stays pinned above the plan cards. Drag the other plans into the exact order customers should see on the homepage.')
s=s.replace("${list('stremio','Stremio plans & add-ons','Order within the Stremio section.',d.stremio)}${list('reseller','Reseller plans','Order within the reseller section of the homepage.',d.resellers,{reseller:true})}", "${list('stremio','Stremio plans & add-ons','Order within the Stremio section.',d.stremio)}")
start=s.index('async function save(req)')
end=s.index('\nfunction createAdminPlanOrderRouter',start)
s=s[:start]+"async function save(req){const d=await orderData(),groups=[['standard',d.standard],['stremio',d.stremio]],submitted={};for(const[name,rows]of groups){const ids=parseIds(req.body[`${name}Order`]),expected=rows.map(r=>String(r.id));if(!sameSet(ids,expected))throw new Error(`The ${name} storefront order changed while you were editing. Reload and try again.`);submitted[name]=ids}await transaction(async client=>{let order=100;for(const id of submitted.standard){await client.query('UPDATE plans SET sort_order=$2,updated_at=NOW() WHERE id=$1',[id,order]);order+=100}order=100;for(const id of submitted.stremio){await client.query('UPDATE plans SET sort_order=$2,updated_at=NOW() WHERE id=$1',[id,order]);order+=100}if(d.free)await client.query('UPDATE plans SET sort_order=0,updated_at=NOW() WHERE id=$1',[d.free.id]);await client.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,metadata) VALUES($1,'admin.storefront.order.update','catalogue',$2::jsonb)`,[req.session.authUserId,JSON.stringify(submitted)])})}"+s[end:]
p.write_text(s)

# Customer 360: remove retired reseller link/copy and make overview forms use the actual CSRF token.
p=Path('src/platform/admin-customer-360.js'); s=p.read_text()
s=s.replace("const resellerLink=detail.customer.reseller_id?`<a class=\"button secondary\" href=\"/admin/reseller-management/${encodeURIComponent(detail.customer.reseller_id)}\">Reseller 360 · ${esc(detail.customer.reseller_username||'owner')}</a>`:'';", "const resellerLink='';")
p.write_text(s)
p=Path('src/platform/customer-360-view-v2.js'); s=p.read_text()
s=s.replace('function overview(d){const c=d.customer,s=current(d);', 'function overview(d,token){const c=d.customer,s=current(d);')
s=s.replace("${kv('Source',c.registration_source)}${kv('Reseller',c.reseller_username||'Direct')}", "${kv('Source',c.registration_source)}")
s=s.replace("csrfHidden(d.csrfToken||'')", 'csrfHidden(token)')
s=s.replace("<span>${esc(c.reseller_username?'Reseller: '+c.reseller_username:'Direct customer')}</span><span>·</span>", "<span>Customer account</span><span>·</span>")
p.write_text(s)

# Stremio source creation is now two-stage: authenticated source persists even if discovery fails.
p=Path('src/stremio/source-pool.js'); s=p.read_text()
old="try{await refreshLibraries(created.id);}catch(error){await query(`UPDATE stremio_sources SET auth_state=$2,last_error=$3,updated_at=NOW() WHERE id=$1`,[created.id,error?.code==='STREMIO_SOURCE_AUTH'?'reconnect_required':'error',String(error.message||error).slice(0,1000)]);throw error;}return created;"
new="try{await refreshLibraries(created.id);return{...created,discoveryWarning:null};}catch(error){const warning=String(error?.message||error).slice(0,1000);await query(`UPDATE stremio_sources SET auth_state=$2,last_error=$3,updated_at=NOW() WHERE id=$1`,[created.id,error?.code==='STREMIO_SOURCE_AUTH'?'reconnect_required':'error',warning]);await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.stremio.source.discovery_failed','stremio_source',$2,$3::jsonb)`,[actorUserId,created.id,JSON.stringify({error:warning,sourcePersisted:true})]).catch(()=>{});return{...created,discoveryWarning:warning};}"
if old not in s: raise SystemExit('stremio connect pattern missing')
s=s.replace(old,new,1); p.write_text(s)

p=Path('src/platform/admin-stremio-sources.js'); s=p.read_text()
old="const created=await sourcePool.connect(req.body,req.session.authUserId);return res.redirect(`/admin/servers/stremio/${encodeURIComponent(created.id)}?message=${encodeURIComponent('Connected. Choose the libraries to index.')}`);"
new="const created=await sourcePool.connect(req.body,req.session.authUserId);if(created.discoveryWarning)return res.redirect(`/admin/servers/stremio/${encodeURIComponent(created.id)}?error=${encodeURIComponent('Jellyfin sign-in succeeded and the source was saved, but library discovery needs attention: '+created.discoveryWarning)}`);return res.redirect(`/admin/servers/stremio/${encodeURIComponent(created.id)}?message=${encodeURIComponent('Jellyfin connected. Step 2: choose the libraries to index.')}`);"
if old not in s: raise SystemExit('stremio admin route pattern missing')
s=s.replace(old,new,1)
s=s.replace('Connect & discover libraries will sign in and take you straight to library selection.','Step 1 signs in and saves the source. Step 2 discovers libraries. If discovery fails, the source stays saved so you can diagnose or retry instead of starting over.')
s=s.replace('Connect & discover libraries</button>','Connect Jellyfin source</button>')
p.write_text(s)

# Strengthen smoke for the follow-up fixes.
p=Path('scripts/admin-coherence-user-overrides-smoke.js'); s=p.read_text()
s=s.replace("const storefront=read('src/platform/storefront.js')", "const storefront=read('src/platform/storefront.js'),order=read('src/platform/admin-plan-order.js'),settings=read('src/platform/admin-original-settings.js'),stremioPool=read('src/stremio/source-pool.js'),stremioAdmin=read('src/platform/admin-stremio-sources.js')")
s=s.replace("console.log('admin coherence user overrides smoke: ok');", "assert(!/reseller_tiers/.test(order)&&!/Reseller plans/.test(order),'retired reseller ordering remains');assert(/Where settings live/.test(settings)&&/Plans & customer access/.test(settings),'settings directory missing');assert(!/allowPrivateConnected/.test(settings),'settings identifier was corrupted');assert(/discoveryWarning/.test(stremioPool)&&/source was saved/.test(stremioAdmin),'Stremio source resilience missing');console.log('admin coherence user overrides smoke: ok');")
p.write_text(s)
