'use strict';

require('dotenv').config();
const fs=require('fs');
const path=require('path');
const {spawn}=require('child_process');
const crypto=require('crypto');
const {query,getPool}=require('../src/db');

const INSTANCE_ID=String(process.env.HOSTNAME||`backup-${crypto.randomUUID()}`).slice(0,200);
const POLL_MS=Math.max(30000,Math.min(15*60*1000,Number(process.env.BACKUP_WORKER_POLL_MS||60000)));
let stopping=false,sleepTimer=null,sleepResolve=null,running=null;
function sleep(ms){return new Promise(resolve=>{sleepResolve=resolve;sleepTimer=setTimeout(()=>{sleepTimer=null;sleepResolve=null;resolve();},ms);});}
function runScript(script,args=[]){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[path.join(__dirname,script),...args],{stdio:'inherit',env:{...process.env,BACKUP_DIR:process.env.BACKUP_DIR||'/backups'}});child.once('error',reject);child.once('close',code=>code===0?resolve():reject(new Error(`${script} exited ${code}`)));});}
async function policy(){const r=await query(`SELECT setting_value FROM platform_settings WHERE setting_key='backup_policy_v1'`),v=r.rows[0]?.setting_value||{};return{enabled:v.enabled!==false,intervalHours:Math.max(1,Math.min(24*30,Number(v.intervalHours)||24)),retentionDays:Math.max(1,Math.min(3650,Number(v.retentionDays)||30)),minimumCopies:Math.max(1,Math.min(365,Number(v.minimumCopies)||7)),verifyAfterBackup:v.verifyAfterBackup!==false};}
async function heartbeat(extra={}){await query(`INSERT INTO backup_worker_state(worker_key,instance_id,last_heartbeat_at,next_run_at,updated_at) VALUES('database_backup',$1,NOW(),$2,NOW()) ON CONFLICT(worker_key) DO UPDATE SET instance_id=EXCLUDED.instance_id,last_heartbeat_at=NOW(),next_run_at=COALESCE($2,backup_worker_state.next_run_at),updated_at=NOW()`,[INSTANCE_ID,extra.nextRunAt||null]);}
async function due(cfg){const r=await query(`SELECT last_success_at,next_run_at FROM backup_worker_state WHERE worker_key='database_backup'`),row=r.rows[0]||{};if(row.next_run_at)return new Date(row.next_run_at)<=new Date();if(!row.last_success_at)return true;return Date.now()-new Date(row.last_success_at).getTime()>=cfg.intervalHours*3600000;}
async function runBackup(cfg){await query(`INSERT INTO backup_worker_state(worker_key,instance_id,last_heartbeat_at,last_attempt_at,updated_at) VALUES('database_backup',$1,NOW(),NOW(),NOW()) ON CONFLICT(worker_key) DO UPDATE SET instance_id=EXCLUDED.instance_id,last_heartbeat_at=NOW(),last_attempt_at=NOW(),last_error=NULL,updated_at=NOW()`,[INSTANCE_ID]);try{await runScript('backup-db.js');if(cfg.verifyAfterBackup)await runScript('verify-backup.js');const next=new Date(Date.now()+cfg.intervalHours*3600000);await query(`UPDATE backup_worker_state SET last_success_at=NOW(),last_error=NULL,next_run_at=$1,last_heartbeat_at=NOW(),updated_at=NOW() WHERE worker_key='database_backup'`,[next]);return next;}catch(error){const next=new Date(Date.now()+Math.min(cfg.intervalHours,1)*3600000);await query(`UPDATE backup_worker_state SET last_error=$1,next_run_at=$2,last_heartbeat_at=NOW(),updated_at=NOW() WHERE worker_key='database_backup'`,[String(error.message||error).slice(0,2000),next]).catch(()=>{});throw error;}}
async function applyRetention(cfg){const dir=path.resolve(process.env.BACKUP_DIR||'/backups');if(!fs.existsSync(dir))return{deleted:0};const files=fs.readdirSync(dir).filter(name=>/^captainfin-.*\.pgdump\.enc$/.test(name)).map(name=>{const file=path.join(dir,name),stat=fs.statSync(file);return{name,file,mtime:stat.mtimeMs};}).sort((a,b)=>b.mtime-a.mtime);const cutoff=Date.now()-cfg.retentionDays*86400000,protectedNames=new Set(files.slice(0,cfg.minimumCopies).map(x=>x.name)),victims=files.filter(x=>x.mtime<cutoff&&!protectedNames.has(x.name));let deleted=0;for(const victim of victims){try{fs.unlinkSync(victim.file);deleted++;await query(`UPDATE backup_runs SET status='deleted',metadata=metadata||$2::jsonb WHERE file_name=$1 AND status='succeeded'`,[victim.name,JSON.stringify({deletedByRetentionAt:new Date().toISOString()})]);}catch(error){console.warn(`Backup retention could not delete ${victim.name}:`,error.message);}}return{deleted};}
async function loop(){await heartbeat();console.log(`CAPTaINFiN backup worker ready; instance=${INSTANCE_ID}`);while(!stopping){try{const cfg=await policy();await heartbeat();if(cfg.enabled&&await due(cfg)){running=runBackup(cfg);try{const next=await running;console.log(`Backup and verification completed; next ${next.toISOString()}`);}finally{running=null;}const retention=await applyRetention(cfg);if(retention.deleted)console.log(`Backup retention deleted ${retention.deleted} old file(s).`);}else if(!cfg.enabled){await query(`UPDATE backup_worker_state SET next_run_at=NULL,last_heartbeat_at=NOW(),updated_at=NOW() WHERE worker_key='database_backup'`);}}catch(error){console.error('Backup worker iteration failed:',error.message);}if(!stopping)await sleep(POLL_MS);}if(running)await Promise.allSettled([running]);try{await getPool().end();}catch(_){}}
function shutdown(signal){if(stopping)return;stopping=true;console.log(`Backup worker draining (${signal})`);if(sleepTimer){clearTimeout(sleepTimer);sleepTimer=null;const resolve=sleepResolve;sleepResolve=null;resolve?.();}}
process.on('SIGTERM',()=>shutdown('SIGTERM'));process.on('SIGINT',()=>shutdown('SIGINT'));
loop().catch(error=>{console.error('Backup worker fatal error:',error);process.exit(1);});
