'use strict';

module.exports = {
  "suites": {
    "check:fast:foundation": [
      "npm run syntax",
      "node scripts/customer-access-state-smoke.js",
      "node scripts/unpaid-access-activation-smoke.js",
      "node scripts/access-repair-behavior-smoke.js",
      "node scripts/access-repair-ownership-smoke.js",
      "node scripts/access-integrity-operator-smoke.js",
      "node scripts/lifecycle-audit-regressions-smoke.js",
      "node scripts/per-plan-revoke-stremio-refund-smoke.js",
      "node scripts/free-claim-provisioning-repair-smoke.js",
      "node scripts/provisioning-recovery-invariants-smoke.js",
      "node scripts/password-minimum-policy-smoke.js",
      "node scripts/customer-deletion-targets-smoke.js",
      "npm run check:boundaries",
      "npm run check:canonical-ownership",
      "node scripts/platform-business-sql-boundary-smoke.js",
      "node scripts/ci/roadmap-contracts.test.js",
      "npm run check:no-retired-product",
      "npm run check:v2-contracts",
      "node scripts/captainfin-brand-audit.js",
      "node scripts/security-operator-clarity-smoke.js",
      "node scripts/security-boundary-hardening-smoke.js",
      "node scripts/customer-security-domain-smoke.js",
      "node scripts/admin-mutation-rate-limit-smoke.js",
      "node scripts/totp-smoke.js",
      "node scripts/runtime-db-isolation-smoke.js"
    ],
    "check:fast:operations": [
      "node scripts/production-image-content-smoke.js",
      "node scripts/ui-helper-inventory.js",
      "node scripts/repository-merge-gates-smoke.js",
      "node scripts/merge-safety-contract-smoke.js",
      "node scripts/zero-downtime-portal-deploy-smoke.js",
      "node scripts/production-acceptance-audit-smoke.js",
      "node scripts/check-manifest-smoke.js",
      "node scripts/required-merge-gates-smoke.js",
      "node scripts/automation-job-registry-smoke.js",
      "node scripts/automation-registry-ownership-smoke.js",
      "node scripts/automation-job-definition-smoke.js",
      "node scripts/automation-release-hardening-smoke.js",
      "node scripts/revenue-integrity-auto-repair-smoke.js",
      "node scripts/critical-runtime-continuity-smoke.js",
      "node scripts/deployment-tooling-smoke.js",
      "node scripts/runtime-recovery-behavior-smoke.js",
      "node scripts/deployment-drain-rollback-smoke.js",
      "node scripts/customer-credential-defense-smoke.js",
      "node scripts/installer-smoke.js",
      "node scripts/admin-version-update-smoke.js",
      "node scripts/first-run-installer-smoke.js",
      "node scripts/backup-healthcheck-smoke.js",
      "node scripts/backup-recovery-readiness-smoke.js",
      "node scripts/offsite-backup-smoke.js",
      "node scripts/system-diagnostics-support-smoke.js",
      "node scripts/worker-diagnostics-hardening-smoke.js",
      "node scripts/operational-robustness-smoke.js",
      "node scripts/outbound-policy-smoke.js",
      "node scripts/reschedule-timer-smoke.js",
      "node scripts/policy-engine-smoke.js"
    ],
    "check:fast:customer-access": [
      "node scripts/jellyfin-registry-smoke.js",
      "node scripts/jellyfin-poll-dedupe-smoke.js",
      "node scripts/lane-entitlements-onboarding-impersonation-smoke.js",
      "node scripts/customer-my-access-inactivity-smoke.js",
      "node scripts/customer-activity-scope-smoke.js",
      "node scripts/customer-filters-smoke.js",
      "node scripts/customer-list-identity-smoke.js",
      "node scripts/customer-360-query-smoke.js",
      "node scripts/customer-360-admin-management-smoke.js",
      "node scripts/customer-360-extracted-actions-smoke.js",
      "node scripts/customer-360-extracted-mutations-smoke.js",
      "node scripts/admin-jellyfin-reenable-smoke.js",
      "node scripts/admin-force-access-boundary-smoke.js",
      "node scripts/admin-customer-operator-boundary-smoke.js",
      "node scripts/admin-direct-lifecycle-boundary-smoke.js",
      "node scripts/media-device-reset-serialization-smoke.js",
      "node scripts/customer-360-access-tab-splice-smoke.js",
      "node scripts/customer-household-overrides-smoke.js",
      "node scripts/customer-billing-tab-smoke.js",
      "node scripts/admin-manual-entitlement-smoke.js",
      "node scripts/end-current-jellyfin-plan-smoke.js",
      "node scripts/server-form-validation-smoke.js",
      "node scripts/server-status-timestamp-smoke.js",
      "node scripts/server-placement-smoke.js",
      "node scripts/server-control-consolidation-smoke.js",
      "node scripts/invitations-smoke.js",
      "node scripts/provisioning-control-smoke.js",
      "node scripts/reconciliation-desired-state-smoke.js",
      "node scripts/provider-recovery-safety-smoke.js",
      "node scripts/provider-lifecycle-adapters-smoke.js",
      "node scripts/provider-contract-smoke.js",
      "node scripts/automatic-free-downgrade-retry-smoke.js",
      "node scripts/lifecycle-provider-scheduling-smoke.js"
    ],
    "check:fast:admin-ux": [
      "node scripts/admin-ux-foundation-smoke.js",
      "node scripts/admin-guided-setup-search-smoke.js",
      "node scripts/admin-operational-dashboard-integrations-smoke.js",
      "node scripts/admin-shared-ui-smoke.js",
      "node scripts/html-primitives-smoke.js",
      "node scripts/admin-accessibility-mobile-smoke.js",
      "node scripts/admin-command-palette-smoke.js",
      "node scripts/admin-settings-coherence-smoke.js",
      "node scripts/admin-visible-actions-smoke.js",
      "node scripts/admin-inline-behavior-audit.js",
      "node scripts/admin-route-ownership-audit.js",
      "node scripts/platform-router-composition-smoke.js",
      "node scripts/visible-workflow-targets-smoke.js",
      "node scripts/workflow-handler-coverage-smoke.js",
      "node scripts/admin-product-audit-smoke.js",
      "node scripts/admin-global-filter-bars-smoke.js",
      "node scripts/admin-surface-hierarchy-smoke.js",
      "node scripts/admin-adaptive-plan-create-smoke.js",
      "node scripts/admin-operator-clarity-smoke.js",
      "node scripts/admin-header-business-metrics-smoke.js"
    ],
    "check:fast:commerce-support": [
      "node scripts/health-readiness-smoke.js",
      "node scripts/storefront-currency-integrity-smoke.js",
      "node scripts/currency-narrow-symbol-smoke.js",
      "node scripts/attention-workflow-smoke.js",
      "node scripts/plan-input-normalization-smoke.js",
      "node scripts/configuration-transfer-ownership-smoke.js",
      "node scripts/unified-plan-control-room-smoke.js",
      "node scripts/request-plan-jellyseerr-policy-smoke.js",
      "node scripts/marketing-campaigns-smoke.js",
      "node scripts/support-tickets-smoke.js",
      "node scripts/operator-read-cursors-smoke.js",
      "node scripts/support-ticket-notifications-smoke.js",
      "node scripts/paypal-return-race-smoke.js",
      "node scripts/paypal-subscription-payment-ledger-smoke.js",
      "node scripts/customer-payment-ledger-surface-smoke.js",
      "node scripts/provider-financial-state-smoke.js",
      "node scripts/payment-history-import-smoke.js",
      "node scripts/financial-date-boundary-smoke.js",
      "node scripts/legacy-payment-history-bridge-smoke.js",
      "node scripts/live-stripe-payment-history-smoke.js",
      "node scripts/legacy-customer-import-smoke.js",
      "node scripts/subscription-discovery-smoke.js",
      "node scripts/transaction-browser-smoke.js",
      "node scripts/plisio-payments-smoke.js",
      "node scripts/customer-playback-trust-smoke.js",
      "node scripts/checkout-abandonment-smoke.js",
      "node scripts/customer-error-sanitization-smoke.js"
    ],
    "check:fast:dashboards": [
      "node scripts/dashboard-business-layout-smoke.js",
      "node scripts/admin-analytics-dashboard-smoke.js",
      "node scripts/admin-dashboard-layout-persistence-smoke.js",
      "node scripts/admin-dashboard-layout-api-smoke.js",
      "node scripts/admin-dashboard-widget-visibility-smoke.js",
      "node scripts/admin-main-dashboard-widgets-smoke.js",
      "node scripts/admin-users-dashboard-smoke.js",
      "node scripts/admin-commerce-dashboard-smoke.js",
      "node scripts/business-expenses-smoke.js",
      "node scripts/admin-servers-dashboard-smoke.js"
    ],
    "check:fast:service-access": [
      "node scripts/plan-driven-access-smoke.js",
      "node scripts/plan-portal-cleanup-smoke.js",
      "node scripts/modular-access-drivers-smoke.js",
      "node scripts/jellyfin-lifecycle-stremio-pool-smoke.js",
      "node scripts/customer-bot-commerce-smoke.js",
      "node scripts/discord-role-reconciliation-smoke.js",
      "node scripts/discord-relink-role-revocation-smoke.js",
      "node scripts/customer-communications-page-smoke.js",
      "node scripts/customer-portal-ia-smoke.js",
      "node scripts/customer-portal-state-smoke.js",
      "node scripts/customer-dashboard-readonly-smoke.js",
      "node scripts/free-access-customer-portal-smoke.js",
      "node scripts/admin-coherence-user-overrides-smoke.js",
      "node scripts/media-identity-reconciliation-smoke.js",
      "node scripts/admin-navigation-coherence-smoke.js",
      "node scripts/notification-multicurrency-smoke.js",
      "node scripts/workflow-notification-correctness-smoke.js"
    ],
    "check:fast:stremio-release": [
      "node scripts/stremio-foundation-smoke.js",
      "node scripts/stremio-admin-smoke.js",
      "node scripts/stremio-zero-downtime-index-smoke.js",
      "node scripts/stremio-managed-sources-smoke.js",
      "node scripts/media-identity-reconciliation-smoke.js",
      "node scripts/stremio-playback-compatibility-smoke.js",
      "node scripts/stremio-episode-resolution-smoke.js",
      "node scripts/stremio-plan-source-composition-smoke.js",
      "node scripts/stremio-source-client-smoke.js",
      "node scripts/stremio-household-access-smoke.js",
      "node scripts/stremio-edge-auth-smoke.js",
      "node scripts/stremio-journey-polish-smoke.js",
      "node scripts/product-readiness-smoke.js",
      "node scripts/service-aware-portals-smoke.js",
      "node scripts/multi-service-subscriptions-smoke.js",
      "node scripts/plan-zero-capacity-smoke.js",
      "node scripts/canonical-service-authority-db-smoke.js",
      "node scripts/remaining-revenue-lifecycle-smoke.js",
      "node scripts/residual-temporal-invariants-smoke.js",
      "npm run check:post443-payment-fast",
      "npm run check:post441-ten-bug-fast",
      "npm run check:release-completion",
      "npm run db:backup-smoke"
    ],
    "check:db:integrity": [
      "node scripts/access-integrity-db-smoke.js",
      "node scripts/revenue-integrity-admin-pin-db-smoke.js",
      "node scripts/lifecycle-integrity-smoke.js",
      "node scripts/free-access-registration-reservation-db-smoke.js",
      "node scripts/platform-coherence-db-smoke.js",
      "node scripts/marketing-segments-db-smoke.js",
      "node scripts/whatsapp-removal-completeness-db-smoke.js",
      "node scripts/admin-jellyfin-assignment-lock-db-smoke.js",
      "node scripts/database-operational-hardening-db-smoke.js",
      "node scripts/worker-instance-health-db-smoke.js"
    ],
    "check:db:access": [
      "node scripts/request-user-sync-smoke.js",
      "node scripts/admin-jellyfin-reenable-db-smoke.js",
      "node scripts/access-entitlement-matrix-db-smoke.js",
      "node scripts/customer-entitlements-admin-authority-db-smoke.js",
      "node scripts/chargeback-terminates-access-db-smoke.js",
      "node scripts/admin-owner-gating-security-db-smoke.js",
      "node scripts/bulk-extend-refund-termination-safety-db-smoke.js",
      "node scripts/free-account-lane-adoption-history-db-smoke.js",
      "node scripts/transactional-email-smoke.js",
      "node scripts/automatic-free-downgrade-retry-db-smoke.js",
      "node scripts/end-current-jellyfin-plan-db-smoke.js",
      "node scripts/residual-temporal-invariants-db-smoke.js"
    ],
    "check:db:commerce": [
      "node scripts/business-expenses-calendar-date-db-smoke.js",
      "node scripts/plan-command-rollback-db-smoke.js",
      "node scripts/affiliate-renewal-credit-smoke.js",
      "node scripts/refund-cash-basis-smoke.js",
      "node scripts/refund-queue-timezone-db-smoke.js",
      "node scripts/provider-financial-state-db-smoke.js",
      "node scripts/payment-history-coverage-timezone-db-smoke.js",
      "node scripts/prepaid-access-stacking-smoke.js",
      "node scripts/same-plan-access-extension-db-smoke.js",
      "node scripts/prorata-refund-db-smoke.js",
      "node scripts/prorata-refund-retry-db-smoke.js",
      "node scripts/affiliate-first-payment-only-db-smoke.js",
      "node scripts/billing-lifecycle-smoke.js",
      "node scripts/payment-event-unsupported-provider-retry-db-smoke.js",
      "node scripts/payment-event-replay-db-smoke.js",
      "node scripts/provider-checkout-recovery-db-smoke.js",
      "node scripts/provider-operation-recovery-db-smoke.js"
    ],
    "check:db:concurrency": [
      "node scripts/state-machine-invariants-db-smoke.js",
      "node scripts/adversarial-concurrency-smoke.js",
      "node scripts/provisioning-control-db-smoke.js",
      "node scripts/jellyfin-account-creation-recovery-db-smoke.js",
      "npm run check:discount-checkout-db",
      "npm run check:post443-payment-db",
      "npm run check:post441-ten-bug-db",
      "npm run check:post451-ten-bug-db"
    ]
  },
  "aliases": {
    "check:fast": [
      "check:fast:foundation",
      "check:fast:operations",
      "check:fast:customer-access",
      "check:fast:admin-ux",
      "check:fast:commerce-support",
      "check:fast:dashboards",
      "check:fast:service-access",
      "check:fast:stremio-release"
    ],
    "check:db": [
      "check:db:integrity",
      "check:db:access",
      "check:db:commerce",
      "check:db:concurrency"
    ],
    "check:release": [
      "check:fast",
      "check:db"
    ]
  },
  "tags": {
    "fast": [
      "check:fast"
    ],
    "db": [
      "check:db"
    ],
    "billing": [
      "check:fast:commerce-support",
      "check:db:commerce"
    ],
    "access": [
      "check:fast:foundation",
      "check:fast:customer-access",
      "check:fast:service-access",
      "check:db:integrity",
      "check:db:access",
      "check:db:concurrency"
    ],
    "browser": [
      "check:fast:admin-ux",
      "check:fast:dashboards",
      "check:fast:operations"
    ],
    "security": [
      "check:fast:foundation"
    ]
  }
};
