'use strict';

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const root = path.join(__dirname, '..');
const installScript = fs.readFileSync(path.join(root, 'install.sh'), 'utf8');
const updateScript = fs.readFileSync(path.join(root, 'update.sh'), 'utf8');
const template = path.join(root, '.env.example');
const prepareInstall = path.join(root, 'scripts', 'prepare-install-env.js');
const prepareProduction = path.join(root, 'scripts', 'prepare-production-env.js');

function bashPath() {
  if (process.platform !== 'win32') return 'bash';
  for (const candidate of ['C:\\Program Files\\Git\\bin\\bash.exe', 'C:\\Program Files\\Git\\usr\\bin\\bash.exe']) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return 'bash';
}

for (const file of ['install.sh', 'update.sh']) {
  const syntax = spawnSync(bashPath(), ['-n', path.join(root, file)], { encoding: 'utf8' });
  assert.strictEqual(syntax.status, 0, syntax.stderr || `${file} must pass bash -n`);
}

for (const token of [
  'prepare-install-env.js',
  '--output=.env',
  'Existing .env detected; preserving all installation secrets',
  'bash scripts/deploy-production.sh',
  'docker compose exec -T app npm run setup:claim',
  'bash update.sh',
  '127.0.0.1:3030'
]) assert(installScript.includes(token), `install.sh must contain ${token}`);

for (const token of [
  'git diff --quiet',
  `[[ "$branch" == 'main' ]]`,
  'git fetch origin main',
  'git rev-list --count origin/main..HEAD',
  'git merge --ff-only origin/main',
  'scripts/deploy-production.sh'
]) assert(updateScript.includes(token), `update.sh must contain ${token}`);

assert(!installScript.includes('openssl rand'), 'installer secret generation must not depend on optional host OpenSSL tooling');
assert(!installScript.includes('POSTGRES_PASSWORD='), 'installer shell must never embed or print generated database passwords');
assert(!installScript.includes('DATA_ENCRYPTION_KEY='), 'installer shell must never embed or print generated encryption keys');

const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'captainfin-install-'));
try {
  const envFile = path.join(tempDir, '.env');
  const generated = spawnSync(process.execPath, [prepareInstall, `--output=${envFile}`, `--template=${template}`], { encoding: 'utf8' });
  assert.strictEqual(generated.status, 0, generated.stderr || 'fresh-install environment generation must succeed');
  assert(fs.existsSync(envFile), 'fresh installer must create .env');
  if (process.platform !== 'win32') assert.strictEqual(fs.statSync(envFile).mode & 0o777, 0o600, 'generated .env must be owner-only');

  const content = fs.readFileSync(envFile, 'utf8');
  assert(content.startsWith('# Generated by CAPTAiNFiN install.sh.'), 'generated environment must identify its safe installer origin');
  assert(!content.includes('replace-with-unique-'), 'fresh installer must remove every example database placeholder');

  const value = key => content.match(new RegExp(`^${key}=(.*)$`, 'm'))?.[1] || '';
  const owner = value('POSTGRES_PASSWORD');
  assert(/^[a-f0-9]{64}$/.test(owner), 'PostgreSQL owner password must be 32 random bytes encoded as hex');
  const ownerUrl = new URL(value('DATABASE_URL'));
  assert.strictEqual(decodeURIComponent(ownerUrl.password), owner, 'DATABASE_URL must use the generated PostgreSQL owner password');

  const coreKeys = ['DATA_ENCRYPTION_KEY','JELLYFIN_ENCRYPTION_KEY','ACTIVITY_ENCRYPTION_KEY','AUTH_ENCRYPTION_KEY','BACKUP_ENCRYPTION_KEY','STREMIO_JELLYFIN_TOKEN_KEY'];
  const secrets = new Set([owner]);
  for (const key of coreKeys) {
    const secret = value(key);
    assert(/^[a-f0-9]{64}$/.test(secret), `${key} must be 32 random bytes encoded as hex`);
    assert(!secrets.has(secret), `${key} must not reuse another installation secret`);
    secrets.add(secret);
  }
  assert(/^[a-f0-9]{96}$/.test(value('SESSION_SECRET')), 'SESSION_SECRET must be 48 random bytes encoded as hex');
  assert.strictEqual(value('ADMIN_USERNAME'), '', 'interactive install must not invent an administrator username');
  assert.strictEqual(value('ADMIN_PASSWORD'), '', 'interactive install must not invent an administrator password');

  for (const key of ['APP_DATABASE_URL','AUTOMATION_DATABASE_URL','ACTIVITY_DATABASE_URL','BACKUP_DATABASE_URL','BACKUP_VERIFY_DATABASE_URL']) {
    assert.strictEqual(value(key), '', `${key} must be delegated to the production runtime-role generator`);
  }

  const prepared = spawnSync(process.execPath, [prepareProduction, '--write', `--env-file=${envFile}`], { encoding: 'utf8' });
  assert.strictEqual(prepared.status, 0, prepared.stderr || 'generated fresh-install environment must pass production preparation');
  const finalContent = fs.readFileSync(envFile, 'utf8');
  for (const [key, role] of [
    ['APP_DATABASE_URL','steamfusion_app'],
    ['AUTOMATION_DATABASE_URL','steamfusion_automation'],
    ['ACTIVITY_DATABASE_URL','steamfusion_activity'],
    ['BACKUP_DATABASE_URL','steamfusion_backup'],
    ['BACKUP_VERIFY_DATABASE_URL','steamfusion_backup_verify']
  ]) {
    const raw = finalContent.match(new RegExp(`^${key}=(.+)$`, 'm'))?.[1];
    assert(raw, `${key} must be generated by production preparation`);
    const url = new URL(raw);
    assert.strictEqual(decodeURIComponent(url.username), role, `${key} must use ${role}`);
    assert(decodeURIComponent(url.password).length >= 24, `${key} must have a strong generated password`);
  }

  const second = spawnSync(process.execPath, [prepareInstall, `--output=${envFile}`, `--template=${template}`], { encoding: 'utf8' });
  assert.notStrictEqual(second.status, 0, 'fresh-install generator must refuse to overwrite an existing .env');
  assert(/Refusing to replace installation secrets/.test(second.stderr), 'existing-secret refusal must be explicit');

  const placeholderFile = path.join(tempDir, '.env.placeholder');
  fs.copyFileSync(template, placeholderFile);
  const placeholder = spawnSync(process.execPath, [prepareProduction, '--write', `--env-file=${placeholderFile}`], { encoding: 'utf8' });
  assert.notStrictEqual(placeholder.status, 0, 'production preparation must reject raw .env.example placeholder credentials');
  assert(/placeholders/.test(placeholder.stderr), 'placeholder rejection must explain how to recover');
} finally {
  fs.rmSync(tempDir, { recursive: true, force: true });
}

console.log('installer smoke: ok');
