'use strict';

require('dotenv').config();
const fs=require('fs');
const os=require('os');
const path=require('path');
const crypto=require('crypto');
const {spawn}=require('child_process');
const {pipeline}=require('stream/promises');
const {Client}=require('pg');
const {parseHeader,createDecipherFromHeader,requireBackupKey}=require('../src/backup/encrypted-stream');
const {query,getPool}=require('../src/db');

function run(command,args,env){return new Promise((resolve,reject)=>{const child=spawn(command,args,{env,stdio:['ignore','pipe','pipe']}),stdout=[],stderr=[];child.stdout.on('data',x=>stdout.push(x));child.stderr.on('data',x=>stderr.push(x));child.once('error',reject);child.once('close',code=>code===0?resolve({stdout:Buffer.concat(stdout).toString(),stderr:Buffer.concat(stderr).toString()}):reject(new Error(`${command} exited ${code}: ${Buffer.concat(stderr).toString().slice(-3000)}`)));});}
function dbUrlFor(base,name){const url=new URL(base);url.pathname=`/${name}`;return url.toString();}
async function latestBackup(){const result=await query(`SELECT * FROM backup_runs WHERE status='succeeded' AND file_path IS NOT NULL ORDER BY started_at DESC LIMIT 1`);return result.rows[0]||null;}
async function mark(id,ok,note){if(!id)return;await query(`UPDATE backup_runs SET verified_at=CASE WHEN $2 THEN NOW() ELSE verified_at END,verification_note=$3,metadata=metadata||$4::jsonb WHERE id=$1`,[id,Boolean(ok),String(note||'').slice(0,2000),JSON.stringify({lastVerificationAttemptAt:new Date().toISOString(),lastVerificationOk:Boolean(ok)})]);}
async function main(){requireBackupKey();const record=process.argv[2]?null:await latestBackup(),input=path.resolve(process.argv[2]||record?.file_path||'');if(!input||!fs.existsSync(input))throw new Error('Backup file not found. Pass a .pgdump.enc path or create a managed backup first.');const runId=record?.id||(await query(`SELECT id FROM backup_runs WHERE file_path=$1 OR file_name=$2 ORDER BY started_at DESC LIMIT 1`,[input,path.basename(input)])).rows[0]?.id||null,tempDir=fs.mkdtempSync(path.join(process.env.BACKUP_RESTORE_TMPDIR||os.tmpdir(),'captainfin-verify-')),plain=path.join(tempDir,'restore.pgdump'),databaseName=`captainfin_verify_${crypto.randomBytes(6).toString('hex')}`,base=process.env.DATABASE_URL;if(!base)throw new Error('DATABASE_URL is required for restore verification.');const adminUrl=dbUrlFor(base,'postgres'),verifyUrl=dbUrlFor(base,databaseName),admin=new Client({connectionString:adminUrl});let created=false;try{const {header,headerLength}=parseHeader(input),decipher=createDecipherFromHeader(header),stat=fs.statSync(input),cipherStart=headerLength,cipherEnd=stat.size-17;if(cipherEnd<cipherStart)throw new Error('Encrypted backup is truncated.');const tag=Buffer.alloc(16);fs.readSync(fs.openSync(input,'r'),tag,0,16,stat.size-16);decipher.setAuthTag(tag);await pipeline(fs.createReadStream(input,{start:cipherStart,end:cipherEnd}),decipher,fs.createWriteStream(plain,{mode:0o600}));await run(process.env.PG_RESTORE_BIN||'pg_restore',['--list',plain],process.env);await admin.connect();await admin.query(`CREATE DATABASE ${databaseName}`);created=true;await run(process.env.PG_RESTORE_BIN||'pg_restore',['--no-owner','--no-privileges','--dbname',verifyUrl,plain],process.env);const verify=new Client({connectionString:verifyUrl});await verify.connect();const schema=await verify.query(`SELECT COUNT(*)::int n FROM information_schema.tables WHERE table_schema='public'`);const migrations=await verify.query(`SELECT to_regclass('public.schema_migrations') present`);await verify.end();if(Number(schema.rows[0]?.n||0)<5||!migrations.rows[0]?.present)throw new Error('Restored database did not contain the expected CAPTaINFiN schema.');const note=`Full temporary restore succeeded into ${databaseName}; ${schema.rows[0].n} public tables detected.`;await mark(runId,true,note);console.log(note);}catch(error){await mark(runId,false,error.message).catch(()=>{});throw error;}finally{if(created){try{if(!admin._connected)await admin.connect();await admin.query(`DROP DATABASE IF EXISTS ${databaseName} WITH (FORCE)`);}catch(error){console.warn('Temporary verification database cleanup failed:',error.message);}}try{await admin.end();}catch(_){}try{fs.rmSync(tempDir,{recursive:true,force:true});}catch(_){}try{await getPool().end();}catch(_){}}}
main().catch(error=>{console.error(`Backup verification failed: ${error.message}`);process.exit(1);});
