'use strict';
const express=require('express');
const {query,transaction}=require('../db');
const csrf=require('../auth/csrf');
const auth=require('../auth/service');
const stripe=require('../payments/stripe');
const paypal=require('../payments/paypal');
function gate(req,res,next){if(req.session?.authUserId&&req.session?.authRole==='admin'&&req.session?.adminId)return next();return res.redirect('/login?session=expired')}
function noStore(_q,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next()}
function b(v){return v==='on'||v==='true'||v===true}
function n(v,min,max,f){const x=parseInt(v,10);return Number.isFinite(x)&&x>=min&&x<=max?x:f}
function t(v,max){return String(v||'').trim().slice(0,max)}
async function data(){const r=await query(`SELECT p.*,COALESCE(jsonb_agg(jsonb_build_object('provider',pp.provider,'externalId',pp.external_id,'checkoutMode',pp.checkout_mode,'active',pp.active)) FILTER(WHERE pp.id IS NOT NULL),'[]'::jsonb) provider_prices FROM plans p LEFT JOIN plan_provider_prices pp ON pp.plan_id=p.id GROUP BY p.id ORDER BY p.sort_order,p.price_minor`);return r.rows}
function createAdminPlansRouter(){const r=express.Router();r.use('/admin/plans',gate,noStore);
r.get('/admin/plans',async(req,res,next)=>{try{return res.render('admin/plans',{siteName:process.env.SITE_NAME||'CAPTaINFiN',activeNav:'plans',plans:await data(),csrfToken:csrf.token(req),message:req.query.message||null,error:req.query.error||null,stripeEnabled:stripe.enabled(),paypalEnabled:paypal.enabled()})}catch(e){next(e)}});
r.post('/admin/plans/:id',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(!(await auth.verifySecondFactor(req.session.authUserId,req.body.code,req)))throw new Error('verification');const price=Number(req.body.price),name=t(req.body.name,80);if(!name||!Number.isFinite(price)||price<0||price>10000)throw new Error('validation');await transaction(async c=>{const u=await c.query(`UPDATE plans SET name=$2,description=$3,price_minor=$4,streams=$5,allow_downloads=$6,allow_video_transcoding=$7,allow_audio_transcoding=$8,allow_live_tv=$9,allow_4k=$10,visible=$11,active=$12,sort_order=$13,updated_at=NOW() WHERE id=$1 RETURNING id`,[req.params.id,name,t(req.body.description,500),Math.round(price*100),n(req.body.streams,1,20,1),b(req.body.allowDownloads),b(req.body.allowVideoTranscoding),b(req.body.allowAudioTranscoding),b(req.body.allowLiveTv),b(req.body.allow4k),b(req.body.visible),b(req.body.active),n(req.body.sortOrder,0,10000,100)]);if(!u.rowCount)throw new Error('missing');await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.update','plan',$2,$3::jsonb)`,[req.session.authUserId,req.params.id,JSON.stringify({name})])});return res.redirect('/admin/plans?message='+encodeURIComponent('Plan updated.'))}catch(e){console.error('Plan update failed:',e.message);return res.redirect('/admin/plans?error='+encodeURIComponent(e.message==='verification'?'Verification failed.':'Plan could not be updated safely.'))}});
r.post('/admin/plans/:id/provider',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(!(await auth.verifySecondFactor(req.session.authUserId,req.body.code,req)))throw new Error('verification');const provider=t(req.body.provider,20);if(!['stripe','paypal'].includes(provider))throw new Error('provider');const external=t(req.body.externalId,200),mode=req.body.checkoutMode==='subscription'?'subscription':'payment';await transaction(async c=>{if(external)await c.query(`INSERT INTO plan_provider_prices(plan_id,provider,external_id,checkout_mode,active) VALUES($1,$2,$3,$4,TRUE) ON CONFLICT(plan_id,provider) DO UPDATE SET external_id=EXCLUDED.external_id,checkout_mode=EXCLUDED.checkout_mode,active=TRUE,updated_at=NOW()`,[req.params.id,provider,external,mode]);else await c.query('DELETE FROM plan_provider_prices WHERE plan_id=$1 AND provider=$2',[req.params.id,provider]);await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.provider_mapping','plan',$2,$3::jsonb)`,[req.session.authUserId,req.params.id,JSON.stringify({provider,configured:Boolean(external),mode})])});return res.redirect('/admin/plans?message='+encodeURIComponent('Payment mapping updated.'))}catch(e){return res.redirect('/admin/plans?error='+encodeURIComponent('Payment mapping could not be updated.'))}});
r.use('/admin/plans',(e,_q,res,_n)=>{console.error('Plans error:',e.message);return res.status(500).render('auth/message',{siteName:process.env.SITE_NAME||'CAPTaINFiN',title:'Plans unavailable',message:'Plans could not be loaded safely.',link:'/admin',linkText:'Back'})});return r}
module.exports={createAdminPlansRouter,data};
