'use strict';

const express=require('express');
const {query}=require('../db');
const runtimeSettings=require('./runtime-settings');
const {esc,layout}=require('./admin-html');

function gate(req,res,next){return req.session?.authUserId&&req.session?.authRole==='admin'?next():res.redirect('/login?session=expired');}
function money(minor,currency){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:String(currency||'GBP').trim()}).format(Number(minor||0)/100)}catch{return `${currency||'GBP'} ${(Number(minor||0)/100).toFixed(2)}`}}
function when(value){try{return new Date(value).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}catch{return String(value||'—')}}
async function rows(){return(await query(`SELECT s.id,s.customer_id,s.status,s.source,s.created_at,s.plan_name_snapshot,s.plan_code_snapshot,s.price_minor_snapshot,s.currency_snapshot,c.display_name,c.login_email,c.login_username FROM subscriptions s JOIN customers c ON c.id=s.customer_id WHERE s.source IN ('stripe','paypal') AND COALESCE(s.price_minor_snapshot,0)>0 ORDER BY s.created_at DESC LIMIT 500`)).rows;}
async function page(){await runtimeSettings.ensureLoaded();const orders=await rows();const body=`<div class="statusBanner"><strong>Orders:</strong> paid Stripe and PayPal subscriptions. Free access, trials with no charge and manual/admin grants are excluded.</div><section class="section"><div class="sectionHead"><div><h2>Recent orders</h2><div class="muted">${orders.length} most recent paid subscription records</div></div></div>${orders.length?`<div class="table"><div class="tableHead" style="grid-template-columns:120px minmax(180px,1.3fr) minmax(180px,1fr) 120px 120px"><span>Date</span><span>Customer</span><span>Plan</span><span>Amount</span><span>Status</span></div>${orders.map(row=>{const customer=row.display_name||row.login_username||row.login_email||row.customer_id;return `<a class="tableRow" href="/admin/users/${esc(row.customer_id)}" style="grid-template-columns:120px minmax(180px,1.3fr) minmax(180px,1fr) 120px 120px;text-decoration:none;color:inherit"><span>${esc(when(row.created_at))}</span><span><strong>${esc(customer)}</strong><small>${esc(row.source)}</small></span><span>${esc(row.plan_name_snapshot||row.plan_code_snapshot||'Plan')}</span><span>${esc(money(row.price_minor_snapshot,row.currency_snapshot))}</span><span><span class="pill ${row.status==='past_due'?'bad':'good'}">${esc(row.status)}</span></span></a>`}).join('')}</div>`:'<div class="empty">No paid orders yet.</div>'}</section>`;return layout({siteName:runtimeSettings.siteName(),active:'orders',title:'Orders',subtitle:'Recent paid customer purchases',body});}
function createAdminOrdersRouter(){const router=express.Router();router.use('/admin/orders',gate);router.get('/admin/orders',async(_req,res,next)=>{try{return res.send(await page())}catch(error){next(error)}});return router;}
module.exports={createAdminOrdersRouter,page,rows};
