'use strict';
const express=require('express');
const {query,transaction}=require('../db');
const csrf=require('../auth/csrf');
const auth=require('../auth/service');
const stripe=require('../payments/stripe');
const paypal=require('../payments/paypal');
const provisioning=require('../jellyfin/provisioning');
const policy=require('../jellyfin/policy');
const {esc,layout}=require('./admin-html');
const {sendCsv}=require('./export');

function gate(req,res,next){if(req.session?.authUserId&&req.session?.authRole==='admin'&&req.session?.adminId)return next();return res.redirect('/login?session=expired')}
function noStore(_q,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next()}
function site(){return process.env.SITE_NAME||'CAPTAiNFiN'}
function b(v){return v==='on'||v==='true'||v===true}
function n(v,min,max,f){const x=parseInt(v,10);return Number.isFinite(x)&&x>=min&&x<=max?x:f}
function nullableInt(v,min=0,max=100000){if(v===undefined||v===null||String(v).trim()==='')return null;const x=parseInt(v,10);if(!Number.isFinite(x)||x<min||x>max)throw new Error('validation');return x}
function t(v,max){return String(v||'').trim().slice(0,max)}
function money(v){const x=Number(v);if(!Number.isFinite(x)||x<0||x>100000)throw new Error('validation');return Math.round(x*100)}
function notice(req){return `${req.query.message?`<div class="notice success">${esc(req.query.message)}</div>`:''}${req.query.error?`<div class="notice error">${esc(req.query.error)}</div>`:''}`}
function stepField(){return `<div class="formGroup"><label>Authenticator / recovery code <span class="muted">(only when enabled)</span></label><input class="input" name="code" autocomplete="one-time-code"></div>`}

function planSubnav(planId,active){
    const items=[['overview','Overview',`/admin/plans/${planId}/edit`],['jellyfin','Jellyfin',`/admin/plans/${planId}/jellyfin`],['libraries','Libraries',`/admin/plans/${planId}/libraries`],['commerce','Commerce',`/admin/plans/${planId}/commerce`]];
    return `<div class="buttonRow planSubnav">${items.map(([key,label,url])=>`<a class="button ${active===key?'':'secondary'}" href="${url}">${label}</a>`).join('')}</div>`;
}

async function planById(id){const r=await query('SELECT * FROM plans WHERE id=$1',[id]);return r.rows[0]||null}
async function activeSubscriberCount(planId){const r=await query(`SELECT COUNT(DISTINCT customer_id)::int n FROM subscriptions WHERE plan_id=$1 AND status IN ('active','trialing','past_due') AND current_period_end>NOW()`,[planId]);return r.rows[0]?.n||0}

async function listData(){const r=await query(`SELECT p.*,COALESCE(jsonb_agg(jsonb_build_object('provider',pp.provider,'externalId',pp.external_id,'checkoutMode',pp.checkout_mode,'active',pp.active)) FILTER(WHERE pp.id IS NOT NULL),'[]'::jsonb) provider_prices,(SELECT COUNT(*)::int FROM subscriptions s WHERE s.plan_id=p.id) subscription_count FROM plans p LEFT JOIN plan_provider_prices pp ON pp.plan_id=p.id GROUP BY p.id ORDER BY p.active DESC,p.sort_order,p.price_minor,p.name`);return r.rows}

function overviewInput(body,{creating=false}={}){
    const name=t(body.name,80),description=t(body.description,500);
    const audience=['direct','reseller','both'].includes(body.audience)?body.audience:'direct';
    const billing=['trial','month','6_months','year','custom'].includes(body.billingInterval)?body.billingInterval:'custom';
    if(!name)throw new Error('validation');
    const code=creating?t(body.code,50).toLowerCase():null;
    if(creating&&!/^[a-z0-9][a-z0-9-]{1,49}$/.test(code))throw new Error('validation');
    return{code,name,description,audience,billing,duration:n(body.durationDays,1,3650,30),serverClass:['premium','free','custom'].includes(body.serverClass)?body.serverClass:'premium',visible:b(body.visible),active:b(body.active),sort:n(body.sortOrder,0,10000,100)};
}
function jellyfinInput(body){
    return{streams:n(body.streams,1,50,1),downloads:b(body.allowDownloads),video:b(body.allowVideoTranscoding),audio:b(body.allowAudioTranscoding),remux:b(body.allowRemuxing),live:b(body.allowLiveTv),liveManagement:b(body.allowLiveTvManagement),remoteAccess:b(body.allowRemoteAccess),fourk:b(body.allow4k)};
}
function commerceInput(body,audience){
    const currency=t(body.currency,3).toUpperCase();
    if(!/^[A-Z]{3}$/.test(currency))throw new Error('validation');
    return{priceMinor:money(body.price),currency,creditCost:audience==='direct'?null:nullableInt(body.resellerCreditCost),trialCreditCost:audience==='direct'?null:nullableInt(body.resellerTrialCreditCost,0,20)};
}

function planCard(p){
    const status=p.active?'good':'bad';
    return `<a class="serverCard" href="/admin/plans/${esc(p.id)}/edit"><div class="serverTop"><strong>${esc(p.name)}</strong><span class="pill ${status}">${p.active?'Active':'Archived'}</span></div><div class="subText">${esc(p.code)} · ${esc(p.audience)} · ${esc(p.billing_interval)}</div><p class="muted">${esc(p.description||'No description')}</p><p><span class="pill">${esc(p.streams)} stream${Number(p.streams)===1?'':'s'}</span><span class="pill">${p.price_minor===0?'Free':esc(p.currency)+' '+(Number(p.price_minor)/100).toFixed(2)}</span><span class="pill">${esc(p.subscription_count)} subscriber${Number(p.subscription_count)===1?'':'s'}</span></p></a>`;
}

async function listPage(req){
    const rows=await listData();
    const body=`${notice(req)}<section class="section"><div class="sectionHead"><h2>Plans</h2><span class="muted">${rows.length} total</span></div>${rows.length?`<div class="serverGrid">${rows.map(planCard).join('')}</div>`:'<div class="empty">No plans yet. Create your first plan to start selling access.</div>'}</section>`;
    return layout({siteName:site(),active:'plans',title:'Plans',subtitle:'Pricing, entitlements and provider mappings',body,action:'<a class="button" href="/admin/plans/new">Add plan</a> <a class="button secondary" href="/admin/plans/export">Export CSV</a>'});
}

function newPlanPage(req){
    const body=`${notice(req)}<section class="section"><div class="sectionHead"><h2>New plan</h2><span class="muted">Jellyfin policy, libraries and pricing are configured after creation.</span></div><form class="formPanel" method="post" action="/admin/plans">${csrfInput(req)}<div class="formGrid"><div class="formGroup"><label>Code</label><input class="input" name="code" required pattern="[a-z0-9][a-z0-9-]{1,49}" placeholder="premium-monthly"></div><div class="formGroup"><label>Name</label><input class="input" name="name" required maxlength="80"></div></div><div class="formGroup"><label>Description</label><textarea class="input" name="description" maxlength="500"></textarea></div><div class="formGrid"><div class="formGroup"><label>Audience</label><select class="input" name="audience"><option value="direct">Direct</option><option value="reseller">Reseller</option><option value="both">Both</option></select></div><div class="formGroup"><label>Billing interval</label><select class="input" name="billingInterval"><option value="trial">Trial</option><option value="month">Monthly</option><option value="6_months">6 months</option><option value="year">Yearly</option><option value="custom">Custom</option></select></div><div class="formGroup"><label>Duration (days)</label><input class="input" type="number" name="durationDays" min="1" max="3650" value="30"></div></div><div class="formGroup"><label>Server class</label><select class="input" name="serverClass"><option value="premium">Premium</option><option value="free">Free</option><option value="custom">Custom</option></select></div><label class="toggleRow"><input type="checkbox" name="visible" checked><span>Visible to customers</span></label><label class="toggleRow"><input type="checkbox" name="active" checked><span>Active</span></label>${stepField()}<div class="buttonRow"><button class="button">Create plan</button><a class="button secondary" href="/admin/plans">Cancel</a></div></form></section>`;
    return layout({siteName:site(),active:'plans',title:'New plan',subtitle:'Create a plan, then configure Jellyfin policy and libraries',body});
}

function csrfInput(req){return `<input type="hidden" name="_csrf" value="${esc(csrf.token(req))}">`}

function overviewPage(req,plan){
    const body=`${notice(req)}${planSubnav(plan.id,'overview')}<section class="section"><div class="sectionHead"><h2>Overview</h2></div><form class="formPanel" method="post" action="/admin/plans/${esc(plan.id)}">${csrfInput(req)}<div class="formGroup"><label>Name</label><input class="input" name="name" maxlength="80" value="${esc(plan.name)}"></div><div class="formGroup"><label>Description</label><textarea class="input" name="description" maxlength="500">${esc(plan.description)}</textarea></div><div class="formGrid"><div class="formGroup"><label>Audience</label><select class="input" name="audience">${['direct','reseller','both'].map(a=>`<option value="${a}" ${plan.audience===a?'selected':''}>${a}</option>`).join('')}</select></div><div class="formGroup"><label>Billing interval</label><select class="input" name="billingInterval">${['trial','month','6_months','year','custom'].map(x=>`<option value="${x}" ${plan.billing_interval===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="formGroup"><label>Duration (days)</label><input class="input" type="number" name="durationDays" min="1" max="3650" value="${esc(plan.duration_days||30)}"></div></div><div class="formGrid"><div class="formGroup"><label>Server class</label><select class="input" name="serverClass">${['premium','free','custom'].map(x=>`<option value="${x}" ${plan.server_class===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="formGroup"><label>Sort order</label><input class="input" type="number" name="sortOrder" value="${esc(plan.sort_order)}"></div></div><div class="toggleGrid"><label class="toggleRow"><input type="checkbox" name="visible" ${plan.visible?'checked':''}><span>Visible to customers</span></label><label class="toggleRow"><input type="checkbox" name="active" ${plan.active?'checked':''}><span>Active</span></label></div>${stepField()}<div class="buttonRow"><button class="button">Save overview</button><a class="button secondary" href="/admin/plans/${esc(plan.id)}/archive-confirm">Archive plan</a></div></form></section>`;
    return layout({siteName:site(),active:'plans',title:plan.name,subtitle:'Plan overview',body});
}

async function jellyfinPage(req,plan){
    const activeCount=await activeSubscriberCount(plan.id);
    const impact=activeCount?`<div class="notice">This plan has ${esc(activeCount)} active customer${activeCount===1?'':'s'}. Saving will queue Jellyfin policy reconciliation for all of them in the background.</div>`:'';
    const toggle=(name,label,checked)=>`<label class="toggleRow"><input type="checkbox" name="${name}" ${checked?'checked':''}><span>${esc(label)}</span></label>`;
    const body=`${notice(req)}${planSubnav(plan.id,'jellyfin')}<section class="section"><div class="sectionHead"><h2>Jellyfin policy</h2><span class="muted">What CAPTaINFiN grants Jellyfin accounts on this plan</span></div>${impact}<form class="formPanel" method="post" action="/admin/plans/${esc(plan.id)}/jellyfin">${csrfInput(req)}<div class="formGroup narrow"><label>Concurrent streams</label><input class="input" type="number" name="streams" min="1" max="50" value="${esc(plan.streams)}"></div><div class="toggleGrid">${toggle('allowDownloads','Downloads',plan.allow_downloads)}${toggle('allowVideoTranscoding','Video transcoding',plan.allow_video_transcoding)}${toggle('allowAudioTranscoding','Audio transcoding',plan.allow_audio_transcoding)}${toggle('allowRemuxing','Remuxing',plan.allow_remuxing)}${toggle('allowLiveTv','Live TV',plan.allow_live_tv)}${toggle('allowLiveTvManagement','Live TV recording / management',plan.allow_live_tv_management)}${toggle('allowRemoteAccess','Remote access',plan.allow_remote_access)}${toggle('allow4k','4K content',plan.allow_4k)}</div>${stepField()}<div class="buttonRow"><button class="button">Save Jellyfin policy</button></div></form></section>`;
    return layout({siteName:site(),active:'plans',title:plan.name,subtitle:'Jellyfin policy',body});
}

async function commercePage(req,plan){
    const stripeMap=(await query('SELECT external_id,checkout_mode FROM plan_provider_prices WHERE plan_id=$1 AND provider=$2',[plan.id,'stripe'])).rows[0];
    const paypalMap=(await query('SELECT external_id,checkout_mode FROM plan_provider_prices WHERE plan_id=$1 AND provider=$2',[plan.id,'paypal'])).rows[0];
    const body=`${notice(req)}${planSubnav(plan.id,'commerce')}<section class="section"><div class="sectionHead"><h2>Pricing</h2></div><form class="formPanel" method="post" action="/admin/plans/${esc(plan.id)}/commerce">${csrfInput(req)}<div class="formGrid"><div class="formGroup"><label>Price</label><input class="input" type="number" step="0.01" min="0" name="price" value="${(Number(plan.price_minor)/100).toFixed(2)}"></div><div class="formGroup"><label>Currency</label><input class="input" name="currency" maxlength="3" value="${esc(plan.currency)}"></div></div>${plan.audience!=='direct'?`<div class="formGrid"><div class="formGroup"><label>Reseller credit cost</label><input class="input" type="number" min="0" name="resellerCreditCost" value="${esc(plan.reseller_credit_cost??'')}"></div><div class="formGroup"><label>Reseller trial credit cost</label><input class="input" type="number" min="0" max="20" name="resellerTrialCreditCost" value="${esc(plan.reseller_trial_credit_cost??'')}"></div></div>`:''}${stepField()}<button class="button">Save pricing</button></form></section><section class="section"><div class="sectionHead"><h2>Payment provider mapping</h2></div><form class="formPanel" method="post" action="/admin/plans/${esc(plan.id)}/provider">${csrfInput(req)}<input type="hidden" name="provider" value="stripe"><div class="formGroup"><label>Stripe price ID</label><input class="input" name="externalId" value="${esc(stripeMap?.external_id||'')}"></div><select class="input" name="checkoutMode"><option value="payment" ${stripeMap?.checkout_mode==='payment'?'selected':''}>One-time payment</option><option value="subscription" ${stripeMap?.checkout_mode==='subscription'?'selected':''}>Recurring subscription</option></select>${stepField()}<button class="button secondary">Save Stripe mapping</button></form><form class="formPanel" method="post" action="/admin/plans/${esc(plan.id)}/provider">${csrfInput(req)}<input type="hidden" name="provider" value="paypal"><div class="formGroup"><label>PayPal plan/product ID</label><input class="input" name="externalId" value="${esc(paypalMap?.external_id||'')}"></div><select class="input" name="checkoutMode"><option value="payment" ${paypalMap?.checkout_mode==='payment'?'selected':''}>One-time payment</option><option value="subscription" ${paypalMap?.checkout_mode==='subscription'?'selected':''}>Recurring subscription</option></select>${stepField()}<button class="button secondary">Save PayPal mapping</button></form><div class="securityNote standalone">Provider secrets are configured on the server and are never displayed or editable here.</div></section>`;
    return layout({siteName:site(),active:'plans',title:plan.name,subtitle:'Commerce',body,stripeEnabled:stripe.enabled(),paypalEnabled:paypal.enabled()});
}

function archiveConfirmPage(req,plan){
    const body=`${notice(req)}${planSubnav(plan.id,'overview')}<section class="section"><div class="sectionHead"><h2>Archive ${esc(plan.name)}</h2></div><div class="notice error">Archiving hides this plan from customers and resellers. Existing subscription history is preserved and current subscribers keep their access until it naturally expires.</div><form class="formPanel" method="post" action="/admin/plans/${esc(plan.id)}/archive">${csrfInput(req)}${stepField()}<div class="buttonRow"><button class="button btn-danger">Archive plan</button><a class="button secondary" href="/admin/plans/${esc(plan.id)}/edit">Cancel</a></div></form></section>`;
    return layout({siteName:site(),active:'plans',title:'Archive plan',subtitle:plan.name,body});
}

function createAdminPlansRouter(){
    const r=express.Router();r.use('/admin/plans',gate,noStore);

    r.get('/admin/plans',async(req,res,next)=>{try{return res.send(await listPage(req))}catch(e){next(e)}});
    r.get('/admin/plans/export',async(req,res,next)=>{try{const rows=await listData();return sendCsv(res,'plans.csv',[{key:'code',label:'Code'},{key:'name',label:'Name'},{key:'audience',label:'Audience'},{key:'billing_interval',label:'Billing'},{key:'duration_days',label:'Duration days'},{label:'Price',value:p=>(Number(p.price_minor)/100).toFixed(2)},{key:'currency',label:'Currency'},{key:'streams',label:'Streams'},{key:'reseller_credit_cost',label:'Reseller credits'},{key:'active',label:'Active'},{key:'subscription_count',label:'Subscriptions'}],rows)}catch(e){next(e)}});
    r.get('/admin/plans/new',(req,res)=>res.send(newPlanPage(req)));
    r.get('/admin/plans/:id/edit',async(req,res,next)=>{try{const plan=await planById(req.params.id);if(!plan)return res.status(404).send('Plan not found');return res.send(overviewPage(req,plan))}catch(e){next(e)}});
    r.get('/admin/plans/:id/jellyfin',async(req,res,next)=>{try{const plan=await planById(req.params.id);if(!plan)return res.status(404).send('Plan not found');return res.send(await jellyfinPage(req,plan))}catch(e){next(e)}});
    r.get('/admin/plans/:id/commerce',async(req,res,next)=>{try{const plan=await planById(req.params.id);if(!plan)return res.status(404).send('Plan not found');return res.send(await commercePage(req,plan))}catch(e){next(e)}});
    r.get('/admin/plans/:id/archive-confirm',async(req,res,next)=>{try{const plan=await planById(req.params.id);if(!plan)return res.status(404).send('Plan not found');return res.send(archiveConfirmPage(req,plan))}catch(e){next(e)}});

    r.post('/admin/plans',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(!(await auth.verifySecondFactor(req.session.authUserId,req.body.code,req)))throw new Error('verification');const p=overviewInput(req.body,{creating:true});const created=await transaction(async c=>{const row=await c.query(`INSERT INTO plans(code,name,description,audience,billing_interval,duration_days,server_class,visible,active,sort_order,allow_remuxing,allow_remote_access) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,FALSE,TRUE) RETURNING id`,[p.code,p.name,p.description,p.audience,p.billing,p.duration,p.serverClass,p.visible,p.active,p.sort]);await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.create','plan',$2,$3::jsonb)`,[req.session.authUserId,row.rows[0].id,JSON.stringify({code:p.code,name:p.name,audience:p.audience})]);return row.rows[0]});return res.redirect(`/admin/plans/${encodeURIComponent(created.id)}/jellyfin?message=${encodeURIComponent('Plan created. Configure its Jellyfin policy and libraries next.')}`)}catch(e){console.error('Plan create failed:',e.message);const msg=e.code==='23505'?'That plan code already exists.':e.message==='verification'?'Verification failed.':'Plan could not be created safely.';return res.redirect('/admin/plans/new?error='+encodeURIComponent(msg))}});

    r.post('/admin/plans/:id',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(!(await auth.verifySecondFactor(req.session.authUserId,req.body.code,req)))throw new Error('verification');const p=overviewInput(req.body);await transaction(async c=>{const u=await c.query(`UPDATE plans SET name=$2,description=$3,audience=$4,billing_interval=$5,duration_days=$6,server_class=$7,visible=$8,active=$9,sort_order=$10,updated_at=NOW() WHERE id=$1 RETURNING id`,[req.params.id,p.name,p.description,p.audience,p.billing,p.duration,p.serverClass,p.visible,p.active,p.sort]);if(!u.rowCount)throw new Error('missing');await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.update','plan',$2,$3::jsonb)`,[req.session.authUserId,req.params.id,JSON.stringify({name:p.name,audience:p.audience})])});return res.redirect(`/admin/plans/${encodeURIComponent(req.params.id)}/edit?message=${encodeURIComponent('Overview saved.')}`)}catch(e){console.error('Plan update failed:',e.message);return res.redirect(`/admin/plans/${encodeURIComponent(req.params.id)}/edit?error=`+encodeURIComponent(e.message==='verification'?'Verification failed.':'Plan could not be updated safely.'))}});

    r.post('/admin/plans/:id/jellyfin',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(!(await auth.verifySecondFactor(req.session.authUserId,req.body.code,req)))throw new Error('verification');const p=jellyfinInput(req.body);const u=await query(`UPDATE plans SET streams=$2,allow_downloads=$3,allow_video_transcoding=$4,allow_audio_transcoding=$5,allow_remuxing=$6,allow_live_tv=$7,allow_live_tv_management=$8,allow_remote_access=$9,allow_4k=$10,updated_at=NOW() WHERE id=$1 RETURNING id`,[req.params.id,p.streams,p.downloads,p.video,p.audio,p.remux,p.live,p.liveManagement,p.remoteAccess,p.fourk]);if(!u.rowCount)throw new Error('missing');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.jellyfin_policy','plan',$2,$3::jsonb)`,[req.session.authUserId,req.params.id,JSON.stringify(p)]);const {queuePlanReconciliation}=require('./bulk-jobs');const job=await queuePlanReconciliation(req.params.id,req.session.authUserId);return res.redirect(job?`/admin/jobs/${encodeURIComponent(job.id)}?message=${encodeURIComponent('Jellyfin policy saved. Reconciliation queued for affected customers.')}`:`/admin/plans/${encodeURIComponent(req.params.id)}/jellyfin?message=${encodeURIComponent('Jellyfin policy saved.')}`)}catch(e){console.error('Plan Jellyfin update failed:',e.message);return res.redirect(`/admin/plans/${encodeURIComponent(req.params.id)}/jellyfin?error=`+encodeURIComponent(e.message==='verification'?'Verification failed.':'Jellyfin policy could not be updated safely.'))}});

    r.post('/admin/plans/:id/commerce',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(!(await auth.verifySecondFactor(req.session.authUserId,req.body.code,req)))throw new Error('verification');const plan=await planById(req.params.id);if(!plan)throw new Error('missing');const p=commerceInput(req.body,plan.audience);const u=await query(`UPDATE plans SET price_minor=$2,currency=$3,reseller_credit_cost=$4,reseller_trial_credit_cost=$5,updated_at=NOW() WHERE id=$1 RETURNING id`,[req.params.id,p.priceMinor,p.currency,p.creditCost,p.trialCreditCost]);if(!u.rowCount)throw new Error('missing');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.commerce','plan',$2,$3::jsonb)`,[req.session.authUserId,req.params.id,JSON.stringify({priceMinor:p.priceMinor,currency:p.currency})]);return res.redirect(`/admin/plans/${encodeURIComponent(req.params.id)}/commerce?message=${encodeURIComponent('Pricing saved.')}`)}catch(e){console.error('Plan commerce update failed:',e.message);return res.redirect(`/admin/plans/${encodeURIComponent(req.params.id)}/commerce?error=`+encodeURIComponent(e.message==='verification'?'Verification failed.':'Pricing could not be updated safely.'))}});

    r.post('/admin/plans/:id/archive',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(!(await auth.verifySecondFactor(req.session.authUserId,req.body.code,req)))throw new Error('verification');const u=await query(`UPDATE plans SET active=FALSE,visible=FALSE,updated_at=NOW() WHERE id=$1 RETURNING code,name`,[req.params.id]);if(!u.rowCount)throw new Error('missing');await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.archive','plan',$2,$3::jsonb)`,[req.session.authUserId,req.params.id,JSON.stringify({code:u.rows[0].code,name:u.rows[0].name})]);return res.redirect('/admin/plans?message='+encodeURIComponent('Plan archived. Existing subscription history was preserved.'))}catch(e){return res.redirect('/admin/plans?error='+encodeURIComponent('Plan could not be archived safely.'))}});

    r.post('/admin/plans/:id/provider',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(!(await auth.verifySecondFactor(req.session.authUserId,req.body.code,req)))throw new Error('verification');const provider=t(req.body.provider,20);if(!['stripe','paypal'].includes(provider))throw new Error('provider');const external=t(req.body.externalId,200),mode=req.body.checkoutMode==='subscription'?'subscription':'payment';await transaction(async c=>{if(external)await c.query(`INSERT INTO plan_provider_prices(plan_id,provider,external_id,checkout_mode,active) VALUES($1,$2,$3,$4,TRUE) ON CONFLICT(plan_id,provider) DO UPDATE SET external_id=EXCLUDED.external_id,checkout_mode=EXCLUDED.checkout_mode,active=TRUE,updated_at=NOW()`,[req.params.id,provider,external,mode]);else await c.query('DELETE FROM plan_provider_prices WHERE plan_id=$1 AND provider=$2',[req.params.id,provider]);await c.query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.plan.provider_mapping','plan',$2,$3::jsonb)`,[req.session.authUserId,req.params.id,JSON.stringify({provider,configured:Boolean(external),mode})])});return res.redirect(`/admin/plans/${encodeURIComponent(req.params.id)}/commerce?message=`+encodeURIComponent('Payment mapping updated.'))}catch(e){return res.redirect(`/admin/plans/${encodeURIComponent(req.params.id)}/commerce?error=`+encodeURIComponent('Payment mapping could not be updated.'))}});

    r.use('/admin/plans',(e,_q,res,_n)=>{console.error('Plans error:',e.message);return res.status(500).render('auth/message',{siteName:site(),title:'Plans unavailable',message:'Plans could not be loaded safely.',link:'/admin',linkText:'Back'})});
    return r;
}
module.exports={createAdminPlansRouter,listData,planSubnav,planById,activeSubscriberCount};
