'use strict';
const express=require('express');
const {query}=require('../db');
const runtimeSettings=require('./runtime-settings');
function requireNativeAdmin(req,res,next){if(req.session?.authUserId&&req.session?.authRole==='admin'&&req.session?.adminId)return next();return res.redirect('/login?session=expired')}
function noStore(_req,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next()}
async function userDetail(customerId){const customer=await query(`SELECT c.id,c.display_name,c.email,c.note,c.created_at,au.id AS user_id,au.username AS login_username,au.active AS login_active,au.email_verified_at,au.last_login_at FROM customers c LEFT JOIN app_users au ON au.id=c.user_id WHERE c.id=$1`,[customerId]);if(!customer.rowCount)return null;const[subscriptions,accounts,runs]=await Promise.all([query(`SELECT s.id,s.status,s.source,s.starts_at,s.current_period_end,s.cancel_at_period_end,p.code AS plan_code,p.name AS plan_name,p.streams,p.allow_downloads,p.allow_video_transcoding,p.server_class FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.customer_id=$1 ORDER BY s.created_at DESC LIMIT 25`,[customerId]),query(`SELECT ja.id,ja.jellyfin_username,ja.disabled,ja.last_activity_at,ja.last_policy_sync,js.name AS server_name,js.server_class,js.public_url,js.health_status FROM jellyfin_accounts ja JOIN jellyfin_servers js ON js.id=ja.server_id WHERE ja.customer_id=$1 ORDER BY ja.created_at ASC`,[customerId]),query(`SELECT action,status,started_at,completed_at FROM provisioning_runs WHERE customer_id=$1 ORDER BY started_at DESC LIMIT 20`,[customerId])]);return{customer:customer.rows[0],subscriptions:subscriptions.rows,accounts:accounts.rows,runs:runs.rows}}
// Customer list/detail and reconciliation now have dedicated owners. Keep this
// legacy router only as the established error boundary for /admin/users while
// callers transition away from the old admin-users module.
function createAdminUsersRouter(){const router=express.Router();router.use('/admin/users',requireNativeAdmin,noStore);router.use('/admin/users',async(error,_req,res,_next)=>{console.error('Admin users route error:',error.message);await runtimeSettings.ensureLoaded().catch(()=>{});return res.status(500).render('auth/message',{siteName:runtimeSettings.siteName(),title:'Users unavailable',message:'The users view could not be loaded safely.',link:'/admin',linkText:'Return to Administration'})});return router}
module.exports={createAdminUsersRouter,userDetail};
