'use strict';

const express=require('express');
const {query}=require('../db');
const runtimeSettings=require('./runtime-settings');
const ui=require('./admin-ui');
const {layout,esc}=require('./admin-html');
function gate(req,res,next){return req.session?.authUserId&&req.session?.authRole==='admin'&&req.session?.adminId?next():res.redirect('/login?session=expired')}
function noStore(_q,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next()}
function dt(v){return v?new Date(v).toLocaleString('en-GB'):'—'}
function clean(v,n=100){return String(v||'').trim().slice(0,n)}
function metadata(value){if(!value)return'';try{const text=typeof value==='string'?value:JSON.stringify(value);return text.length>260?text.slice(0,257)+'…':text}catch{return''}}
async function timeline({type='',q='',limit=250}={}){
 const n=Math.max(25,Math.min(500,Number(limit)||250));
 const [audit,auth,payments,incidents,provisioning,email]=await Promise.all([
  query(`SELECT created_at AS at,'audit' kind,action title,entity_type subject,entity_id::text subject_id,metadata detail FROM audit_log ORDER BY created_at DESC LIMIT $1`,[n]),
  query(`SELECT created_at AS at,'security' kind,event_type title,COALESCE(identity_hint,'user') subject,user_id::text subject_id,jsonb_build_object('success',success) detail FROM auth_events ORDER BY created_at DESC LIMIT $1`,[n]),
  query(`SELECT created_at AS at,'payment' kind,event_type title,provider subject,provider_event_id subject_id,jsonb_build_object('processedAt',processed_at,'error',processing_error) detail FROM payment_events ORDER BY created_at DESC LIMIT $1`,[n]),
  query(`SELECT created_at AS at,'incident' kind,incident_type||'.'||incident_status title,provider||' · '||scope subject,COALESCE(provider_case_id,provider_event_id) subject_id,jsonb_build_object('accessAction',access_action,'customerId',customer_id,'amountMinor',amount_minor,'currency',currency,'resolvedAt',resolved_at) detail FROM payment_incidents ORDER BY created_at DESC LIMIT $1`,[n]),
  query(`SELECT updated_at AS at,'provisioning' kind,'provisioning.'||status title,status subject,customer_id::text subject_id,jsonb_build_object('attempts',attempt_count,'failures',consecutive_failures,'lastError',last_error,'serverId',server_id,'lastResult',last_result) detail FROM customer_provisioning_state ORDER BY updated_at DESC LIMIT $1`,[n]),
  query(`SELECT COALESCE(sent_at,last_attempt_at,created_at) AS at,'email' kind,message_type title,status subject,id::text subject_id,jsonb_build_object('attempts',attempts,'error',last_error) detail FROM notification_outbox ORDER BY COALESCE(sent_at,last_attempt_at,created_at) DESC LIMIT $1`,[n])
 ]);
 let rows=[...audit.rows,...auth.rows,...payments.rows,...incidents.rows,...provisioning.rows,...email.rows].sort((a,b)=>new Date(b.at)-new Date(a.at));
 if(type)rows=rows.filter(r=>r.kind===type);
 if(q){const needle=q.toLowerCase();rows=rows.filter(r=>[r.kind,r.title,r.subject,r.subject_id,metadata(r.detail)].join(' ').toLowerCase().includes(needle));}
 return rows.slice(0,n);
}
function isActionable(row){const d=row.detail||{};if(row.kind==='security')return d.success===false;if(row.kind==='payment')return Boolean(d.error);if(row.kind==='incident')return !d.resolvedAt;if(row.kind==='provisioning')return row.subject==='failed'||Boolean(d.lastError);if(row.kind==='email')return ['failed','dead'].includes(String(row.subject||''))||Boolean(d.error);return false;}
function eventLabel(row){if(row.kind==='security')return row.detail?.success===false?'Failed sign-in / security event':'Security event';if(row.kind==='payment')return row.detail?.error?'Payment event failed':'Payment event';if(row.kind==='incident')return 'Payment incident';if(row.kind==='provisioning')return row.subject==='failed'?'Provisioning failed':'Provisioning update';if(row.kind==='email')return ['failed','dead'].includes(String(row.subject||''))?'Notification failed':'Notification event';return 'Administrative change';}
function eventDetail(row){const d=row.detail||{};if(row.kind==='security')return `${row.title} · ${row.subject||'account'}`;if(row.kind==='payment')return `${row.subject||'payment provider'} · ${row.title}${d.error?' · processing failed':''}`;if(row.kind==='incident')return `${row.subject||'payment provider'} · ${String(row.title||'incident').replaceAll('_',' ')}`;if(row.kind==='provisioning')return `${String(row.subject||'unknown').replaceAll('_',' ')}${d.lastError?' · last attempt failed':''}`;if(row.kind==='email')return `${row.title} · ${String(row.subject||'unknown').replaceAll('_',' ')}`;return `${row.title}${row.subject?' · '+row.subject:''}`;}
function sourceAction(row){if(row.kind==='incident')return['Open Commerce','/admin/commerce'];if(row.kind==='payment')return['Open Payments','/admin/payments'];if(row.kind==='provisioning')return['Open Provisioning','/admin/provisioning'];if(row.kind==='email')return['Open Notifications','/admin/notifications'];if(row.kind==='security')return['Open Security','/admin/settings?section=security'];return['View audit log','/admin/events'];}
function eventRow(row){const [label,href]=sourceAction(row);return `<div class="timelineItem"><div class="timelineTime">${esc(dt(row.at))}</div><div><div class="timelineTitle"><span class="pill ${isActionable(row)?'bad':''}">${esc(eventLabel(row))}</span> ${esc(row.title)}</div><div class="timelineDetail">${esc(eventDetail(row))}</div>${isActionable(row)?`<div style="margin-top:6px"><a class="button secondary btn-sm" href="${esc(href)}">${esc(label)}</a></div>`:''}</div></div>`;}
function auditHero(rows){const actionable=rows.filter(isActionable),security=actionable.filter(row=>row.kind==='security').length,payment=actionable.filter(row=>['payment','incident'].includes(row.kind)).length,delivery=actionable.filter(row=>['provisioning','email'].includes(row.kind)).length,first=actionable[0],action=first?sourceAction(first):null;return ui.operatorHero({tone:first?'bad':'good',eyebrow:'Audit & incident trail',title:first?`${actionable.length} recent ${actionable.length===1?'event needs':'events need'} investigation`:'No recent operational failures stand out',body:'This view combines canonical security, payments, provisioning, notification and administrator events without exposing raw identifiers or event payloads by default.',statusLabel:first?'Investigate':'Audit clear',next:first?`${eventLabel(first)} is the newest actionable event. Open its owning workflow and fix the source problem.`:'Use the audit trail when you need to trace a change or investigate historical behaviour.',facts:[{label:'Investigate',value:String(actionable.length),detail:'recent actionable events'},{label:'Security',value:String(security),detail:'failed security events'},{label:'Payments',value:String(payment),detail:'incidents or provider errors'},{label:'Delivery',value:String(delivery),detail:'provisioning or notification failures'}],actionsHtml:action?`<a class="button" href="${esc(action[1])}">${esc(action[0])}</a><a class="button secondary" href="#audit-investigate">Investigate events</a>`:'<a class="button secondary" href="#audit-history">Open audit history</a>'});}
async function page(req){await runtimeSettings.ensureLoaded();const type=clean(req.query.type,30),q=clean(req.query.q,100),allRows=await timeline({limit:250}),rows=(type||q)?await timeline({type,q,limit:250}):allRows,kinds=['','audit','security','payment','incident','provisioning','email'],actionable=allRows.filter(isActionable);const investigate=actionable.length?`<section class="section" id="audit-investigate">${ui.sectionHeader({title:'Needs investigation',description:'Failures and unresolved incidents derived from the existing event sources. Fix them in the workflow that owns the state.'})}<div class="timelineList">${actionable.slice(0,40).map(eventRow).join('')}</div></section>`:'';const filters=`<form class="formPanel" method="get" action="/admin/events"><div class="formGrid"><div class="formGroup"><label>Type</label><select class="input" name="type">${kinds.map(k=>`<option value="${esc(k)}" ${k===type?'selected':''}>${esc(k||'All events')}</option>`).join('')}</select></div><div class="formGroup"><label>Search audit history</label><input class="input" name="q" value="${esc(q)}" placeholder="Action, type or diagnostic term…"></div></div><button class="button secondary">Filter history</button></form><div class="timelineList">${rows.map(eventRow).join('')||'<div class="empty">No matching events.</div>'}</div>`;const body=`${auditHero(allRows)}${investigate}<div id="audit-history">${ui.detailDisclosure({title:`Full audit history (${rows.length})`,summary:'Routine administration, successful events and historical diagnostics',open:Boolean(type||q),bodyHtml:filters})}</div>`;return layout({siteName:runtimeSettings.siteName(),active:'events',title:'Audit log',subtitle:'Investigate failures first; trace routine system history when needed',body});}
function createAdminEventsRouter(){const r=express.Router();r.use('/admin/events',gate,noStore);r.get('/admin/events',async(req,res,next)=>{try{return res.send(await page(req))}catch(e){next(e)}});return r}
module.exports={createAdminEventsRouter,timeline,isActionable,eventLabel,eventDetail,sourceAction,auditHero};
