'use strict';
const express=require('express');
const csrf=require('../auth/csrf');
const support=require('./support-settings');
const runtimeSettings=require('./runtime-settings');
const branding=require('./branding');
const {layout,esc}=require('./admin-html');
function gate(req,res,next){return req.session?.authUserId&&req.session?.authRole==='admin'&&req.session?.adminId?next():res.redirect('/login?session=expired');}
function noStore(_q,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next();}
function external(label,url){return url?`<a class="button secondary" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:'';}
async function adminPage(req){await runtimeSettings.ensureLoaded();const s=await support.get(),body=`${req.query.message?`<div class="notice success">${esc(req.query.message)}</div>`:''}${req.query.error?`<div class="notice error">${esc(req.query.error)}</div>`:''}<section class="section"><div class="sectionHead"><div><h2>Customer-facing support & legal links</h2><div class="muted">Leave an item blank to hide it from the public Help page.</div></div></div><form class="formPanel" method="post" action="/admin/support"><input type="hidden" name="_csrf" value="${esc(csrf.token(req))}"><div class="formGrid"><div class="formGroup"><label>Support email</label><input class="input" type="email" name="supportEmail" value="${esc(s.supportEmail)}"></div><div class="formGroup"><label>Support URL / Discord / ticket portal</label><input class="input" type="url" name="supportUrl" value="${esc(s.supportUrl)}"></div><div class="formGroup"><label>Terms of service URL</label><input class="input" type="url" name="termsUrl" value="${esc(s.termsUrl)}"></div><div class="formGroup"><label>Privacy policy URL</label><input class="input" type="url" name="privacyUrl" value="${esc(s.privacyUrl)}"></div><div class="formGroup"><label>Refund policy URL</label><input class="input" type="url" name="refundUrl" value="${esc(s.refundUrl)}"></div><div class="formGroup"><label>Status page URL</label><input class="input" type="url" name="statusUrl" value="${esc(s.statusUrl)}"></div></div><button class="button">Save support links</button> <a class="button secondary" href="/help" target="_blank">Preview Help page</a></form></section>`;return layout({siteName:runtimeSettings.siteName(),active:'support',title:'Support & Legal',subtitle:'Customer help, policies and service-status links',body});}
async function publicPage(){await runtimeSettings.ensureLoaded();const s=await support.get(),site=runtimeSettings.siteName(),email=s.supportEmail?`<a class="button primary" href="mailto:${esc(s.supportEmail)}">Email support</a>`:'';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Help · ${esc(site)}</title><link rel="icon" href="${esc(branding.assetUrl('favicon'))}"><link rel="stylesheet" href="/css/customer-portal.css"><style>.help{max-width:850px;margin:auto;padding:36px 20px}.helpLinks{display:flex;flex-wrap:wrap;gap:10px}.panel{padding:20px;margin:18px 0}</style></head><body><main class="help"><a href="/">← ${esc(site)}</a><h1>Help & policies</h1><p class="accessMeta">Use the configured support channel for account, billing or streaming help. Payment-provider disputes and refunds are handled according to the published service terms.</p><section class="panel"><h2>Support</h2><div class="helpLinks">${email}${external('Open support',s.supportUrl)}${external('Service status',s.statusUrl)}</div>${!s.supportEmail&&!s.supportUrl?'<div class="empty">No public support channel has been configured yet.</div>':''}</section><section class="panel"><h2>Policies</h2><div class="helpLinks">${external('Terms of service',s.termsUrl)}${external('Privacy policy',s.privacyUrl)}${external('Refund policy',s.refundUrl)}</div>${!s.termsUrl&&!s.privacyUrl&&!s.refundUrl?'<div class="empty">No public policy links have been configured yet.</div>':''}</section></main></body></html>`;}
function createSupportRouter(){const r=express.Router();r.get('/help',async(_req,res,next)=>{try{return res.send(await publicPage());}catch(e){next(e);}});r.use('/admin/support',gate,noStore);r.get('/admin/support',async(req,res,next)=>{try{return res.send(await adminPage(req));}catch(e){next(e);}});r.post('/admin/support',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{await support.save(req.body,req.session.authUserId);return res.redirect('/admin/support?message='+encodeURIComponent('Support and legal links saved.'));}catch(e){return res.redirect('/admin/support?error='+encodeURIComponent(e.message));}});return r;}
module.exports={createSupportRouter,adminPage,publicPage};
