'use strict';
const express=require('express');
const csrf=require('../auth/csrf');
const drift=require('../jellyfin/drift-control');
const provisioning=require('../jellyfin/provisioning');
const runtimeSettings=require('./runtime-settings');
const ui=require('./admin-ui');
const {esc,layout}=require('./admin-html');
function gate(req,res,next){return req.session?.authUserId&&req.session?.authRole==='admin'&&req.session?.adminId?next():res.redirect('/login?session=expired');}
function noStore(_q,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next();}
function token(req){return `<input type="hidden" name="_csrf" value="${esc(csrf.token(req))}">`;}
function notice(req){return `${req.query.message?`<div class="notice success">${esc(req.query.message)}</div>`:''}${req.query.error?`<div class="notice error">${esc(req.query.error)}</div>`:''}`;}
function date(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('en-GB');}
function pill(label,cls=''){return `<span class="pill ${cls}">${esc(label)}</span>`;}
function statusPill(s){return s==='in_sync'?pill('Matches plan','good'):s==='drift'?pill('Different from plan','warn'):s==='missing'?pill('Account missing','bad'):s==='unreachable'?pill('Server unreachable','bad'):pill('Not checked');}
const FIELD_LABELS={Username:'Username',IsAdministrator:'Administrator',IsHidden:'Hidden user',IsDisabled:'Account disabled',EnableAllDevices:'All devices',EnableAllFolders:'All libraries',EnabledFolders:'Libraries',EnableAllChannels:'All channels',EnableRemoteAccess:'Remote access',EnableMediaPlayback:'Media playback',EnableAudioPlaybackTranscoding:'Audio transcoding',EnableVideoPlaybackTranscoding:'Video transcoding',EnablePlaybackRemuxing:'Remux / direct stream',EnableContentDownloading:'Downloads',EnableSyncTranscoding:'Sync transcoding',EnableMediaConversion:'Media conversion',EnableContentDeletion:'Content deletion',EnableRemoteControlOfOtherUsers:'Remote-control other users',EnableSharedDeviceControl:'Shared-device control',EnableLiveTvManagement:'Live TV management',EnableLiveTvAccess:'Live TV access',EnableSubtitleManagement:'Subtitle editing',EnableUserPreferenceAccess:'User preferences',SyncPlayAccess:'SyncPlay',MissingLibraries:'Missing server libraries'};
function compact(v){if(Array.isArray(v))return v.length?(v.length<=3?v.join(', '):`${v.slice(0,3).join(', ')} +${v.length-3}`):'none';if(typeof v==='boolean')return v?'on':'off';return v==null||v===''?'none':String(v);}
function differences(row){const ds=Array.isArray(row.differences)?row.differences:[];if(!ds.length)return'<span class="muted">—</span>';const summary=ds.slice(0,3).map(d=>FIELD_LABELS[d.field]||d.field).join(', ')+(ds.length>3?` +${ds.length-3}`:'');return `<details><summary>${esc(summary)}</summary><div class="driftDifferenceList">${ds.map(d=>`<div class="driftDifference"><strong>${esc(FIELD_LABELS[d.field]||d.field)}</strong><span>Expected: ${esc(compact(d.expected))}</span><span>Jellyfin: ${esc(compact(d.actual))}</span></div>`).join('')}</div></details>`;}
function repairControl(req,r){if(!['drift','missing'].includes(r.status))return'';return `<details class="driftRepair"><summary class="button secondary btn-sm">Reapply expected access…</summary><div class="driftRepairBody"><div class="subText">This can change the customer’s Jellyfin permissions. Type <strong>RECONCILE</strong> to continue.</div><form method="post" action="/admin/provisioning/drift/${esc(r.customer_id)}/reconcile">${token(req)}<input class="input" name="confirmation" autocomplete="off" placeholder="RECONCILE" required><button class="button btn-sm">Reapply expected access</button></form></div></details>`;}
function row(req,r){const identity=r.portal_username||r.display_name||r.email||'Customer',desired=r.desired_disabled===true?'<strong>Disabled</strong><div class="subText">No active entitlement on this account</div>':r.desired_disabled===false?`<strong>Enabled</strong><div class="subText">${esc(r.plan_name||'Active entitlement')}</div>`:'<span class="muted">Not evaluated</span>';return `<tr><td>${statusPill(r.status)}${r.last_error?`<div class="errorText">${esc(r.last_error)}</div>`:''}</td><td><strong>${esc(identity)}</strong><div class="subText">${esc(r.email||'CAPTAiNFiN customer')}</div></td><td><strong>${esc(r.jellyfin_username||'Account')}</strong><div class="subText">${esc(r.server_name||'Unknown server')} · ${esc(r.health_status||'unknown')}</div></td><td>${desired}</td><td>${differences(r)}</td><td>${esc(date(r.last_checked_at))}</td><td>${esc(date(r.next_check_at))}</td><td class="right"><div class="driftActions"><form method="post" action="/admin/provisioning/drift/${esc(r.jellyfin_account_id)}/audit">${token(req)}<button class="button secondary btn-sm">Check now</button></form>${repairControl(req,r)}</div></td></tr>`;}
function table(req,rows){if(!rows.length)return'<div class="empty">No managed Jellyfin accounts are in this group.</div>';return `<div class="tableWrap"><table class="dataTable driftTable"><thead><tr><th>Status</th><th>Customer</th><th>Jellyfin account</th><th>Expected access</th><th>Differences</th><th>Last checked</th><th>Next check</th><th></th></tr></thead><tbody>${rows.map(r=>row(req,r)).join('')}</tbody></table></div>`;}
function consistencyHero(stats,issues){
  const drifted=Number(stats.drift||0),missing=Number(stats.missing||0),unreachable=Number(stats.unreachable||0),unknown=Number(stats.unknown||0),inSync=Number(stats.in_sync||0),total=Number(stats.total||0);
  let tone='good',title='Managed Jellyfin access matches CAPTAiNFiN',statusLabel='In sync',next='No repair is required. Automatic checks will continue in the background.';
  if(missing||unreachable){tone='bad';title=`${missing+unreachable} managed ${missing+unreachable===1?'account needs':'accounts need'} investigation`;statusLabel='Action needed';next='Restore unreachable servers or recreate missing access before treating the customer as correctly provisioned.';}
  else if(drifted){tone='warn';title=`${drifted} managed ${drifted===1?'account differs':'accounts differ'} from the expected plan`;statusLabel='Differences found';next='Review the differences below and reapply expected access only where CAPTAiNFiN should overwrite the Jellyfin-side change.';}
  else if(unknown){tone='info';title=`${unknown} managed ${unknown===1?'account has':'accounts have'} not been checked yet`;statusLabel='Check pending';next='Run the due checks if you need confirmation now; otherwise the automation worker will check them on schedule.';}
  return ui.operatorHero({tone,eyebrow:'Access consistency',title,body:'CAPTAiNFiN compares the Jellyfin account it manages with the access the customer’s current plan expects.',statusLabel,next,facts:[
    {label:'Managed accounts',value:String(total),detail:'Jellyfin accounts owned by CAPTAiNFiN'},
    {label:'Matches plan',value:String(inSync),detail:'no managed-field differences'},
    {label:'Different',value:String(drifted),detail:'Jellyfin settings changed from expected'},
    {label:'Unavailable',value:String(missing+unreachable),detail:`${missing} missing · ${unreachable} unreachable`}
  ],actionsHtml:issues.length?'<a class="button" href="#consistency-issues">Review differences</a><a class="button secondary" href="/admin/provisioning">Provisioning</a>':'<a class="button secondary" href="#all-managed-accounts">All managed accounts</a><a class="button secondary" href="/admin/provisioning">Provisioning</a>'});
}
async function page(req){
  await runtimeSettings.ensureLoaded();
  const[rows,stats,cfg]=await Promise.all([drift.listAuditRows(),drift.stats(),drift.settings()]);
  const issues=rows.filter(r=>['drift','missing','unreachable'].includes(r.status));
  const checkActions=`<div class="driftToolbar"><form method="post" action="/admin/provisioning/drift/audit-due">${token(req)}<button class="button secondary">Check due accounts</button></form><form method="post" action="/admin/provisioning/drift/audit-all">${token(req)}<button class="button secondary">Check all managed accounts</button></form></div>`;
  const issuesHtml=issues.length?`<section class="section" id="consistency-issues">${ui.sectionHeader({eyebrow:'Current exceptions',title:'Review these accounts first',description:'Missing, unreachable and changed accounts are separated from routine in-sync checks.',actionsHtml:checkActions})}<div class="statusBanner"><strong>Checking is read-only.</strong> CAPTAiNFiN changes Jellyfin only when you deliberately choose “Reapply expected access” and type the confirmation.</div>${table(req,issues)}</section>`:`<section class="section">${ui.sectionHeader({title:'No access inconsistencies need attention',description:'All checked managed accounts match their expected state.',actionsHtml:checkActions})}<div class="empty">Nothing currently needs repair.</div></section>`;
  const allAccounts=ui.detailDisclosure({title:'All managed accounts',summary:`${rows.length} accounts including those already matching their plan`,bodyHtml:`<div id="all-managed-accounts"></div>${table(req,rows)}`});
  const cadence=ui.detailDisclosure({title:'Automatic check cadence',summary:'Advanced timing used by the automation worker',bodyHtml:`<div class="compactList"><div class="compactRow"><span>Matching account recheck</span><strong>${esc(cfg.healthyMinutes)} min</strong></div><div class="compactRow"><span>Changed account recheck</span><strong>${esc(cfg.driftMinutes)} min</strong></div><div class="compactRow"><span>Failure retry window</span><strong>${esc(cfg.failureBaseMinutes)}–${esc(cfg.failureMaxMinutes)} min</strong></div><div class="compactRow"><span>Accounts per batch</span><strong>${esc(cfg.batchSize)}</strong></div></div><div class="quick-actions" style="margin-top:12px"><a class="button secondary" href="/admin/automation">Automation jobs</a></div>`});
  const body=`${notice(req)}${consistencyHero(stats,issues)}${issuesHtml}${allAccounts}${cadence}<style>.driftTable{min-width:1400px}.driftToolbar,.driftActions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.driftToolbar form,.driftActions form,.driftRepair form{margin:0}.driftDifferenceList{display:grid;gap:8px;margin-top:8px;min-width:300px}.driftDifference{display:grid;gap:2px;padding:7px;border:1px solid #2d3743;border-radius:6px;background:#10161d}.driftDifference span,.errorText{font-size:10px}.errorText{color:#ef9298;max-width:280px}.compactList{display:grid;gap:8px}.compactRow{display:flex;justify-content:space-between;gap:18px;padding:10px 0;border-bottom:1px solid #26303a}.driftRepair{position:relative}.driftRepair>summary{list-style:none;cursor:pointer}.driftRepair>summary::-webkit-details-marker{display:none}.driftRepairBody{display:grid;gap:8px;min-width:260px;margin-top:8px;padding:10px;border:1px solid #35404c;border-radius:8px}.driftRepairBody form{display:grid;gap:8px}</style>`;
  return layout({siteName:runtimeSettings.siteName(),active:'policy-drift',title:'Access consistency',subtitle:'Find Jellyfin account settings that no longer match the customer’s CAPTAiNFiN plan',body});
}
function createAdminDriftRouter(){const r=express.Router();r.use('/admin/provisioning/drift',gate,noStore);r.get('/admin/provisioning/drift',async(req,res,next)=>{try{return res.send(await page(req));}catch(e){next(e);}});r.post('/admin/provisioning/drift/audit-due',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{const x=await drift.auditDue({all:false});return res.redirect('/admin/provisioning/drift?message='+encodeURIComponent(`Check complete: ${x.inSync} match, ${x.drift} different, ${x.missing} missing, ${x.unreachable} unreachable.`));}catch(e){return res.redirect('/admin/provisioning/drift?error='+encodeURIComponent(e.message));}});r.post('/admin/provisioning/drift/audit-all',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{const x=await drift.auditDue({all:true,limit:1000});return res.redirect('/admin/provisioning/drift?message='+encodeURIComponent(`Full check: ${x.inSync} match, ${x.drift} different, ${x.missing} missing, ${x.unreachable} unreachable.`));}catch(e){return res.redirect('/admin/provisioning/drift?error='+encodeURIComponent(e.message));}});r.post('/admin/provisioning/drift/:accountId/audit',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{const x=await drift.auditAccount(req.params.accountId);return res.redirect('/admin/provisioning/drift?message='+encodeURIComponent(`Account check: ${String(x.status).replace('_',' ')}.`));}catch(e){return res.redirect('/admin/provisioning/drift?error='+encodeURIComponent(e.message));}});r.post('/admin/provisioning/drift/:customerId/reconcile',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid security token');try{if(String(req.body.confirmation||'').trim().toUpperCase()!=='RECONCILE')throw new Error('Type RECONCILE exactly to reapply the expected Jellyfin access.');await provisioning.reconcileCustomer(req.params.customerId);await drift.clearForCustomer(req.params.customerId);return res.redirect('/admin/provisioning/drift?message='+encodeURIComponent('Expected CAPTAiNFiN access reapplied; a fresh check is queued.'));}catch(e){return res.redirect('/admin/provisioning/drift?error='+encodeURIComponent(e.message));}});return r;}
module.exports={createAdminDriftRouter,page,differences,consistencyHero,repairControl};
