'use strict';

const express=require('express');
const {customer360}=require('./customer-360');
const monthly=require('../resellers/monthly');
const runtimeSettings=require('./runtime-settings');
const {query}=require('../db');
const {esc}=require('./admin-html');
const branding=require('./branding');
function gate(req,res,next){if(req.session?.authUserId&&req.session?.authRole==='admin'&&req.session?.adminId)return next();return res.redirect('/login?session=expired')}
function pill(v,kind=''){return `<span class="pill ${kind}">${esc(v)}</span>`}
function fmtDate(v){return v?esc(new Date(v).toLocaleString('en-GB')):'—'}
function money(minor,currency='GBP'){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:String(currency||'GBP').trim(),minimumFractionDigits:2}).format(Number(minor||0)/100)}catch{return `${currency} ${(Number(minor||0)/100).toFixed(2)}`}}
function safeUrl(v){try{const u=new URL(String(v||''));return['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function shell({title,subtitle,back,body}){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${esc(title)} · Admin preview</title><link rel="icon" href="${esc(branding.assetUrl('favicon'))}"><link rel="stylesheet" href="/css/admin-original-base.css"><link rel="stylesheet" href="/css/admin-original-components.css"><link rel="stylesheet" href="/css/customer-360.css"><style>body{margin:0;background:#0c1117;color:#d9e0e8}.previewBanner{position:sticky;top:0;z-index:200;background:#5a3b08;color:#fff3c4;border-bottom:1px solid #8d6214;padding:10px 16px;display:flex;align-items:center;justify-content:space-between;gap:12px}.previewWrap{max-width:1180px;margin:auto;padding:24px 18px 60px}.previewHeader{display:flex;align-items:center;gap:12px;margin-bottom:22px}.previewLogo{width:38px;height:38px;border-radius:9px;object-fit:cover}.previewGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.previewCard{background:#121922;border:1px solid #26303d;border-radius:12px;padding:16px}.previewCard h3{margin:0 0 8px}.previewStat{font-size:26px;font-weight:800}.previewList{display:grid;gap:10px}.previewRow{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid #222b36}.previewRow:last-child{border-bottom:0}.previewNote{background:#18212c;border:1px dashed #425065;border-radius:10px;padding:12px;color:#9da9b8}.meter{height:8px;border-radius:20px;background:#222a34;overflow:hidden;margin-top:8px}.meter span{display:block;height:100%;background:#20a9d6}@media(max-width:620px){.previewBanner{align-items:flex-start;flex-direction:column}.previewWrap{padding:18px 12px 46px}}</style></head><body><div class="previewBanner"><div><strong>ADMIN PREVIEW — READ ONLY</strong><div style="font-size:12px;opacity:.85">Safe rendering of the portal. Account-changing actions are disabled.</div></div><a class="button secondary btn-sm" href="${esc(back)}">Exit preview</a></div><main class="previewWrap"><header class="previewHeader"><img class="previewLogo" src="${esc(branding.assetUrl('logo'))}" alt=""><div><h1 style="margin:0 0 3px">${esc(title)}</h1><div class="muted">${esc(subtitle)}</div></div></header>${body}</main></body></html>`}
function customerBody(d){const c=d.customer,current=d.subscriptions.find(x=>['active','trialing','past_due','paused'].includes(x.status)&&(!x.current_period_end||new Date(x.current_period_end)>new Date()))||d.subscriptions[0],account=d.accounts[0],url=safeUrl(account?.public_url);return `<div class="previewGrid"><section class="previewCard"><h3>My subscription</h3>${current?`<div class="previewStat">${esc(current.plan_name)}</div><p>${pill(current.status,current.status==='active'?'good':'')} ${pill(`${current.streams} stream${Number(current.streams)===1?'':'s'}`)}</p><div class="muted">Access until ${fmtDate(current.current_period_end)}</div>`:'<div class="muted">No active subscription.</div>'}</section><section class="previewCard"><h3>Jellyfin access</h3>${account?`<div class="previewStat" style="font-size:18px">${esc(account.jellyfin_username)}</div><p>${pill(account.disabled?'Disabled':'Enabled',account.disabled?'bad':'good')}</p><div class="muted">${esc(account.server_name)}</div>${url?`<p><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Open Jellyfin</a></p>`:''}`:'<div class="muted">No Jellyfin account yet.</div>'}</section><section class="previewCard"><h3>Activity</h3><div class="previewStat">${esc(d.activeStreams.length)}</div><div class="muted">active streams now</div><p>${esc(d.activitySummary.sessions_30d||0)} sessions / 30d</p></section><section class="previewCard"><h3>Billing</h3><div class="previewStat" style="font-size:18px">${esc(d.paymentCustomers.map(x=>x.provider).join(', ')||'No provider')}</div><div class="muted">${current?.cancel_at_period_end?'Cancels at period end':'Managed subscription status'}</div></section></div><section class="previewCard" style="margin-top:14px"><h3>Account settings</h3><div class="previewList"><div class="previewRow"><span>Login username</span><strong>${esc(c.login_username||'—')}</strong></div><div class="previewRow"><span>Email</span><strong>${esc(c.login_email||c.email||'—')}</strong></div></div><div class="previewNote" style="margin-top:14px">Password, billing and plan-changing controls are disabled in admin preview.</div></section>`}
async function resellerData(id){const r=await query(`SELECT r.*,u.username,u.email,u.active FROM resellers r JOIN app_users u ON u.id=r.user_id WHERE r.id=$1`,[id]);if(!r.rowCount)return null;const [sub,seats,customers,analytics,streams]=await Promise.all([monthly.currentSubscription(id),monthly.seatUsage(id),monthly.listManagedCustomers(id),monthly.salesAnalytics(id,{from:new Date(Date.now()-30*86400000),to:new Date()}),query(`SELECT COUNT(DISTINCT aps.jellyfin_session_id)::int n FROM active_playback_sessions aps JOIN customers c ON c.id=aps.customer_id WHERE c.reseller_id=$1`,[id])]);return{reseller:r.rows[0],sub,seats,customers,analytics,streams:Number(streams.rows[0]?.n||0)}}
function resellerBody(d){const r=d.reseller,s=d.sub,limit=Number(s?.seat_limit||0),pct=limit?Math.min(100,Math.round(Number(d.seats||0)/limit*100)):0,revenue=(d.analytics.totals||[]).map(x=>money(x.amount_minor,x.currency)).join(' + ')||'—';return `<div class="previewGrid"><section class="previewCard"><h3>Monthly tier</h3><div class="previewStat">${esc(s?.tier_name||'No active tier')}</div><div class="muted">${s?`${money(s.monthly_price_minor,s.currency)} / month · ${esc(s.status)}`:'No parent billing entitlement'}</div></section><section class="previewCard"><h3>Active entitlements</h3><div class="previewStat">${esc(d.seats)}${limit?` / ${esc(limit)}`:''}</div><div class="meter"><span style="width:${pct}%"></span></div><div class="muted">Seat = active customer entitlement</div></section><section class="previewCard"><h3>Downstream revenue / 30d</h3><div class="previewStat" style="font-size:20px">${esc(revenue)}</div><div class="muted">Reseller-reported; separate from CAPTAiNFiN revenue</div></section><section class="previewCard"><h3>Streams now</h3><div class="previewStat">${esc(d.streams)}</div><div class="muted">across child customers</div></section></div><section class="previewCard" style="margin-top:14px"><h3>Parent billing</h3><div class="previewList"><div class="previewRow"><span>Status</span><strong>${esc(s?.status||'None')}</strong></div><div class="previewRow"><span>Paid through</span><strong>${fmtDate(s?.current_period_end)}</strong></div><div class="previewRow"><span>Renewal</span><strong>${s?.cancel_at_period_end?'Stops at period end':'On / manual'}</strong></div><div class="previewRow"><span>Portal login</span><strong>${r.active?'Enabled':'Disabled'}</strong></div><div class="previewRow"><span>Estate hold</span><strong>${r.estate_suspended_at?'Suspended':'Clear'}</strong></div></div></section><section class="previewCard" style="margin-top:14px"><h3>Customers</h3>${d.customers.length?`<div class="previewList">${d.customers.slice(0,12).map(x=>`<div class="previewRow"><div><strong>${esc(x.display_name||x.jellyfin_username||'Customer')}</strong>${x.is_reseller_owner?'<div class="muted">Reseller own account</div>':`<div class="muted">${esc(x.plan_name||'No plan')}</div>`}</div><div style="text-align:right">${pill(x.access_paused_at?'Suspended':x.sub_status||'No plan',x.access_paused_at?'bad':x.sub_status?'good':'warn')}<div class="muted">${fmtDate(x.current_period_end)}</div></div></div>`).join('')}</div>`:'<div class="muted">No customers yet.</div>'}<div class="previewNote" style="margin-top:14px">Customer creation, renewal, suspension, credentials and billing actions are disabled in preview.</div></section>`}
function createAdminPreviewRouter(){const r=express.Router();r.use('/admin/preview',gate);r.get('/admin/preview/customer/:id',async(req,res,next)=>{try{await runtimeSettings.ensureLoaded();const d=await customer360(req.params.id);if(!d)return res.status(404).send('Customer not found');res.setHeader('Cache-Control','no-store, private, max-age=0');return res.send(shell({title:runtimeSettings.siteName(),subtitle:`Customer portal · ${d.customer.login_username||d.customer.display_name||d.customer.login_email||'Customer'}`,back:`/admin/users/${encodeURIComponent(req.params.id)}`,body:customerBody(d)}))}catch(e){next(e)}});r.get('/admin/preview/reseller/:id',async(req,res,next)=>{try{await runtimeSettings.ensureLoaded();const d=await resellerData(req.params.id);if(!d)return res.status(404).send('Reseller not found');res.setHeader('Cache-Control','no-store, private, max-age=0');return res.send(shell({title:runtimeSettings.siteName(),subtitle:`Reseller portal · ${d.reseller.username}`,back:`/admin/reseller-management/${encodeURIComponent(req.params.id)}`,body:resellerBody(d)}))}catch(e){next(e)}});return r}
module.exports={createAdminPreviewRouter,resellerData};
