'use strict';
const express=require('express');
const runtimeSettings=require('./runtime-settings');
const operations=require('./operations-settings');
const emailSettings=require('../integrations/email-settings');
const emailOutbox=require('../integrations/email-outbox');
const emailChange=require('../security/customer-email-change');
const csrf=require('../auth/csrf');
function safeNext(value){const next=String(value||'');return next.startsWith('/')&&!next.startsWith('//')?next:'/account'}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function save(req){return new Promise((resolve,reject)=>req.session.save(e=>e?reject(e):resolve()));}
function requireCustomer(req,res,next){return req.session?.customerId&&req.session?.customerUserId?next():res.redirect('/account/login?next='+encodeURIComponent(req.originalUrl||'/account'))}
function confirmationPage(req,{displayName,email,error=null}){const site=runtimeSettings.siteName();return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Confirm email change · ${esc(site)}</title><link rel="stylesheet" href="/css/customer-portal.css"><style>main{max-width:620px;margin:40px auto;padding:22px}.panel{padding:20px}.field{margin:14px 0}</style></head><body><main><p><a href="/account/security">← Account security</a></p><section class="panel"><h1>Confirm email change</h1><p>Changing the account email also changes where password-reset messages are delivered. Enter your current portal password to approve the change to <strong>${esc(email)}</strong>.</p>${error?`<div class="notice error">${esc(error)}</div>`:''}<form method="post" action="/account/security/profile"><input type="hidden" name="_csrf" value="${esc(csrf.token(req))}"><input type="hidden" name="displayName" value="${esc(displayName)}"><input type="hidden" name="email" value="${esc(email)}"><div class="field"><label>Current portal password</label><input class="input" type="password" name="currentPassword" autocomplete="current-password" required autofocus></div><button class="button primary">Confirm email change</button></form></section></main></body></html>`;}
async function processProfile(req,res){try{await runtimeSettings.ensureLoaded();const current=await emailChange.identity(req.session.customerId,req.session.customerUserId),displayName=String(req.body.displayName||'').trim(),email=emailChange.cleanEmail(req.body.email),changed=String(current.email||'').toLowerCase()!==email;if(changed&&!String(req.body.currentPassword||''))return res.status(200).send(confirmationPage(req,{displayName,email}));const requireVerification=runtimeSettings.requireEmailVerification();if(changed&&requireVerification){const mail=await emailSettings.status();if(!mail.configured)throw new Error('Email verification is required, but transactional email is not configured.');}const out=await emailChange.begin({customerId:req.session.customerId,userId:req.session.customerUserId,displayName,email,currentPassword:req.body.currentPassword,requireVerification,currentSessionId:req.sessionID});if(!out.changed)return res.redirect('/account/security?message='+encodeURIComponent('Profile updated.'));if(out.pending){const site=runtimeSettings.siteName(),url=await operations.absoluteUrl(req,`/account/verify-email-change?token=${encodeURIComponent(out.token)}`);await emailOutbox.enqueue({type:'email_change_verification',to:out.email,subject:`Confirm your ${site} email change`,text:`Confirm that this should become the email address for your ${site} account: ${url}\n\nThis link expires in 24 hours. If you did not request this change, do not use the link.`,html:`<p>Confirm that <strong>${esc(out.email)}</strong> should become the email address for your ${esc(site)} account.</p><p><a href="${esc(url)}">Confirm email change</a></p><p>This link expires in 24 hours. If you did not request this change, ignore this message.</p>`,dedupeKey:`email-change:${req.session.customerUserId}:${out.expiresAt.toISOString()}`});return res.redirect('/account/security?message='+encodeURIComponent(`Profile saved. Check ${out.email} to confirm the email change; your current email remains authoritative until then.`));}if(out.sessionVersion){req.session.customerSessionVersion=out.sessionVersion;await save(req);}return res.redirect('/account/security?message='+encodeURIComponent(`Email changed. ${out.revokedSessions||0} other session(s) were signed out.`));}catch(error){const displayName=String(req.body.displayName||'').trim(),email=String(req.body.email||'').trim();if(String(req.body.currentPassword||''))return res.status(400).send(confirmationPage(req,{displayName,email,error:error.message}));return res.redirect('/account/security?error='+encodeURIComponent(error.message));}}
function createCustomerLoginRouter(){const r=express.Router();r.get('/account/login',async(req,res,next)=>{try{await runtimeSettings.ensureLoaded();return res.render('customer/login',{error:null,message:req.query.session==='expired'?'Your session expired. Sign in again.':null,next:safeNext(req.query.next),csrfToken:csrf.token(req),siteName:runtimeSettings.siteName()})}catch(e){next(e)}});
 // This route intentionally precedes customer-security's historical profile
 // handler. It stages identity changes instead of replacing the reset address
 // from a merely-authenticated (possibly stolen) session.
 r.post('/account/security/profile',requireCustomer,(req,res,next)=>{if(!csrf.verify(req))return res.status(403).send('Invalid or expired security token');processProfile(req,res).catch(next)});
 r.get('/account/verify-email-change',async(req,res,next)=>{try{await runtimeSettings.ensureLoaded();const changed=await emailChange.complete(req.query.token);return res.status(changed?200:400).render('customer/message',{title:changed?'Email changed':'Email change failed',message:changed?'Your new email address is verified. For security, all existing sessions were signed out; sign in again with the updated address.':'This email-change link is invalid, expired, already used or no longer matches the pending change.',siteName:runtimeSettings.siteName()});}catch(error){next(error)}});
 // The old dashboard still contains a legacy password form. Never accept its
 // password without the current credential; direct the customer to the fully
 // protected Security workflow instead of leaving a 404 or weakening policy.
 r.post('/account/password',requireCustomer,(req,res)=>res.redirect('/account/security?error='+encodeURIComponent('Use Account Security to change your portal password; your current password is required.')));
 return r}
module.exports={createCustomerLoginRouter,safeNext,processProfile,confirmationPage};
