'use strict';
const express=require('express');
const {query}=require('../db');
const runtimeSettings=require('./runtime-settings');
const branding=require('./branding');
const customerNav=require('./customer-nav-html');
const {esc}=require('./admin-html');
function requireCustomer(req,res,next){return req.session?.customerId&&req.session?.customerUserId?next():res.redirect('/account/login?next='+encodeURIComponent(req.originalUrl||'/account/history'))}
function noStore(_q,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next()}
function dt(v){return v?new Date(v).toLocaleString('en-GB'):'—'}
function money(minor,currency='GBP'){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:String(currency||'GBP').trim(),currencyDisplay:'narrowSymbol',minimumFractionDigits:2}).format(Number(minor||0)/100)}catch{return `${currency} ${(Number(minor||0)/100).toFixed(2)}`}}
function statusLabel(value){return({active:'Active',trialing:'Trial',past_due:'Payment needs attention',paused:'Paused',cancelled:'Cancelled',expired:'Ended',pending:'Pending',applied:'Completed',failed:'Needs attention',cancelled_change:'Cancelled'})[String(value||'')]||String(value||'Unknown').replaceAll('_',' ')}
function billingLabel(value){return({stripe:'Stripe',paypal:'PayPal',manual:'Manual',service_credit:'Service credit',trial:'Trial',free:'Free Access',migration:'Imported history',admin:'Administrator'})[String(value||'')]||String(value||'Account')}
function changeMode(value){return String(value)==='period_end'?'Next renewal':String(value)==='immediate'?'Immediate':'Scheduled'}
function shell(site,body,navOptions){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Billing history · ${esc(site)}</title><link rel="icon" href="${esc(branding.assetUrl('favicon'))}"><link rel="stylesheet" href="/css/customer-portal.css"><link rel="stylesheet" href="/css/customer-navigation.css"><style>.historyTable{width:100%;border-collapse:collapse;min-width:760px}.historyTable th,.historyTable td{text-align:left;padding:10px;border-bottom:1px solid #26303a;vertical-align:top}.historyTable th{color:#8390a2;font-size:12px}.historySection{margin:18px 0}.historySection h2{margin:0 0 10px}.historyCard{background:#121922;border:1px solid #26303d;border-radius:12px;padding:16px;overflow:auto}</style></head><body><main class="customerPortalPage">${customerNav.nav('history',navOptions)}<header class="customerPortalPageHeader"><div><h1>Billing history</h1><p>Your plans, renewal dates and completed or scheduled plan changes.</p></div><a class="button secondary" href="/account#plans">Plans & billing</a></header>${body}</main></body></html>`}
async function history(customerId){const[subscriptions,changes]=await Promise.all([query(`SELECT s.id,s.status,s.source,s.starts_at,s.current_period_end,s.cancel_at_period_end,s.created_at,s.updated_at,s.superseded_by,s.replaced_at,s.replacement_reason,COALESCE(s.plan_name_snapshot,p.name) plan_name,COALESCE(s.plan_code_snapshot,p.code) plan_code,COALESCE(s.price_minor_snapshot,p.price_minor) price_minor,COALESCE(s.currency_snapshot,p.currency) currency,COALESCE(s.billing_interval_snapshot,p.billing_interval) billing_interval,COALESCE(s.duration_days_snapshot,p.duration_days) duration_days FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.customer_id=$1 ORDER BY s.created_at DESC,s.current_period_end DESC`,[customerId]),query(`SELECT pc.*,p.name target_plan_name,p.code target_plan_code FROM customer_plan_changes pc JOIN plans p ON p.id=pc.target_plan_id WHERE pc.customer_id=$1 ORDER BY pc.created_at DESC LIMIT 100`,[customerId])]);return{subscriptions:subscriptions.rows,changes:changes.rows}}
async function page(req){await runtimeSettings.ensureLoaded();const [data,navOptions]=await Promise.all([history(req.session.customerId),customerNav.optionsForCustomer(req.session.customerId)]);const subs=data.subscriptions.length?`<div class="historyCard"><table class="historyTable"><thead><tr><th>Plan</th><th>Status</th><th>Access period</th><th>Payment</th></tr></thead><tbody>${data.subscriptions.map(s=>`<tr><td><strong>${esc(s.plan_name)}</strong><div class="accessMeta">${esc(money(s.price_minor,s.currency))} · ${esc(String(s.billing_interval||'access').replaceAll('_',' '))}</div></td><td><span class="pill ${['active','trialing'].includes(s.status)?'good':s.status==='past_due'?'warn':''}">${esc(statusLabel(s.status))}</span>${s.superseded_by?'<div class="accessMeta">Replaced by a newer plan</div>':''}</td><td>${esc(dt(s.starts_at))}<div class="accessMeta">until ${esc(dt(s.current_period_end))}</div></td><td>${esc(billingLabel(s.source))}<div class="accessMeta">${s.cancel_at_period_end?'Renewal will stop':'No cancellation scheduled'}</div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No billing history yet.</div>';const changes=data.changes.length?`<div class="historyCard"><table class="historyTable"><thead><tr><th>Requested</th><th>New plan</th><th>When it changes</th><th>Status</th></tr></thead><tbody>${data.changes.map(c=>`<tr><td>${esc(dt(c.created_at))}</td><td><strong>${esc(c.target_plan_name)}</strong></td><td>${esc(changeMode(c.mode))}${c.effective_at?`<div class="accessMeta">${esc(dt(c.effective_at))}</div>`:''}</td><td><span class="pill ${c.state==='applied'?'good':c.state==='failed'?'warn':''}">${esc(statusLabel(c.state))}</span>${c.error?'<div class="accessMeta">This change needs support attention.</div>':''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No plan changes recorded.</div>';return shell(runtimeSettings.siteName(),`<section class="historySection"><h2>Plans and payments</h2>${subs}</section><section class="historySection"><h2>Plan changes</h2>${changes}</section>`,navOptions)}
function createCustomerHistoryRouter(){const r=express.Router();r.use('/account/history',requireCustomer,noStore);r.get('/account/history',async(req,res,next)=>{try{return res.send(await page(req))}catch(e){next(e)}});return r}
module.exports={createCustomerHistoryRouter,history,page,statusLabel,billingLabel,changeMode};
