'use strict';
const express=require('express');
const {query}=require('../db');
const runtimeSettings=require('./runtime-settings');
const branding=require('./branding');
const {esc}=require('./admin-html');
function requireCustomer(req,res,next){return req.session?.customerId&&req.session?.customerUserId?next():res.redirect('/account/login?next='+encodeURIComponent(req.originalUrl||'/account/history'))}
function noStore(_q,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next()}
function dt(v){return v?new Date(v).toLocaleString('en-GB'):'—'}
function money(minor,currency='GBP'){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:String(currency||'GBP').trim(),minimumFractionDigits:2}).format(Number(minor||0)/100)}catch{return `${currency} ${(Number(minor||0)/100).toFixed(2)}`}}
function shell(site,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Billing history · ${esc(site)}</title><link rel="icon" href="${esc(branding.assetUrl('favicon'))}"><link rel="stylesheet" href="/css/customer-portal.css"><style>.historyMain{max-width:1180px;margin:auto;padding:28px 18px 60px}.historyTop{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-bottom:20px}.historyTable{width:100%;border-collapse:collapse}.historyTable th,.historyTable td{text-align:left;padding:10px;border-bottom:1px solid #26303a;vertical-align:top}.historyTable th{color:#8390a2;font-size:12px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;word-break:break-all}.historySection{margin:18px 0}.historySection h2{margin:0 0 10px}.historyCard{background:#121922;border:1px solid #26303d;border-radius:12px;padding:16px;overflow:auto}@media(max-width:720px){.historyTop{align-items:flex-start;flex-direction:column}.historyTable{min-width:760px}}</style></head><body><main class="historyMain"><header class="historyTop"><div><div class="eyebrow">Your account</div><h1>Subscription & payment history</h1><p class="accessMeta">Entitlements, provider references, renewal state and payment-provider events kept by ${esc(site)}.</p></div><a class="button secondary" href="/account">Back to account</a></header>${body}</main></body></html>`}
async function history(customerId){const[subscriptions,changes,events]=await Promise.all([query(`SELECT s.id,s.status,s.source,s.starts_at,s.current_period_end,s.cancel_at_period_end,s.provider_customer_id,s.provider_subscription_id,s.created_at,s.updated_at,s.superseded_by,s.replaced_at,s.replacement_reason,p.name plan_name,p.code plan_code,p.price_minor,p.currency,p.billing_interval FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.customer_id=$1 ORDER BY s.created_at DESC,s.current_period_end DESC`,[customerId]),query(`SELECT pc.*,p.name target_plan_name,p.code target_plan_code FROM customer_plan_changes pc JOIN plans p ON p.id=pc.target_plan_id WHERE pc.customer_id=$1 ORDER BY pc.created_at DESC LIMIT 100`,[customerId]),query(`SELECT DISTINCT pe.provider,pe.provider_event_id,pe.event_type,pe.processed_at,pe.processing_error,pe.created_at FROM payment_events pe WHERE EXISTS(SELECT 1 FROM subscriptions s WHERE s.customer_id=$1 AND ((s.provider_subscription_id IS NOT NULL AND pe.payload::text LIKE '%'||s.provider_subscription_id||'%') OR (s.provider_customer_id IS NOT NULL AND pe.payload::text LIKE '%'||s.provider_customer_id||'%'))) ORDER BY pe.created_at DESC LIMIT 250`,[customerId])]);return{subscriptions:subscriptions.rows,changes:changes.rows,events:events.rows}}
async function page(req){await runtimeSettings.ensureLoaded();const data=await history(req.session.customerId);const subs=data.subscriptions.length?`<div class="historyCard"><table class="historyTable"><thead><tr><th>Plan</th><th>Status</th><th>Period</th><th>Billing</th><th>Provider reference</th></tr></thead><tbody>${data.subscriptions.map(s=>`<tr><td><strong>${esc(s.plan_name)}</strong><div class="accessMeta">${esc(money(s.price_minor,s.currency))} · ${esc(s.billing_interval)}</div></td><td><span class="pill ${['active','trialing'].includes(s.status)?'good':s.status==='past_due'?'warn':''}">${esc(s.status)}</span>${s.superseded_by?'<div class="accessMeta">Replaced</div>':''}</td><td>${esc(dt(s.starts_at))}<div class="accessMeta">to ${esc(dt(s.current_period_end))}</div></td><td>${esc(s.source)}<div class="accessMeta">${s.cancel_at_period_end?'Renewal stops at period end':'Renewal state unchanged'}</div></td><td class="mono">${esc(s.provider_subscription_id||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No subscription history yet.</div>';const changes=data.changes.length?`<div class="historyCard"><table class="historyTable"><thead><tr><th>Requested</th><th>Target plan</th><th>Mode</th><th>Effective</th><th>Status</th></tr></thead><tbody>${data.changes.map(c=>`<tr><td>${esc(dt(c.created_at))}</td><td><strong>${esc(c.target_plan_name)}</strong></td><td>${esc(c.mode)}<div class="accessMeta">${esc(c.provider||'manual')}</div></td><td>${esc(dt(c.effective_at))}</td><td>${esc(c.state)}${c.error?`<div class="accessMeta">${esc(c.error)}</div>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No plan changes recorded.</div>';const events=data.events.length?`<div class="historyCard"><table class="historyTable"><thead><tr><th>When</th><th>Provider</th><th>Event</th><th>Status</th><th>Reference</th></tr></thead><tbody>${data.events.map(e=>`<tr><td>${esc(dt(e.created_at))}</td><td>${esc(e.provider)}</td><td>${esc(e.event_type)}</td><td>${e.processing_error?'<span class="pill warn">Needs review</span>':e.processed_at?'<span class="pill good">Processed</span>':'<span class="pill">Pending</span>'}${e.processing_error?`<div class="accessMeta">${esc(e.processing_error)}</div>`:''}</td><td class="mono">${esc(e.provider_event_id)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No matching provider events are stored for this account.</div>';return shell(runtimeSettings.siteName(),`<section class="historySection"><h2>Subscriptions</h2>${subs}</section><section class="historySection"><h2>Plan changes</h2>${changes}</section><section class="historySection"><h2>Payment-provider events</h2>${events}</section>`)}
function createCustomerHistoryRouter(){const r=express.Router();r.use('/account/history',requireCustomer,noStore);r.get('/account/history',async(req,res,next)=>{try{return res.send(await page(req))}catch(e){next(e)}});return r}
module.exports={createCustomerHistoryRouter,history,page};
