'use strict';
const express=require('express');
const csrf=require('../auth/csrf');
const catalog=require('../requests/media-catalog');
const arr=require('../requests/arr-registry');
const {layout,esc}=require('./admin-html');
function site(){return process.env.SITE_NAME||'CAPTAiNFiN'}
function gate(req,res,next){if(req.session?.authUserId&&req.session?.authRole==='admin'&&req.session?.adminId)return next();return res.redirect('/login?session=expired')}
function pill(v,k=''){return `<span class="pill ${k}">${esc(v)}</span>`}
function nav(active){return `<nav class="detailTabs"><a class="detailTab ${active==='queue'?'active':''}" href="/admin/requests">Queue</a><a class="detailTab ${active==='instances'?'active':''}" href="/admin/requests/instances">Instances</a><a class="detailTab ${active==='routing'?'active':''}" href="/admin/requests/routing">Quality Routing</a></nav>`}
function send(res,o){res.setHeader('Cache-Control','no-store, private, max-age=0');return res.send(layout({siteName:site(),active:'requests',title:'Requests',subtitle:'Media discovery, approval and quality routing',...o}))}
function queueBody(rows){return `${nav('queue')}<section class="section"><div class="sectionHead"><h2>Queue</h2><span class="muted">${rows.length} shown</span></div>${rows.length?`<div class="tableWrap"><table class="dataTable responsiveTable"><thead><tr><th>Media</th><th>Requester</th><th>Quality</th><th>Status</th><th>Target</th><th>Created</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td data-label="Media"><strong>${esc(x.title||'Untitled')}</strong><div class="subText">${esc(x.media_type)}${x.year?' · '+esc(x.year):''}</div></td><td data-label="Requester">${esc(x.customer_name||x.reseller_username||'Unknown')}</td><td data-label="Quality">${esc(x.quality_name||'—')}</td><td data-label="Status">${pill(x.status,['available','approved','added'].includes(x.status)?'good':x.status==='failed'?'bad':'warn')}</td><td data-label="Target">${esc(x.instance_name||'Not routed')}</td><td data-label="Created">${x.created_at?esc(new Date(x.created_at).toLocaleString()):'—'}</td><td data-label=""><a class="button secondary btn-sm" href="/admin/requests/${encodeURIComponent(x.id)}">Details</a></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No media requests yet.</div>'}</section>`}
async function instanceBody(){const rows=await arr.list();return `${nav('instances')}<section class="section"><div class="sectionHead"><h2>Arr instances</h2><a class="button" href="/admin/requests/instances/new">Add instance</a></div>${rows.length?`<div class="serverGrid">${rows.map(x=>`<div class="serverCard"><div class="serverTop"><div><strong>${esc(x.name)}</strong><div class="subText">${esc(x.kind)} · ${esc(x.base_url)}</div></div>${pill(x.health_status,x.health_status==='healthy'?'good':x.health_status==='offline'?'bad':'warn')}</div><div class="serverStats"><div><span class="metricMini">${esc(x.version||'—')}</span><span class="subText">version</span></div><div><span class="metricMini">${x.last_health_check?esc(new Date(x.last_health_check).toLocaleDateString()):'never'}</span><span class="subText">last check</span></div></div><div class="cardActions"><a class="button secondary" href="/admin/requests/instances/${encodeURIComponent(x.id)}">Manage</a></div></div>`).join('')}</div>`:'<div class="empty">No Radarr or Sonarr instances configured.</div>'}</section><div class="securityNote">API keys are write-only and encrypted. They are never rendered back to the browser.</div>`}
async function routingBody(){const [tiers,routes]=await Promise.all([catalog.tiers(),catalog.routes()]);return `${nav('routing')}<section class="section"><div class="sectionHead"><h2>Quality tiers</h2><a class="button" href="/admin/requests/routing/new">Add tier</a></div>${tiers.length?`<div class="tableWrap"><table class="dataTable responsiveTable"><thead><tr><th>Quality</th><th>Movie route</th><th>TV route</th><th>Status</th><th></th></tr></thead><tbody>${tiers.map(t=>{const movie=routes.find(r=>String(r.quality_tier_id)===String(t.id)&&r.media_type==='movie'),tv=routes.find(r=>String(r.quality_tier_id)===String(t.id)&&r.media_type==='series');const fmt=r=>r?`${esc(r.instance_name)}<div class="subText">${esc(r.quality_profile_name)} · ${esc(r.root_folder_path)}${r.search_on_add?' · search on add':''}</div>`:'Not configured';return `<tr><td data-label="Quality"><strong>${esc(t.name)}</strong><div class="subText">${esc(t.code)}</div></td><td data-label="Movies">${fmt(movie)}</td><td data-label="TV">${fmt(tv)}</td><td data-label="Status">${pill(t.active?'Active':'Disabled',t.active?'good':'bad')}</td><td data-label=""><a class="button secondary btn-sm" href="/admin/requests/routing/${encodeURIComponent(t.id)}">Manage</a></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No quality tiers configured.</div>'}</section><div class="securityNote">Search on add is off unless explicitly enabled on a route.</div>`}
function createMediaCenterRouter(){const r=express.Router();r.use('/admin/requests',gate);r.get('/admin/requests',async(_q,res,next)=>{try{return send(res,{body:queueBody(await catalog.queue())})}catch(e){next(e)}});r.get('/admin/requests/instances',async(_q,res,next)=>{try{return send(res,{body:await instanceBody()})}catch(e){next(e)}});r.get('/admin/requests/routing',async(_q,res,next)=>{try{return send(res,{body:await routingBody()})}catch(e){next(e)}});return r}
module.exports={createMediaCenterRouter};
