'use strict';
const express=require('express');
const runtimeSettings=require('./runtime-settings');
const supportPolicy=require('./support-policy');
const branding=require('./branding');
const {esc}=require('./admin-html');

function contactLink(label,url){return url?`<a class="infoAction" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:''}
function infoShell(site,title,subtitle,body){
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${esc(title)} · ${esc(site)}</title><link rel="icon" href="${esc(branding.assetUrl('favicon'))}"><link rel="stylesheet" href="/css/storefront.css"><link rel="stylesheet" href="/css/storefront-refinement.css"><link rel="stylesheet" href="/css/public-info-pages.css"></head><body><div class="siteBackdrop" aria-hidden="true"><div class="backdropGlow glowA"></div><div class="backdropGlow glowB"></div><div class="backdropGrid"></div></div><header class="storeHeader"><div class="storeWrap headerInner"><a class="storeBrand" href="/"><img src="${esc(branding.assetUrl('logo'))}" alt=""><span>${esc(site)}</span></a><nav class="storeNav" aria-label="Public navigation"><a href="/about">About</a><a href="/faq">FAQ</a><a href="/contact">Contact</a><a href="/trust">Trust</a></nav><div class="headerActions"><a class="storeBtn ghost" href="/account/login">Sign in</a></div></div></header><main class="infoMain"><section class="storeWrap infoHero"><div class="heroEyebrow"><span class="liveDot"></span>CAPTAiNFiN information</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></section>${body}</main><footer class="storeFooter"><div class="storeWrap footerBottom"><span>© ${new Date().getFullYear()} ${esc(site)}</span><span class="infoFooterLinks"><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/refund-policy">Refund policy</a></span></div></footer></body></html>`;
}
function card(title,copy){return `<article class="infoCard"><h2>${esc(title)}</h2><p>${esc(copy)}</p></article>`}
async function baseData(){await runtimeSettings.ensureLoaded();return{site:runtimeSettings.siteName(),support:await supportPolicy.get().catch(()=>({}))}}
function createPublicPagesRouter(){
  const router=express.Router();
  router.get('/about',async(_req,res,next)=>{try{const{site}=await baseData();return res.send(infoShell(site,'About CAPTAiNFiN','A private access portal for managing streaming membership, customer accounts and support in one place.',`<section class="storeWrap infoGrid">${card('Built for simple access','CAPTAiNFiN gives customers one account for plans, Jellyfin access, Stremio setup, security and support.')}${card('Clear operations','The administration area tracks customers, servers, commerce, automation and attention items from a single control centre.')}${card('Professional by design','The interface keeps billing, access and server-health decisions visible without exposing raw secrets or unnecessary internal identifiers.')}</section>`));}catch(error){next(error);}});
  router.get('/faq',async(_req,res,next)=>{try{const{site,support}=await baseData(),supportEmail=support.supportEmail||'';const faqs=[['How do I start?','Create or sign in to your customer account, choose an available plan, then follow the access setup shown in your portal.'],['Why can I not sign in to Jellyfin?','Check that your Jellyfin password has been set in the customer portal and that your account is marked Ready.'],['Where is Stremio setup?','Eligible plans show Stremio setup inside the customer portal. Use that page to install your personal add-on link.'],['Can I change plans?','Available plan changes are shown under Plans & billing. The portal explains whether a change starts now or at renewal.'],['How do I get help?',supportEmail?`Contact support at ${supportEmail}.`:'Use the Contact page for the currently configured support option.']];return res.send(infoShell(site,'FAQ','Quick answers for account, billing, Jellyfin and Stremio setup questions.',`<section class="storeWrap faqList">${faqs.map(([q,a])=>`<details class="faqItem"><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section>`));}catch(error){next(error);}});
  router.get('/contact',async(_req,res,next)=>{try{const{site,support}=await baseData();const actions=[support.supportEmail?`<a class="infoAction primary" href="mailto:${esc(support.supportEmail)}">Email ${esc(support.supportEmail)}</a>`:'',contactLink('Support link',support.supportUrl),contactLink('Docs',support.docsUrl),contactLink('Service status',support.statusUrl)].filter(Boolean).join('');return res.send(infoShell(site,'Contact','Get help with account access, billing, Jellyfin, Stremio or service questions.',`<section class="storeWrap contactPanel"><div><h2>Support routes</h2><p>Include your customer username and a short description of what you were trying to do. Do not send passwords or payment card details.</p></div><div class="infoActions">${actions||'<span class="infoMuted">No public support destination has been configured yet.</span>'}</div></section>`));}catch(error){next(error);}});
  router.get('/trust',async(_req,res,next)=>{try{const{site}=await baseData();return res.send(infoShell(site,'Trust & security','How CAPTAiNFiN keeps operational access, credentials and support workflows understandable.',`<section class="storeWrap infoGrid">${card('Credential boundaries','Customer portal passwords, Jellyfin passwords and payment-provider credentials are separate. Administrators do not see your passwords.')}${card('Operational visibility','Server health, provisioning failures, payment incidents and Stremio source failures appear in Needs Attention for administrator follow-up.')}${card('Safer support','Support should never ask for your password. Use official support destinations and keep sensitive payment details out of messages.')}</section>`));}catch(error){next(error);}});
  router.get(['/terms','/privacy','/refund-policy'],async(req,res,next)=>{try{const{site,support}=await baseData(),map={'/terms':['Terms','termsUrl'],'/privacy':['Privacy','privacyUrl'],'/refund-policy':['Refund policy','refundPolicyUrl']},[title,key]=map[req.path],configured=support[key];return res.send(infoShell(site,title,`${title} information for this CAPTAiNFiN service.`,configured?`<section class="storeWrap contactPanel"><div><h2>Official ${esc(title.toLowerCase())}</h2><p>The operator has configured an external document for the full current policy.</p></div><div class="infoActions">${contactLink(`Open ${title}`,configured)}</div></section>`:`<section class="storeWrap contactPanel"><div><h2>${esc(title)} not configured yet</h2><p>The operator should configure the final public ${esc(title.toLowerCase())} document in Admin Settings before relying on this page as legal text.</p></div><div class="infoActions"><a class="infoAction" href="/contact">Contact support</a></div></section>`));}catch(error){next(error);}});
  return router;
}
module.exports={createPublicPagesRouter,infoShell};
