'use strict';

const express=require('express');
const {query}=require('../db');
const csrf=require('../auth/csrf');
const ledger=require('../resellers/ledger');
const settings=require('../resellers/settings');
const runtimeSettings=require('./runtime-settings');
const branding=require('./branding');
const {esc}=require('./admin-html');

function gate(req,res,next){return req.session?.authUserId&&req.session?.authRole==='reseller'?next():res.redirect('/login?session=expired')}
function noStore(_q,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next()}
function token(req){return `<input type="hidden" name="_csrf" value="${esc(csrf.token(req))}">`}
function dt(v){return v?new Date(v).toLocaleString('en-GB'):'—'}
function money(minor,currency='GBP'){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:String(currency||'GBP').trim(),minimumFractionDigits:2}).format(Number(minor||0)/100)}catch{return `${currency} ${(Number(minor||0)/100).toFixed(2)}`}}
function redirect(res,key,message){return res.redirect(`/reseller/ledger?${key}=${encodeURIComponent(message)}`)}
async function reseller(userId){const r=await query('SELECT r.* FROM resellers r WHERE r.user_id=$1',[userId]);if(!r.rowCount)throw new Error('Reseller not found.');return r.rows[0]}
function shell(site,body){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Sales ledger · ${esc(site)}</title><link rel="icon" href="${esc(branding.assetUrl('favicon'))}"><link rel="stylesheet" href="/css/admin-original-base.css"><link rel="stylesheet" href="/css/admin-original-components.css"><link rel="stylesheet" href="/css/customer-360.css"><style>body{background:#0c1117}.wrap{max-width:1500px;margin:auto;padding:22px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:18px}.actions{display:flex;gap:6px;flex-wrap:wrap}.inlineForm{display:flex;gap:6px;align-items:end;flex-wrap:wrap}.inlineForm .formGroup{min-width:120px;margin:0}.amount.pos{color:#79d99b}.amount.neg{color:#ef8c8c}</style></head><body><main class="wrap"><header class="top"><a href="/reseller"><strong>${esc(site)} · Reseller</strong></a><div class="actions"><a class="button secondary btn-sm" href="/reseller">Dashboard</a><a class="button secondary btn-sm" href="/reseller/security">Security</a></div></header>${body}</main></body></html>`}

async function page(req){
 await runtimeSettings.ensureLoaded();const r=await reseller(req.session.authUserId),cfg=await settings.forReseller(r.id),rows=await ledger.list(r.id),customers=await query(`SELECT id,display_name FROM customers WHERE reseller_id=$1 ORDER BY is_reseller_owner,display_name`,[r.id]);
 const net=rows.reduce((sum,row)=>sum+(row.voided_at?0:row.sale_type==='refund'?-Number(row.amount_minor):['sale','adjustment'].includes(row.sale_type)?Number(row.amount_minor):0),0);
 const table=rows.length?`<div class="tableWrap"><table class="dataTable responsiveTable"><thead><tr><th>When</th><th>Customer</th><th>Type</th><th>Amount</th><th>Reference</th><th>Correction</th></tr></thead><tbody>${rows.map(row=>{const signed=row.sale_type==='refund'?-Number(row.amount_minor):Number(row.amount_minor);const remaining=Math.max(0,Number(row.amount_minor||0)-Number(row.refunded_minor||0));return `<tr><td>${esc(dt(row.created_at))}</td><td><strong>${esc(row.display_name||'—')}</strong><div class="subText">${esc(row.plan_name||'')}</div></td><td><span class="pill ${row.voided_at?'bad':row.sale_type==='refund'?'warn':''}">${esc(row.voided_at?'voided':row.sale_type)}</span></td><td class="amount ${signed<0?'neg':'pos'}">${esc(money(signed,row.currency))}</td><td>${esc(row.external_reference||'—')}<div class="subText">${esc(row.note||'')}</div></td><td>${!row.voided_at&&['sale','adjustment'].includes(row.sale_type)&&Number(row.amount_minor)>0?`<details><summary>Refund / void</summary><form class="formPanel" method="post" action="/reseller/ledger/${esc(row.id)}/refund">${token(req)}<div class="formGroup"><label>Refund amount</label><input class="input" type="number" name="amount" min="0.01" max="${(remaining/100).toFixed(2)}" step="0.01" value="${(remaining/100).toFixed(2)}"></div><div class="formGroup"><label>Reference</label><input class="input" name="externalReference" maxlength="200"></div><div class="formGroup"><label>Note</label><input class="input" name="note" maxlength="500"></div><button class="button secondary btn-sm" ${remaining<=0?'disabled':''}>Record refund</button></form><form method="post" action="/reseller/ledger/${esc(row.id)}/void">${token(req)}<input class="input" name="reason" maxlength="500" placeholder="Void reason" required><button class="button btn-danger btn-sm">Void entry</button></form></details>`:'—'}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No ledger entries yet.</div>';
 const body=`${req.query.message?`<div class="notice success">${esc(req.query.message)}</div>`:''}${req.query.error?`<div class="notice error">${esc(req.query.error)}</div>`:''}<div class="statusBanner"><strong>Append-only accounting.</strong> Refunds, voids and adjustments correct reseller-reported revenue only. They never silently disable, extend or change a Jellyfin entitlement.</div><div class="metrics"><div class="metric"><div class="metricLabel">Net recorded revenue</div><div class="metricValue">${esc(money(net,cfg.ledgerCurrency))}</div></div><div class="metric"><div class="metricLabel">Ledger entries</div><div class="metricValue">${rows.length}</div></div></div><section class="section"><div class="sectionHead"><h2>Manual adjustment</h2><span class="muted">Positive or negative · ${esc(cfg.ledgerCurrency)}</span></div>${customers.rowCount?`<form class="formPanel inlineForm" method="post" action="/reseller/ledger/adjustment">${token(req)}<div class="formGroup"><label>Customer</label><select class="input" name="customerId">${customers.rows.map(c=>`<option value="${esc(c.id)}">${esc(c.display_name||'Customer')}</option>`).join('')}</select></div><div class="formGroup"><label>Amount</label><input class="input" type="number" name="amount" step="0.01" required placeholder="-5.00 or 5.00"></div><div class="formGroup"><label>Reference</label><input class="input" name="externalReference" maxlength="200"></div><div class="formGroup"><label>Reason</label><input class="input" name="note" maxlength="500" required></div><button class="button secondary">Record adjustment</button></form>`:'<div class="empty">Create a customer before recording an adjustment.</div>'}</section><section class="section"><div class="sectionHead"><h2>Sales ledger</h2><span class="muted">Latest 1,000 entries</span></div>${table}</section>`;
 return shell(runtimeSettings.siteName(),body);
}

function createResellerLedgerRouter(){const r=express.Router();r.use('/reseller/ledger',gate,noStore);r.use((req,res,next)=>req.method==='POST'?(csrf.verify(req)?next():res.status(403).send('Invalid security token')):next());r.get('/reseller/ledger',async(req,res,next)=>{try{return res.send(await page(req))}catch(e){next(e)}});r.post('/reseller/ledger/adjustment',async(req,res)=>{try{const owner=await reseller(req.session.authUserId);await ledger.adjustment({resellerId:owner.id,customerId:req.body.customerId,amount:req.body.amount,note:req.body.note,externalReference:req.body.externalReference,actorUserId:req.session.authUserId});return redirect(res,'message','Ledger adjustment recorded.')}catch(e){return redirect(res,'error',e.message)}});r.post('/reseller/ledger/:id/refund',async(req,res)=>{try{const owner=await reseller(req.session.authUserId);await ledger.refund({resellerId:owner.id,saleId:req.params.id,amount:req.body.amount,note:req.body.note,externalReference:req.body.externalReference,actorUserId:req.session.authUserId});return redirect(res,'message','Refund recorded in the reseller ledger.')}catch(e){return redirect(res,'error',e.message)}});r.post('/reseller/ledger/:id/void',async(req,res)=>{try{const owner=await reseller(req.session.authUserId);await ledger.voidEntry({resellerId:owner.id,saleId:req.params.id,reason:req.body.reason,actorUserId:req.session.authUserId});return redirect(res,'message','Ledger entry voided.')}catch(e){return redirect(res,'error',e.message)}});return r}
module.exports={createResellerLedgerRouter,page};
