'use strict';
const {query}=require('../db');
const customers=require('../customers');
const {esc}=require('./admin-html');
const runtimeSettings=require('./runtime-settings');
const branding=require('./branding');
async function settings(){const r=await query(`SELECT setting_key,setting_value FROM platform_settings WHERE setting_key IN ('storefront','storefront_features')`);const m=Object.fromEntries(r.rows.map(x=>[x.setting_key,x.setting_value]));return{copy:m.storefront||{},features:Array.isArray(m.storefront_features)?m.storefront_features:[]}}
function planCard(p,target){const price=Number(p.price_minor)===0?'Free':'$'+(Number(p.price_minor)/100).toFixed(Number(p.price_minor)%100?2:0);return `<article class="plan ${p.code==='yearly'?'featured':''}"><h3>${esc(p.name)}</h3><div class="desc">${esc(p.description)}</div><div class="price">${esc(price)}</div><div class="currency">${esc(p.billing_interval==='trial'?'24 hours':p.currency+' · '+p.billing_interval.replace('_',' '))}</div><ul><li>${esc(p.streams)} concurrent stream${Number(p.streams)===1?'':'s'}</li><li>${p.allow_downloads?'Downloads included':'Streaming access'}</li><li>Movies and TV access</li><li>Self-service account portal</li></ul><a class="btn ${p.code==='yearly'?'':'alt'}" href="${target}">${target==='/account'?'Choose in account':target==='/account/register'?'Create account':'Sign in'}</a></article>`}
async function storefrontPage(req,res){try{await runtimeSettings.ensureLoaded();const [plans,store]=await Promise.all([customers.listPublicPlans(),settings()]);const open=runtimeSettings.publicRegistrationOpen(),logged=Boolean(req.session?.customerId),target=logged?'/account':open?'/account/register':'/account/login',site=process.env.SITE_NAME||'CAPTaINFiN';res.setHeader('Cache-Control','public, max-age=60');return res.send(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${esc(site)} · Store</title><link rel="icon" href="${esc(branding.assetUrl('favicon'))}"><style>html,body{margin:0;background:#0d0f12;color:#f4f7fa;min-height:100vh}.brandLockup{display:inline-flex;align-items:center;gap:9px}.brandLockup img{width:30px;height:30px;border-radius:8px;object-fit:cover}</style><link rel="stylesheet" href="/css/storefront.css"></head><body><div class="wrap"><header class="top"><a class="brand brandLockup" href="/"><img src="${esc(branding.assetUrl('logo'))}" alt=""><span>${esc(site)}</span></a><div class="actions"><a class="btn alt" href="/account/login">Sign in</a>${logged?'<a class="btn" href="/account">My account</a>':open?'<a class="btn" href="/account/register">Get started</a>':''}</div></header></div><main><section class="hero"><div class="wrap"><div class="eyebrow">Premium streaming access</div><h1>${esc(store.copy.heroTitle||'Your entertainment. One simple subscription.')}</h1><p>${esc(store.copy.heroSubtitle||'Movies and TV, available wherever you watch.')}</p><div class="heroBtns"><a class="btn" href="${target}">${logged?'Open my account':open?'Get started':'Sign in'}</a><a class="btn alt" href="#plans">View plans</a></div></div></section><section class="section"><div class="wrap"><h2>${esc(store.copy.featureTitle||'Everything you need to watch your way')}</h2><p class="lead">Simple access, sensible limits and a self-service account portal.</p><div class="features">${store.features.map((f,i)=>`<div class="feature"><div class="mark">0${i+1}</div><strong>${esc(f)}</strong></div>`).join('')}</div></div></section><section class="section" id="plans"><div class="wrap"><h2>Choose your plan</h2><p class="lead">Paid plans include multiple concurrent streams and downloads.</p><div class="pricing">${plans.map(p=>planCard(p,target)).join('')}</div>${open?'':`<div class="notice">New registrations are currently closed while the Store is being commissioned. Existing customers can still sign in.</div>`}</div></section></main><footer class="footer"><div class="wrap"><span>© ${new Date().getFullYear()} ${esc(site)}</span><span><a href="/account/login">Customer sign in</a> · <a href="/login">Administration</a></span></div></footer></body></html>`)}catch(e){console.error('Storefront failed:',e.message);return res.status(500).send('Store temporarily unavailable')}}
module.exports={storefrontPage,settings};
