'use strict';
const {query}=require('../db');
const KEY='support_policy_v1';
const DEFAULTS=Object.freeze({supportEmail:'',supportUrl:'',docsUrl:String(process.env.PUBLIC_DOCS_URL||'').trim(),statusUrl:'',termsUrl:'',privacyUrl:'',refundPolicyUrl:'',companyName:'',companyAddress:'',companyTaxId:''});
function text(v,n=500){return String(v||'').trim().slice(0,n)}
function safeUrl(v){const value=text(v,500);if(!value)return'';const url=new URL(value);if(!['https:','http:'].includes(url.protocol))throw new Error('Links must use http or https.');return url.toString()}
function normalize(v={}){return{supportEmail:text(v.supportEmail,254).toLowerCase(),supportUrl:v.supportUrl?safeUrl(v.supportUrl):'',docsUrl:v.docsUrl?safeUrl(v.docsUrl):'',statusUrl:v.statusUrl?safeUrl(v.statusUrl):'',termsUrl:v.termsUrl?safeUrl(v.termsUrl):'',privacyUrl:v.privacyUrl?safeUrl(v.privacyUrl):'',refundPolicyUrl:v.refundPolicyUrl?safeUrl(v.refundPolicyUrl):'',companyName:text(v.companyName,200),companyAddress:text(v.companyAddress,1000),companyTaxId:text(v.companyTaxId,120)}}
async function get(){const r=await query('SELECT setting_value FROM platform_settings WHERE setting_key=$1',[KEY]);return normalize({...DEFAULTS,...(r.rows[0]?.setting_value||{})})}
async function save(input,actorUserId=null){const value=normalize(input);if(value.supportEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.supportEmail))throw new Error('Enter a valid support email address.');await query(`INSERT INTO platform_settings(setting_key,setting_value,updated_by) VALUES($1,$2::jsonb,$3) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[KEY,JSON.stringify(value),actorUserId]);await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.support_policy.update','platform_setting',$2,$3::jsonb)`,[actorUserId,KEY,JSON.stringify({configured:Object.values(value).filter(Boolean).length,docsPublished:Boolean(value.docsUrl)})]);return value}
module.exports={KEY,DEFAULTS,get,save,normalize};
