'use strict';
const express=require('express');
const csrf=require('../auth/csrf');
const {esc}=require('../platform/admin-html');
const tmdb=require('./tmdb');
const catalog=require('./media-catalog');
const submitter=require('./media-submit');

const submitWindows=new Map();
function site(){return process.env.SITE_NAME||'CAPTAiNFiN'}
function gate(req,res,next){if(req.session?.customerId)return next();return res.redirect('/account/login?next='+encodeURIComponent(req.originalUrl||'/media'))}
function noStore(_req,res,next){res.setHeader('Cache-Control','no-store, private, max-age=0');res.setHeader('Pragma','no-cache');next()}
function submissionAllowed(customerId){const now=Date.now(),windowMs=60*60*1000,max=20,key=String(customerId);let b=submitWindows.get(key);if(!b||now-b.started>windowMs)b={started:now,count:0};b.count++;submitWindows.set(key,b);return b.count<=max}
function statusKind(status){if(status==='available')return'good';if(status==='failed'||status==='declined')return'bad';if(status==='searching'||status==='pending')return'warn';return'accent'}
function nav(active){return`<nav class="mediaNav"><a class="${active==='discover'?'active':''}" href="/media">Discover</a><a class="${active==='movies'?'active':''}" href="/media/movies">Movies</a><a class="${active==='tv'?'active':''}" href="/media/tv">TV</a><a class="${active==='mine'?'active':''}" href="/media/mine">My Requests</a></nav>`}
function shell({active,title,subtitle='',body}){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${esc(title)} · ${esc(site())}</title><link rel="stylesheet" href="/css/admin-original-base.css"><link rel="stylesheet" href="/css/admin-original-components.css"><link rel="stylesheet" href="/css/media-discovery.css"></head><body><div class="mediaPortal"><header class="mediaTop"><a class="mediaBrand" href="/media"><img src="/logo.jpg" alt=""><span>${esc(site())}</span></a>${nav(active)}<div class="mediaUser"><a class="button secondary btn-sm" href="/account">Account</a></div></header><main class="mediaContent"><div class="mediaHero"><div><h1>${esc(title)}</h1><div class="muted">${esc(subtitle)}</div></div>${active!=='mine'?`<form class="mediaSearch" method="get" action="${active==='tv'?'/media/tv':'/media/movies'}"><input class="input" name="q" maxlength="120" placeholder="Search movies and TV"><button class="button">Search</button></form>`:''}</div>${body}</main></div></body></html>`}
function existingMap(rows){const m=new Map();for(const r of rows){if(r.tmdb_id)m.set(`${r.media_type}:${r.tmdb_id}`,r)}return m}
function mediaCard(item,options,prior,token){const poster=tmdb.posterUrl(item.posterPath);const key=`${item.mediaType}:${item.tmdbId}`;const existing=prior.get(key);const optionHtml=options.map(o=>`<option value="${esc(o.id)}">${esc(o.name)}</option>`).join('');let action;if(existing)action=`<div class="mediaActions"><span class="pill ${statusKind(existing.status)}">${esc(existing.status)}</span><a class="button secondary btn-sm" href="/media/mine">Details</a></div>`;else if(!options.length)action='<div class="mediaActions"><span class="pill">No quality route</span></div>';else action=`<form class="mediaActions" method="post" action="/media/submit"><input type="hidden" name="_csrf" value="${esc(token)}"><input type="hidden" name="mediaType" value="${esc(item.mediaType)}"><input type="hidden" name="tmdbId" value="${esc(item.tmdbId)}"><input type="hidden" name="title" value="${esc(item.title)}"><input type="hidden" name="year" value="${esc(item.year||'')}"><input type="hidden" name="posterPath" value="${esc(item.posterPath||'')}"><input type="hidden" name="backdropPath" value="${esc(item.backdropPath||'')}"><select class="input qualitySelect" name="tierId">${optionHtml}</select><button class="button">Request</button></form>`;return`<article class="posterCard"><div class="posterArt">${poster?`<img loading="lazy" src="${esc(poster)}" alt="">`:'<div class="posterEmpty">No poster</div>'}</div><div class="posterBody"><div class="posterName" title="${esc(item.title)}">${esc(item.title)}</div><div class="posterMeta">${esc(item.mediaType==='series'?'TV':'Movie')}${item.year?' · '+esc(item.year):''}${item.voteAverage?' · ★ '+esc(item.voteAverage.toFixed(1)):''}</div><div class="posterOverview">${esc(item.overview||'No description available.')}</div>${action}</div></article>`}
function historyBody(rows){const counts={pending:0,added:0,searching:0,available:0};for(const x of rows)if(counts[x.status]!==undefined)counts[x.status]++;return`<div class="statusGrid"><div class="statusCard"><strong>${rows.length}</strong><span>Total</span></div><div class="statusCard"><strong>${counts.pending}</strong><span>Pending</span></div><div class="statusCard"><strong>${counts.added+counts.searching}</strong><span>In progress</span></div><div class="statusCard"><strong>${counts.available}</strong><span>Available</span></div></div><div class="historyList">${rows.length?rows.map(x=>{const p=tmdb.posterUrl(x.poster_path,'w185');return`<div class="historyItem">${p?`<img class="historyThumb" src="${esc(p)}" alt="">`:'<div class="historyThumb"></div>'}<div><div class="historyTitle">${esc(x.title||'Untitled')}</div><div class="historyMeta">${esc(x.media_type==='series'?'TV':'Movie')} · ${esc(x.quality_name||'Quality not set')}${x.year?' · '+esc(x.year):''}${x.instance_name?' · '+esc(x.instance_name):''}</div>${x.last_error?`<div class="historyMeta inlineBad">${esc(x.last_error)}</div>`:''}</div><div class="historyStatus"><span class="pill ${statusKind(x.status)}">${esc(x.status)}</span><div class="historyMeta">${esc(new Date(x.created_at).toLocaleDateString())}</div></div></div>`}).join(''):'<div class="mediaNotice">You have not requested anything yet.</div>'}</div>`}
async function discovery(req,active,forcedType=null){const history=await catalog.history(req.session.customerId),prior=existingMap(history),token=csrf.token(req);let items=[],error=null;try{if(req.query.q){items=await tmdb.search(forcedType||'movie',req.query.q)}else{items=await tmdb.trending();if(forcedType)items=items.filter(x=>x.mediaType===forcedType)}}catch(e){error=e.message}const movieOptions=await catalog.options('movie'),seriesOptions=await catalog.options('series');const cards=items.map(x=>mediaCard(x,x.mediaType==='series'?seriesOptions:movieOptions,prior,token)).join('');const title=active==='movies'?'Movies':active==='tv'?'TV':'Discover';const body=`${req.query.message?`<div class="notice success">${esc(req.query.message)}</div>`:''}${req.query.error?`<div class="notice error">${esc(req.query.error)}</div>`:''}${error?`<div class="mediaNotice">${esc(error)}</div>`:''}${!tmdb.enabled()?'<div class="mediaNotice">TMDB discovery is not configured yet.</div>':''}<div class="posterGrid">${cards||'<div class="mediaNotice">No titles found.</div>'}</div>`;return shell({active,title,subtitle:req.query.q?`Search results for “${String(req.query.q).slice(0,120)}”`:'Browse media and choose the quality you want',body})}
function createMediaPortalRouter(){const r=express.Router();r.use('/media',gate,noStore);r.get('/media',async(req,res,next)=>{try{return res.send(await discovery(req,'discover'))}catch(e){next(e)}});r.get('/media/movies',async(req,res,next)=>{try{return res.send(await discovery(req,'movies','movie'))}catch(e){next(e)}});r.get('/media/tv',async(req,res,next)=>{try{return res.send(await discovery(req,'tv','series'))}catch(e){next(e)}});r.get('/media/mine',async(req,res,next)=>{try{const rows=await catalog.history(req.session.customerId);const notices=`${req.query.message?`<div class="notice success">${esc(req.query.message)}</div>`:''}${req.query.error?`<div class="notice error">${esc(req.query.error)}</div>`:''}`;return res.send(shell({active:'mine',title:'My Requests',subtitle:'Track everything you have asked for',body:notices+historyBody(rows)}))}catch(e){next(e)}});r.post('/media/submit',async(req,res)=>{if(!csrf.verify(req))return res.status(403).send('Invalid or expired security token');if(!submissionAllowed(req.session.customerId))return res.redirect('/media?error='+encodeURIComponent('Too many requests. Try again later.'));try{await submitter.submit({customerId:req.session.customerId,mediaType:req.body.mediaType,tmdbId:req.body.tmdbId,tierId:req.body.tierId,title:req.body.title,year:req.body.year,posterPath:req.body.posterPath,backdropPath:req.body.backdropPath});return res.redirect('/media/mine?message='+encodeURIComponent('Request submitted for approval.'))}catch(e){return res.redirect('/media?error='+encodeURIComponent(String(e.message||'Could not submit request').slice(0,200)))}});return r}
module.exports={createMediaPortalRouter,shell,mediaCard,historyBody};
