'use strict';

const crypto = require('crypto');
const { query, transaction } = require('../db');
const commerce = require('./commerce-control');
const serviceCreditReservations = require('./service-credit-reservations');
const CHECKOUT_PROVIDERS = ['stripe', 'paypal', 'coingate'];
function hash(raw){return crypto.createHash('sha256').update(String(raw)).digest('hex');}
function rawNonce(){return crypto.randomBytes(32).toString('base64url');}
function safeSnapshot(value){if(!value||typeof value!=='object'||Array.isArray(value))return{};const json=JSON.stringify(value);if(Buffer.byteLength(json,'utf8')>32768)throw new Error('Checkout commercial snapshot is too large.');return value;}
async function settleReservation(client,intentId,state){if(!intentId)return;const reservationState=state==='completed'?'consumed':state==='expired'?'expired':'released';await client.query(`UPDATE discount_checkout_reservations SET state=$2,consumed_at=CASE WHEN $2='consumed' THEN NOW() ELSE consumed_at END,released_at=CASE WHEN $2='released' THEN NOW() ELSE released_at END,updated_at=NOW() WHERE checkout_intent_id=$1 AND state='reserved'`,[intentId,reservationState]);await serviceCreditReservations.settle(client,intentId,state);}
async function createIntent({scope,customerId=null,planId=null,planPriceId=null,provider,checkoutMode='subscription',ttlMinutes=30,commercialSnapshot={}}){await commerce.assertOpen();if(scope!=='customer')throw new Error('Invalid checkout scope.');if(!CHECKOUT_PROVIDERS.includes(provider))throw new Error('Invalid checkout provider.');if(!['payment','subscription'].includes(checkoutMode))throw new Error('Invalid checkout mode.');const nonce=rawNonce(),snapshot=safeSnapshot(commercialSnapshot),maxTtl=provider==='coingate'?130:60,expires=new Date(Date.now()+Math.max(5,Math.min(maxTtl,Number(ttlMinutes)||30))*60000);if(planPriceId&&String(snapshot.planPriceId||'')!==String(planPriceId))throw new Error('Checkout price does not match the commercial snapshot.');const row=await transaction(async client=>{if(!customerId)throw new Error('Checkout owner is required.');const expired=await client.query(`UPDATE billing_checkout_intents SET state='expired',updated_at=NOW() WHERE customer_id=$1 AND state='open' AND expires_at<=NOW() RETURNING id`,[customerId]);for(const x of expired.rows)await settleReservation(client,x.id,'expired');const existing=await client.query(`SELECT id,provider,checkout_mode,expires_at FROM billing_checkout_intents WHERE customer_id=$1 AND state='open' LIMIT 1 FOR UPDATE`,[customerId]);if(existing.rowCount)throw new Error('A checkout is already in progress. Finish or cancel it before starting another one.');const created=await client.query(`INSERT INTO billing_checkout_intents(scope,customer_id,plan_id,plan_price_id,provider,checkout_mode,nonce_hash,expires_at,commercial_snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) RETURNING *`,[scope,customerId,planId,planPriceId,provider,checkoutMode,hash(nonce),expires,JSON.stringify(snapshot)]);return created.rows[0]});return{...row,nonce};}
async function attachProviderCheckout(intentId,providerCheckoutId){const result=await query(`UPDATE billing_checkout_intents SET provider_checkout_id=$2,updated_at=NOW() WHERE id=$1 AND state='open' RETURNING *`,[intentId,String(providerCheckoutId||'').slice(0,300)]);if(!result.rowCount)throw new Error('Checkout intent is no longer open.');return result.rows[0];}
function verifyRow(row,{nonce,providerCheckoutId=null,scope=null,provider=null,ownerId=null}={}){if(!row)throw new Error('Checkout intent not found.');if(row.state!=='open'||new Date(row.expires_at)<=new Date())throw new Error('Checkout intent has expired or was already used.');if(!nonce||hash(nonce)!==row.nonce_hash)throw new Error('Checkout state verification failed.');if(providerCheckoutId&&row.provider_checkout_id&&String(row.provider_checkout_id)!==String(providerCheckoutId))throw new Error('Provider checkout does not match the local checkout intent.');if(scope&&row.scope!==scope)throw new Error('Checkout intent belongs to a different billing scope.');if(provider&&row.provider!==provider)throw new Error('Checkout intent belongs to a different provider.');if(ownerId&&String(row.customer_id)!==String(ownerId))throw new Error('Checkout intent belongs to a different account.');return row;}
async function findById(intentId){if(!intentId)return null;const result=await query('SELECT * FROM billing_checkout_intents WHERE id=$1',[intentId]);return result.rows[0]||null;}
async function verify({intentId,nonce,providerCheckoutId=null,scope=null,provider=null,ownerId=null}){return verifyRow(await findById(intentId),{nonce,providerCheckoutId,scope,provider,ownerId});}
async function consume({intentId,nonce,providerCheckoutId=null,state='completed',scope=null,provider=null,ownerId=null}){if(!['completed','cancelled','failed'].includes(state))throw new Error('Invalid checkout completion state.');return transaction(async client=>{const result=await client.query('SELECT * FROM billing_checkout_intents WHERE id=$1 FOR UPDATE',[intentId]),row=verifyRow(result.rows[0],{nonce,providerCheckoutId,scope,provider,ownerId});const updated=await client.query(`UPDATE billing_checkout_intents SET state=$2,completed_at=CASE WHEN $2='completed' THEN NOW() ELSE completed_at END,updated_at=NOW() WHERE id=$1 RETURNING *`,[intentId,state]);await settleReservation(client,intentId,state);return updated.rows[0]});}
async function completeVerifiedProvider(provider,providerCheckoutId,state='completed'){if(!CHECKOUT_PROVIDERS.includes(provider))throw new Error('Invalid checkout provider.');if(!['completed','cancelled','failed'].includes(state))throw new Error('Invalid checkout completion state.');return transaction(async client=>{const result=await client.query(`SELECT * FROM billing_checkout_intents WHERE provider=$1 AND provider_checkout_id=$2 ORDER BY created_at DESC LIMIT 1 FOR UPDATE`,[provider,String(providerCheckoutId||'')]);if(!result.rowCount)return null;const row=result.rows[0];if(row.state===state)return row;
// Provider-confirmed completion is monotonic: a duplicate or late failure/cancel
// notification must never undo a payment that was already fulfilled locally.
// Conversely, a later authenticated success may recover an earlier local
// cancelled/failed marker because provider proof of payment is authoritative.
if(row.state==='completed')return row;if(state!=='completed'&&row.state!=='open')return row;const updated=await client.query(`UPDATE billing_checkout_intents SET state=$2,completed_at=CASE WHEN $2='completed' THEN COALESCE(completed_at,NOW()) ELSE completed_at END,updated_at=NOW() WHERE id=$1 RETURNING *`,[row.id,state]);await settleReservation(client,row.id,state);return updated.rows[0];});}
async function findProviderIntent(provider,providerCheckoutId){if(!CHECKOUT_PROVIDERS.includes(provider))return null;const r=await query(`SELECT * FROM billing_checkout_intents WHERE provider=$1 AND provider_checkout_id=$2 ORDER BY created_at DESC LIMIT 1`,[provider,String(providerCheckoutId||'')]);return r.rows[0]||null;}
function asMoney(value){const n=Number(value);return Number.isInteger(n)&&n>=0?n:null;}
function normalizeCurrency(value){return String(value||'').trim().toUpperCase();}
async function verifiedProviderContract({provider,providerCheckoutId,scope='customer',ownerId=null,planId=null,checkoutMode=null,providerMappingId=null,amountMinor=null,currency=null}){const row=await findProviderIntent(provider,providerCheckoutId);if(!row)throw new Error('Verified provider checkout has no matching local checkout intent.');if(row.provider!==provider)throw new Error('Provider checkout belongs to a different provider.');if(scope&&row.scope!==scope)throw new Error('Provider checkout belongs to a different billing scope.');if(ownerId&&String(row.customer_id)!==String(ownerId))throw new Error('Provider checkout belongs to a different account.');if(planId&&String(row.plan_id||'')!==String(planId))throw new Error('Provider checkout plan does not match the local checkout contract.');if(checkoutMode&&row.checkout_mode!==checkoutMode)throw new Error('Provider checkout mode does not match the local checkout contract.');const snapshot=safeSnapshot(row.commercial_snapshot||{});if(snapshot.kind!=='direct_plan'||String(snapshot.planId||'')!==String(row.plan_id||''))throw new Error('Checkout commercial snapshot is incomplete or does not match its plan.');if(row.plan_price_id&&String(snapshot.planPriceId||'')!==String(row.plan_price_id))throw new Error('Checkout commercial snapshot does not match its selected plan price.');if(snapshot.provider!==provider||snapshot.checkoutMode!==row.checkout_mode)throw new Error('Checkout commercial snapshot provider terms do not match the local intent.');if(providerMappingId&&String(snapshot.providerMappingId||'')!==String(providerMappingId))throw new Error('Provider price/plan does not match the checkout contract.');const expectedMinor=asMoney(snapshot.discountedMinor??snapshot.priceMinor),actualMinor=amountMinor==null?null:asMoney(amountMinor);if(actualMinor!=null&&expectedMinor!=null&&actualMinor!==expectedMinor)throw new Error(`Provider amount ${actualMinor} does not match checkout contract amount ${expectedMinor}.`);const expectedCurrency=normalizeCurrency(snapshot.currency),actualCurrency=currency==null?'':normalizeCurrency(currency);if(actualCurrency&&expectedCurrency&&actualCurrency!==expectedCurrency)throw new Error(`Provider currency ${actualCurrency} does not match checkout contract currency ${expectedCurrency}.`);return{intent:row,snapshot};}
async function alreadyCompletedByOwner({intentId,nonce,scope=null,provider=null,ownerId=null}){
  // A provider webhook can complete an intent before the browser's own return
  // redirect reaches verify() -- that is a successful payment, not an error, so
  // give the caller a way to detect it without weakening verify()'s own checks.
  // The nonce is still required to match, so this cannot be used to probe intent
  // state without the value only the original checkout redirect carries.
  if(!intentId||!nonce)return null;
  const row=await findById(intentId);
  if(!row||row.state!=='completed')return null;
  if(hash(nonce)!==row.nonce_hash)return null;
  if(scope&&row.scope!==scope)return null;
  if(provider&&row.provider!==provider)return null;
  if(ownerId&&String(row.customer_id)!==String(ownerId))return null;
  return row;
}
async function getOpenForOwner(scope,ownerId){const result=await query(`SELECT * FROM billing_checkout_intents WHERE customer_id=$1 AND state='open' AND expires_at>NOW() ORDER BY created_at DESC LIMIT 1`,[ownerId]);return result.rows[0]||null;}
async function cancelForOwner(scope,ownerId){return transaction(async client=>{const result=await client.query(`UPDATE billing_checkout_intents SET state='cancelled',updated_at=NOW() WHERE customer_id=$1 AND state='open' RETURNING id`,[ownerId]);for(const row of result.rows)await settleReservation(client,row.id,'cancelled');return result.rowCount;});}
module.exports={CHECKOUT_PROVIDERS,createIntent,attachProviderCheckout,findById,verify,consume,completeVerifiedProvider,findProviderIntent,verifiedProviderContract,alreadyCompletedByOwner,getOpenForOwner,cancelForOwner,hash,settleReservation};