'use strict';

const crypto=require('crypto');
const {query}=require('../db');
const registry=require('./registry');
const provisioning=require('./provisioning');
const policy=require('./policy');
const laneOverrides=require('./lane-policy-overrides');

const CONTROLLED_FIELDS=['IsAdministrator','IsHidden','IsDisabled','EnableAllDevices','EnableAllFolders','EnabledFolders','EnableAllChannels','EnableRemoteAccess','EnableMediaPlayback','EnableAudioPlaybackTranscoding','EnableVideoPlaybackTranscoding','EnablePlaybackRemuxing','EnableContentDownloading','EnableSyncTranscoding','EnableMediaConversion','EnableContentDeletion','EnableRemoteControlOfOtherUsers','EnableSharedDeviceControl','EnableLiveTvManagement','EnableLiveTvAccess','EnableSubtitleManagement','EnableUserPreferenceAccess','SyncPlayAccess'];
const DISABLED_TECHNICAL=policy.flattenEffective(policy.effectiveTechnicalPolicy(null,null));
function clamp(v,f,min,max){const n=Number.parseInt(v,10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):f}
async function settings(){const r=await query(`SELECT setting_value FROM platform_settings WHERE setting_key='jellyfin_drift_policy'`),v=r.rows[0]?.setting_value||{};return{healthyMinutes:clamp(v.healthyMinutes,360,30,1440),driftMinutes:clamp(v.driftMinutes,60,15,720),failureBaseMinutes:clamp(v.failureBaseMinutes,15,5,360),failureMaxMinutes:clamp(v.failureMaxMinutes,360,15,1440),batchSize:clamp(v.batchSize,100,1,1000)}}
async function saveSettings(input,actorUserId=null){const value={healthyMinutes:clamp(input.healthyMinutes,360,30,1440),driftMinutes:clamp(input.driftMinutes,60,15,720),failureBaseMinutes:clamp(input.failureBaseMinutes,15,5,360),failureMaxMinutes:clamp(input.failureMaxMinutes,360,15,1440),batchSize:clamp(input.batchSize,100,1,1000)};if(value.failureMaxMinutes<value.failureBaseMinutes)throw new Error('Maximum failure backoff must be at least the base backoff.');await query(`INSERT INTO platform_settings(setting_key,setting_value) VALUES('jellyfin_drift_policy',$1::jsonb) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_at=NOW()`,[JSON.stringify(value)]);await query(`INSERT INTO audit_log(actor_user_id,action,entity_type,entity_id,metadata) VALUES($1,'admin.jellyfin_drift.settings','platform_setting','jellyfin_drift_policy',$2::jsonb)`,[actorUserId,JSON.stringify(value)]);return value}
function hash(value){return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex')}
function normalizeValue(field,value){if(field==='EnabledFolders')return Array.from(new Set(Array.isArray(value)?value.map(String):[])).sort();if(field==='SyncPlayAccess')return String(value||'None');return Boolean(value)}
function normalizedPolicy(source){const out={};for(const field of CONTROLLED_FIELDS)out[field]=normalizeValue(field,source?.[field]);return out}
function sameValue(a,b){if(Array.isArray(a)||Array.isArray(b))return JSON.stringify(a||[])===JSON.stringify(b||[]);return a===b}
function comparePolicy({desiredPolicy,remotePolicy,expectedUsername,remoteUsername,missingLibraries=[]}){const desired=normalizedPolicy(desiredPolicy),remote=normalizedPolicy(remotePolicy),differences=[];if(String(remoteUsername||'')!==String(expectedUsername||''))differences.push({field:'Username',expected:String(expectedUsername||''),actual:String(remoteUsername||'')});for(const field of CONTROLLED_FIELDS)if(!sameValue(desired[field],remote[field]))differences.push({field,expected:desired[field],actual:remote[field]});if(missingLibraries.length)differences.push({field:'MissingLibraries',expected:[],actual:missingLibraries.map(String).sort()});return{desired,remote,differences,desiredHash:hash({username:expectedUsername,policy:desired}),remoteHash:hash({username:remoteUsername,policy:remote})}}
async function ensureRows(){await query(`INSERT INTO jellyfin_policy_drift(jellyfin_account_id,customer_id,server_id,status,next_check_at) SELECT ja.id,ja.customer_id,ja.server_id,'unknown',NOW() FROM jellyfin_accounts ja ON CONFLICT(jellyfin_account_id) DO UPDATE SET customer_id=EXCLUDED.customer_id,server_id=EXCLUDED.server_id`)}
async function customerContext(customerId,catalogCache=new Map()){const[entitlement,accountsResult]=await Promise.all([provisioning.currentEntitlement(customerId),query(`SELECT ja.*,js.enabled server_enabled,js.server_class,js.name server_name FROM jellyfin_accounts ja JOIN jellyfin_servers js ON js.id=ja.server_id WHERE ja.customer_id=$1 ORDER BY ja.is_primary DESC,ja.disabled ASC,ja.created_at ASC`,[customerId])]),accounts=accountsResult.rows;let activeAccount=null,effective=null;if(entitlement){activeAccount=accounts.find(a=>a.is_primary&&a.server_class===entitlement.server_class&&a.server_enabled)||accounts.find(a=>!a.disabled&&a.server_class===entitlement.server_class&&a.server_enabled)||accounts.find(a=>a.server_class===entitlement.server_class&&a.server_enabled)||null;const accessLane=entitlement.is_free_tier?'free':'primary';const[override,libOverrides,selection]=await Promise.all([laneOverrides.getPolicyOverride(customerId,accessLane),provisioning.getLibraryOverrides(customerId,accessLane),provisioning.getLibrarySelection(customerId)]),planKey=String(entitlement.plan_id||entitlement.id||entitlement.code);let catalog=catalogCache.get(planKey);if(!catalog){catalog=await provisioning.libraryCatalogForPlan(entitlement);catalogCache.set(planKey,catalog)}const technicalRows=policy.effectiveTechnicalPolicy(entitlement,override),entitlementRows=policy.libraryEntitlement(entitlement,libOverrides,catalog.names),visibleNames=policy.customerVisibleLibraries(entitlementRows,selection),mode=['all','exclude','include'].includes(entitlement.library_access_mode)?entitlement.library_access_mode:'all';effective={technical:policy.flattenEffective(technicalRows),visibleNames,unrestricted:mode==='all'&&libOverrides.length===0&&!selection,catalog}}return{customerId,entitlement,accounts,activeAccount,effective}}
async function desiredState(account,context){const disabled=!context.entitlement||!context.activeAccount||String(context.activeAccount.id)!==String(account.id);if(disabled)return{disabled:true,policy:provisioning.policyBody(DISABLED_TECHNICAL,true,{enableAllFolders:false,enabledFolders:[]}),missingLibraries:[]};const libraryAccess=await provisioning.resolveLibraryAccessForServer(account.server_id,context.effective.unrestricted,context.effective.visibleNames,false);return{disabled:false,policy:provisioning.policyBody(context.effective.technical,false,libraryAccess),missingLibraries:libraryAccess.missing||[]}}
async function persistSuccess(account,desired,comparison){const cfg=await settings(),status=comparison.differences.length?'drift':'in_sync',now=new Date(),next=new Date(now.getTime()+(status==='drift'?cfg.driftMinutes:cfg.healthyMinutes)*60000);await query(`INSERT INTO jellyfin_policy_drift(jellyfin_account_id,customer_id,server_id,status,desired_disabled,desired_hash,remote_hash,differences,last_checked_at,last_success_at,last_error,consecutive_failures,next_check_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$9,NULL,0,$10,NOW()) ON CONFLICT(jellyfin_account_id) DO UPDATE SET customer_id=EXCLUDED.customer_id,server_id=EXCLUDED.server_id,status=EXCLUDED.status,desired_disabled=EXCLUDED.desired_disabled,desired_hash=EXCLUDED.desired_hash,remote_hash=EXCLUDED.remote_hash,differences=EXCLUDED.differences,last_checked_at=EXCLUDED.last_checked_at,last_success_at=EXCLUDED.last_success_at,last_error=NULL,consecutive_failures=0,next_check_at=EXCLUDED.next_check_at,updated_at=NOW()`,[account.id,account.customer_id,account.server_id,status,desired.disabled,comparison.desiredHash,comparison.remoteHash,JSON.stringify(comparison.differences),now,next]);return{accountId:account.id,customerId:account.customer_id,status,differences:comparison.differences,nextCheckAt:next}}
async function persistFailure(account,status,error){const cfg=await settings(),prior=await query('SELECT consecutive_failures FROM jellyfin_policy_drift WHERE jellyfin_account_id=$1',[account.id]),failures=Number(prior.rows[0]?.consecutive_failures||0)+1,delay=Math.min(cfg.failureMaxMinutes,cfg.failureBaseMinutes*(2**Math.min(6,Math.max(0,failures-1)))),now=new Date(),next=new Date(now.getTime()+delay*60000);await query(`INSERT INTO jellyfin_policy_drift(jellyfin_account_id,customer_id,server_id,status,differences,last_checked_at,last_error,consecutive_failures,next_check_at,updated_at) VALUES($1,$2,$3,$4,'[]'::jsonb,$5,$6,$7,$8,NOW()) ON CONFLICT(jellyfin_account_id) DO UPDATE SET customer_id=EXCLUDED.customer_id,server_id=EXCLUDED.server_id,status=EXCLUDED.status,differences='[]'::jsonb,last_checked_at=EXCLUDED.last_checked_at,last_error=EXCLUDED.last_error,consecutive_failures=EXCLUDED.consecutive_failures,next_check_at=EXCLUDED.next_check_at,updated_at=NOW()`,[account.id,account.customer_id,account.server_id,status,now,String(error?.message||error).slice(0,1500),failures,next]);return{accountId:account.id,customerId:account.customer_id,status,error:String(error?.message||error),failures,nextCheckAt:next}}
async function auditAccount(accountId,{context=null,catalogCache=new Map()}={}){const ar=await query(`SELECT ja.*,js.enabled server_enabled,js.server_class,js.name server_name FROM jellyfin_accounts ja JOIN jellyfin_servers js ON js.id=ja.server_id WHERE ja.id=$1`,[accountId]);if(!ar.rowCount)throw new Error('Jellyfin account not found.');const account=ar.rows[0],ctx=context||await customerContext(account.customer_id,catalogCache);try{const desired=await desiredState(account,ctx),remote=await registry.request(account.server_id,`/Users/${encodeURIComponent(account.jellyfin_user_id)}`,{method:'GET',timeoutMs:10000});if(!remote||typeof remote!=='object'||!remote.Policy)throw new Error('Jellyfin returned an unexpected user record.');return persistSuccess(account,desired,comparePolicy({desiredPolicy:desired.policy,remotePolicy:remote.Policy,expectedUsername:account.jellyfin_username,remoteUsername:remote.Name,missingLibraries:desired.missingLibraries}))}catch(error){const message=String(error?.message||error),status=/\b404\b|not found/i.test(message)?'missing':'unreachable';return persistFailure(account,status,error)}}
async function dueAccounts({all=false,limit=null}={}){await ensureRows();const cfg=await settings(),safe=Math.max(1,Math.min(1000,Number(limit||cfg.batchSize)));const result=await query(`SELECT d.jellyfin_account_id,d.customer_id FROM jellyfin_policy_drift d JOIN jellyfin_accounts ja ON ja.id=d.jellyfin_account_id JOIN jellyfin_servers js ON js.id=ja.server_id WHERE js.enabled=TRUE AND($1::boolean OR d.next_check_at<=NOW()) ORDER BY d.next_check_at,d.updated_at LIMIT $2`,[Boolean(all),safe]);return result.rows}
async function auditDue({all=false,limit=null}={}){const rows=await dueAccounts({all,limit}),contexts=new Map(),catalogCache=new Map(),summary={total:rows.length,inSync:0,drift:0,unreachable:0,missing:0,results:[]};for(const row of rows){const customerId=String(row.customer_id);let context=contexts.get(customerId);if(!context){try{context=await customerContext(row.customer_id,catalogCache);contexts.set(customerId,context)}catch(error){const account=(await query('SELECT * FROM jellyfin_accounts WHERE id=$1',[row.jellyfin_account_id])).rows[0],result=await persistFailure(account,'unreachable',error);summary.results.push(result);summary.unreachable++;continue}}const result=await auditAccount(row.jellyfin_account_id,{context,catalogCache});summary.results.push(result);if(result.status==='in_sync')summary.inSync++;else if(result.status==='drift')summary.drift++;else if(result.status==='missing')summary.missing++;else summary.unreachable++}return summary}
async function listAuditRows(){await ensureRows();const result=await query(`SELECT d.*,ja.jellyfin_username,ja.jellyfin_user_id,ja.disabled,ja.is_primary,ja.last_policy_sync,js.name server_name,js.slug server_slug,js.health_status,c.display_name,c.email,u.username portal_username,p.name plan_name,p.code plan_code FROM jellyfin_policy_drift d JOIN jellyfin_accounts ja ON ja.id=d.jellyfin_account_id JOIN jellyfin_servers js ON js.id=ja.server_id JOIN customers c ON c.id=ja.customer_id LEFT JOIN app_users u ON u.id=c.user_id LEFT JOIN LATERAL(SELECT p.* FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.customer_id=c.id AND s.superseded_by IS NULL AND s.status IN('active','trialing','past_due','paused') AND s.current_period_end>NOW() ORDER BY s.current_period_end DESC,s.created_at DESC LIMIT 1)p ON TRUE ORDER BY CASE d.status WHEN'drift'THEN 0 WHEN'missing'THEN 1 WHEN'unreachable'THEN 2 WHEN'unknown'THEN 3 ELSE 4 END,d.updated_at DESC,c.display_name,js.name`);return result.rows}
async function stats(){await ensureRows();const result=await query(`SELECT COUNT(*)::int total,COUNT(*)FILTER(WHERE status='in_sync')::int in_sync,COUNT(*)FILTER(WHERE status='drift')::int drift,COUNT(*)FILTER(WHERE status='unreachable')::int unreachable,COUNT(*)FILTER(WHERE status='missing')::int missing,COUNT(*)FILTER(WHERE status='unknown')::int unknown FROM jellyfin_policy_drift`);return result.rows[0]}
async function clearForCustomer(customerId){await query(`UPDATE jellyfin_policy_drift SET status='unknown',next_check_at=NOW(),updated_at=NOW() WHERE customer_id=$1`,[customerId])}
module.exports={CONTROLLED_FIELDS,normalizeValue,normalizedPolicy,comparePolicy,ensureRows,customerContext,desiredState,auditAccount,auditDue,dueAccounts,listAuditRows,stats,clearForCustomer,settings,saveSettings};
