'use strict';

const{query}=require('../db');
const FALLBACK_METHODS=['Cash','Bank transfer','PayPal','Stripe','Other'];
function cleanCurrency(value){const code=String(value||'GBP').trim().toUpperCase();return/^[A-Z]{3}$/.test(code)?code:'GBP'}
async function defaults(){const result=await query(`SELECT setting_value FROM platform_settings WHERE setting_key='reseller_defaults_v2'`),value=result.rows[0]?.setting_value||{};return{ledgerCurrency:cleanCurrency(value.ledgerCurrency||'GBP'),paymentMethods:Array.isArray(value.paymentMethods)&&value.paymentMethods.length?value.paymentMethods.map(String):FALLBACK_METHODS,ownerAccountAllowed:value.ownerAccountAllowed!==false,defaultTierId:value.defaultTierId||null,customerPortalPolicy:['jellyfin_only','optional','portal_required'].includes(value.customerPortalPolicy)?value.customerPortalPolicy:'optional'}}
async function forReseller(resellerId){const[base,row]=await Promise.all([defaults(),query('SELECT ledger_currency,allowed_payment_methods,owner_account_allowed,customer_portal_policy,legal_name,tax_id,invoice_address,receipt_prefix FROM resellers WHERE id=$1',[resellerId])]);if(!row.rowCount)throw new Error('Reseller not found.');const reseller=row.rows[0];return{ledgerCurrency:cleanCurrency(reseller.ledger_currency||base.ledgerCurrency),paymentMethods:Array.isArray(reseller.allowed_payment_methods)&&reseller.allowed_payment_methods.length?reseller.allowed_payment_methods:base.paymentMethods,ownerAccountAllowed:reseller.owner_account_allowed!==false&&base.ownerAccountAllowed!==false,defaultTierId:base.defaultTierId,customerPortalPolicy:['jellyfin_only','optional','portal_required'].includes(reseller.customer_portal_policy)?reseller.customer_portal_policy:base.customerPortalPolicy,legalName:reseller.legal_name||'',taxId:reseller.tax_id||'',invoiceAddress:reseller.invoice_address||'',receiptPrefix:reseller.receipt_prefix||''}}
async function eligiblePlans(tierId,{owner=false,includeTrial=false}={}){const tier=await query(`SELECT catalogue_mode FROM reseller_tiers WHERE id=$1`,[tierId]);if(!tier.rowCount)return[];const mode=tier.rows[0].catalogue_mode||'all_eligible',explicit=mode==='allowlist';const result=await query(`SELECT p.* FROM plans p LEFT JOIN reseller_tier_plan_rules r ON r.tier_id=$1 AND r.plan_id=p.id AND r.active=TRUE WHERE p.active=TRUE AND p.archived_at IS NULL AND (p.effective_from IS NULL OR p.effective_from<=NOW()) AND (p.effective_until IS NULL OR p.effective_until>NOW()) AND p.audience IN('reseller','both') AND (NOT $2::boolean OR r.plan_id IS NOT NULL) AND (NOT $2::boolean OR CASE WHEN $3::boolean THEN r.allow_owner ELSE r.allow_customer END) AND (p.billing_interval<>'trial' OR ($4::boolean AND (NOT $2::boolean OR r.allow_trial))) ORDER BY p.sort_order,p.price_minor,p.name`,[tierId,explicit,owner,includeTrial]);return result.rows}
function validatePaymentMethod(settings,value){const requested=String(value||'').trim(),match=settings.paymentMethods.find(method=>method.toLowerCase()===requested.toLowerCase());if(!match)throw new Error('Choose one of the payment methods configured by the administrator.');return match}
module.exports={FALLBACK_METHODS,defaults,forReseller,eligiblePlans,validatePaymentMethod,cleanCurrency};
